import raw from '@/lib/guestSeed.json'

// The guest account shared with Android, generated by
// scripts/gen-guest-seed.mjs (never edit guestSeed.json by hand).

export interface SeedMovement {
  id: string
  wallet: string
  type: string
  amount: number
  category: string
  date: string
  time: string
  title: string
  currency?: string
  sub?: string
  merchant?: string
  note?: string
  counterparty?: string
  counterpartyKind?: string
  to?: string
  planned?: boolean
  series?: string
  goal?: string
  goalPlan?: boolean
  customBudget?: string
  loan?: { kind: string; due?: string }
  parentLoan?: string
  attachment?: { kind: string; name: string; file: string }
}

export interface Seed {
  principal: string
  currencies: string[]
  wallets: { id: string; name: string; type: string; currency: string; opening: number }[]
  categories: { id: string; parentId: string | null; kind: string; name: string; nameEn: string; vis: string }[]
  movements: SeedMovement[]
  budgets: { id: string; kind: string; category?: string; name?: string; icon?: string; walletIds: string[]; period: string; start?: string; end?: string; amount: number }[]
  goals: {
    id: string
    name: string
    icon: string
    target: number
    initial: number
    targetDate: string | null
    plan: { amount: number; frequency: string; wallet: string; start: string; endMode: string; count: number | null; endDate: string | null; autoConfirm: boolean; next: string; active: boolean } | null
  }[]
  series: { id: string; name: string; type?: string; amount: number; currency: string; wallet: string; category: string; sub?: string; interval: string; next: string; occurrences: number | null; endDate: string | null; autoConfirm: boolean; active: boolean }[]
  files: Record<string, string>
}

export const SEED = raw as Seed

const pad = (n: number) => String(n).padStart(2, '0')

// Day `day` ("L": the last one) of the month `offset` months from today's.
function monthDay(today: string, offset: number, day: number | 'L'): string {
  const [y, m] = today.split('-').map(Number)
  const first = new Date(Date.UTC(y, m - 1 + offset, 1))
  const last = new Date(Date.UTC(first.getUTCFullYear(), first.getUTCMonth() + 1, 0)).getUTCDate()
  return `${first.getUTCFullYear()}-${pad(first.getUTCMonth() + 1)}-${pad(day === 'L' ? last : Math.min(day, last))}`
}

// A seed date against `today` ('YYYY-MM-DD'): "M:o:d" a day of a month o
// months away, "T:o" o days away, "D:o" today's day number o months away,
// "N:d" the first day-d date strictly after today.
export function resolveSeedDate(spec: string, today: string): string {
  const [kind, a, b] = spec.split(':')
  if (kind === 'T') {
    const [y, m, d] = today.split('-').map(Number)
    const t = new Date(Date.UTC(y, m - 1, d + Number(a)))
    return `${t.getUTCFullYear()}-${pad(t.getUTCMonth() + 1)}-${pad(t.getUTCDate())}`
  }
  if (kind === 'M') return monthDay(today, Number(a), b === 'L' ? 'L' : Number(b))
  if (kind === 'D') return monthDay(today, Number(a), Number(today.slice(8, 10)))
  if (kind === 'N') {
    const here = monthDay(today, 0, Number(a))
    return here > today ? here : monthDay(today, 1, Number(a))
  }
  throw new Error(`Unknown seed date ${spec}`)
}
