package com.s2nova.app.data.mock

import android.content.Context
import com.s2nova.app.data.Currencies
import com.s2nova.app.data.Taxonomy
import com.s2nova.app.data.model.AppAlert
import com.s2nova.app.data.model.AttachmentMeta
import com.s2nova.app.data.model.BudgetKind
import com.s2nova.app.data.model.BudgetPeriod
import com.s2nova.app.data.model.BudgetProgress
import com.s2nova.app.data.model.CategoryBudget
import com.s2nova.app.data.model.CategoryNode
import com.s2nova.app.data.model.CounterpartyKind
import com.s2nova.app.data.model.Goal
import com.s2nova.app.data.model.GoalPlan
import com.s2nova.app.data.model.GoalPlanEnd
import com.s2nova.app.data.model.LoanKind
import com.s2nova.app.data.model.PaymentMethod
import com.s2nova.app.data.model.RecurrenceInterval
import com.s2nova.app.data.model.RecurringSeries
import com.s2nova.app.data.model.Transaction
import com.s2nova.app.data.model.TransactionStatus
import com.s2nova.app.data.model.TransactionType
import com.s2nova.app.data.model.Wallet
import com.s2nova.app.data.model.WalletType
import com.s2nova.app.data.repository.budgetStatusOf
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.time.LocalDate
import java.time.YearMonth
import java.util.Base64
import kotlin.math.min
import kotlin.math.roundToInt
import kotlin.math.roundToLong

// The guest account shared with Web (assets/guest_seed.json, generated by
// scripts/gen-guest-seed.mjs; never edit it by hand). Its relative dates are
// resolved against today when the guest session starts, and everything else
// (balances, budget spending, goal progress, Programado and plan counts,
// settled loans, alerts) is derived from the movements dated up to today,
// with the same rules Web's guestApi.ts and the backend use.

@Serializable
data class SeedWallet(val id: String, val name: String, val type: String, val currency: String, val opening: Double)

@Serializable
data class SeedCategory(val id: String, val parentId: String? = null, val kind: String, val name: String, val nameEn: String, val vis: String)

@Serializable
data class SeedLoan(val kind: String, val due: String? = null)

@Serializable
data class SeedAttachment(val kind: String, val name: String, val file: String)

@Serializable
data class SeedMovement(
    val id: String,
    val wallet: String,
    val type: String,
    val amount: Double,
    val category: String,
    val date: String,
    val time: String,
    val title: String,
    val currency: String? = null,
    val sub: String? = null,
    val merchant: String? = null,
    val note: String? = null,
    val counterparty: String? = null,
    val counterpartyKind: String? = null,
    val to: String? = null,
    val planned: Boolean = false,
    val series: String? = null,
    val goal: String? = null,
    val goalPlan: Boolean = false,
    val customBudget: String? = null,
    val loan: SeedLoan? = null,
    val parentLoan: String? = null,
    val attachment: SeedAttachment? = null,
)

@Serializable
data class SeedBudget(
    val id: String,
    val kind: String,
    val category: String? = null,
    val name: String? = null,
    val icon: String? = null,
    val walletIds: List<String> = emptyList(),
    val period: String,
    val start: String? = null,
    val end: String? = null,
    val amount: Double,
)

@Serializable
data class SeedPlan(
    val amount: Double,
    val frequency: String,
    val wallet: String,
    val start: String,
    val endMode: String,
    val count: Int? = null,
    val endDate: String? = null,
    val autoConfirm: Boolean,
    val next: String,
    val active: Boolean,
)

@Serializable
data class SeedGoal(val id: String, val name: String, val icon: String, val target: Double, val initial: Double, val targetDate: String? = null, val plan: SeedPlan? = null)

@Serializable
data class SeedSeries(
    val id: String,
    val name: String,
    val type: String = "EXPENSE",
    val amount: Double,
    val currency: String,
    val wallet: String,
    val category: String,
    val sub: String? = null,
    val interval: String,
    val next: String,
    val occurrences: Int? = null,
    val endDate: String? = null,
    val autoConfirm: Boolean,
    val active: Boolean,
)

@Serializable
data class SeedFile(
    val principal: String,
    val currencies: List<String>,
    val wallets: List<SeedWallet>,
    val categories: List<SeedCategory>,
    val movements: List<SeedMovement>,
    val budgets: List<SeedBudget>,
    val goals: List<SeedGoal>,
    val series: List<SeedSeries>,
    val files: Map<String, String>,
)

// The account as the repositories hold it.
data class GuestAccount(
    val principal: String,
    val currencies: List<String>,
    val categories: List<CategoryNode>,
    val wallets: List<Wallet>,
    val transactions: List<Transaction>,
    // Receipt bytes per movement id.
    val files: Map<String, ByteArray>,
    val budgets: List<BudgetProgress>,
    val goals: List<Goal>,
    val series: List<RecurringSeries>,
    val alerts: List<AppAlert>,
)

object GuestSeed {
    private val json = Json { ignoreUnknownKeys = true }
    private var text: String? = null

    fun init(context: Context) {
        if (text == null) text = context.assets.open("guest_seed.json").bufferedReader().use { it.readText() }
    }

    fun initFrom(seedText: String) {
        text = seedText
    }

    fun file(): SeedFile = json.decodeFromString(SeedFile.serializer(), text ?: error("GuestSeed.init(context) was not called"))

    private fun monthDay(today: LocalDate, offset: Long, day: String): LocalDate {
        val month = YearMonth.from(today).plusMonths(offset)
        return month.atDay(if (day == "L") month.lengthOfMonth() else min(day.toInt(), month.lengthOfMonth()))
    }

    // "M:o:d" a day of a month o months away, "T:o" o days away, "D:o"
    // today's day number o months away, "N:d" the first day-d date strictly
    // after today (as web resolveSeedDate).
    fun resolve(spec: String, today: LocalDate): String {
        val parts = spec.split(":")
        val date = when (parts[0]) {
            "T" -> today.plusDays(parts[1].toLong())
            "M" -> monthDay(today, parts[1].toLong(), parts[2])
            "D" -> monthDay(today, parts[1].toLong(), today.dayOfMonth.toString())
            "N" -> monthDay(today, 0, parts[1]).let { if (it.isAfter(today)) it else monthDay(today, 1, parts[1]) }
            else -> error("Unknown seed date $spec")
        }
        return date.toString()
    }

    private fun round(amount: Double, code: String): Double {
        val factor = Math.pow(10.0, Currencies.info(code).decimals.toDouble())
        return (amount * factor).roundToLong() / factor
    }

    private fun convert(amount: Double, from: String, to: String) = round(amount * Currencies.referenceRate(from, to), to)

    private fun paymentMethodFor(type: String) = when (type) {
        "CASH" -> PaymentMethod.CASH
        "NEQUI" -> PaymentMethod.NEQUI
        "DAVIPLATA" -> PaymentMethod.DAVIPLATA
        else -> PaymentMethod.BANK_TRANSFER
    }

    private fun parseColor(hex: String): Long = ("FF" + hex.removePrefix("#")).toLong(16)

    fun account(today: LocalDate = LocalDate.now(), english: Boolean = false, seed: SeedFile = file()): GuestAccount {
        val todayIso = today.toString()
        val at = { spec: String -> resolve(spec, today) }
        val principal = seed.principal
        val walletById = seed.wallets.associateBy { it.id }

        val categories = seed.categories.map { c ->
            val parent = c.parentId?.let { p -> Taxonomy.nodes.firstOrNull { it.id == p } }
            val name = if (english) c.nameEn else c.name
            val vis = parent?.vis ?: c.vis
            CategoryNode(c.id, null, c.kind == "INCOME", c.parentId, name, name, vis, parseColor(parent?.color ?: Taxonomy.visColor(vis)), custom = true, hidden = false, usage = 0)
        }

        val kept = seed.movements.map { it to at(it.date) }.filter { (m, date) -> date <= todayIso || m.planned }
        val files = mutableMapOf<String, ByteArray>()
        val built = kept.map { (m, date) ->
            val walletCurrency = walletById.getValue(m.wallet).currency
            val currency = m.currency ?: walletCurrency
            val target = m.to?.let { walletById.getValue(it).currency } ?: walletCurrency
            val foreign = currency != target
            val attachment = m.attachment?.let { a ->
                val data = seed.files[a.file] ?: return@let null
                val bytes = Base64.getDecoder().decode(data)
                files[m.id] = bytes
                AttachmentMeta("${m.id}-file", a.kind == "PDF", if (a.kind == "PDF") "application/pdf" else "image/png", a.name, bytes.size.toLong(), date)
            }
            Transaction(
                id = m.id,
                walletId = m.wallet,
                transferToWalletId = m.to,
                description = m.title,
                amount = m.amount,
                type = TransactionType.valueOf(m.type),
                status = if (m.planned) TransactionStatus.PLANNED else TransactionStatus.COMPLETED,
                category = if (m.type == "TRANSFER") com.s2nova.app.data.repository.CategoryRepository.TRANSFER else m.category,
                subcategoryId = m.sub,
                date = date,
                time = m.time,
                paymentMethod = paymentMethodFor(walletById.getValue(m.wallet).type),
                currency = currency,
                fxRate = if (foreign) Currencies.referenceRate(currency, target) else null,
                walletAmount = if (foreign) convert(m.amount, currency, target) else null,
                counterpartyKind = m.counterpartyKind?.let { runCatching { CounterpartyKind.valueOf(it) }.getOrNull() },
                customBudgetId = m.customBudget,
                attachment = attachment,
                merchant = m.merchant,
                note = m.note,
                goalId = m.goal,
                recurringSeriesId = m.series,
                loanKind = m.loan?.let { LoanKind.valueOf(it.kind) },
                counterpartyName = m.counterparty,
                dueDate = m.loan?.due?.let(at),
                parentLoanId = m.parentLoan,
            )
        }
        // A loan whose repayments cover it is settled by the last one.
        val transactions = built.map { t ->
            if (t.loanKind == null) return@map t
            val repayments = built.filter { it.parentLoanId == t.id }.sortedBy { it.date }
            if (repayments.isNotEmpty() && repayments.sumOf { it.amount } >= t.amount) t.copy(loanSettled = true, settledByTransactionId = repayments.last().id) else t
        }
        val completed = transactions.filter { it.status == TransactionStatus.COMPLETED }

        // Balances: the opening one plus every completed movement.
        val balance = seed.wallets.associate { it.id to it.opening }.toMutableMap()
        for (t in completed) {
            val moved = t.walletAmount ?: t.amount
            when (t.type) {
                TransactionType.INCOME -> balance[t.walletId] = balance.getValue(t.walletId) + moved
                TransactionType.EXPENSE -> balance[t.walletId] = balance.getValue(t.walletId) - moved
                TransactionType.TRANSFER -> {
                    balance[t.walletId] = balance.getValue(t.walletId) - t.amount
                    t.transferToWalletId?.let { balance[it] = balance.getValue(it) + moved }
                }
            }
        }
        val wallets = seed.wallets.map { w ->
            val current = round(balance.getValue(w.id), w.currency)
            Wallet(
                w.id, w.name, WalletType.valueOf(w.type), w.opening, current, w.currency,
                convert(current, w.currency, principal),
                transactions.count { it.walletId == w.id || it.transferToWalletId == w.id },
            )
        }
        val walletCurrency = wallets.associate { it.id to it.currency }
        fun inPrincipal(t: Transaction) = convert(t.walletAmount ?: t.amount, walletCurrency.getValue(t.walletId), principal)

        // Budgets, with the backend's spending rule; a custom budget that
        // ended before this month isn't listed (backend GET /budgets).
        val month = todayIso.substring(0, 7)
        val monthStart = "$month-01"
        val monthEnd = YearMonth.from(today).atEndOfMonth().toString()
        val budgets = seed.budgets.filter { it.kind != "CUSTOM" || at(it.end!!) >= monthStart }.map { b ->
            val custom = b.kind == "CUSTOM"
            val from = if (custom) at(b.start!!) else monthStart
            val to = if (custom) at(b.end!!) else monthEnd
            val spent = round(
                completed.filter { t ->
                    t.type == TransactionType.EXPENSE && t.date in from..to &&
                        if (custom) t.customBudgetId == b.id
                        else (t.category == b.category || t.subcategoryId == b.category) && (b.walletIds.isEmpty() || t.walletId in b.walletIds)
                }.sumOf(::inPrincipal),
                principal,
            )
            val pct = if (b.amount > 0) min(999, (spent / b.amount * 100).roundToInt()) else 0
            val budget = CategoryBudget(
                id = b.id, name = b.name, kind = if (custom) BudgetKind.CUSTOM else BudgetKind.CATEGORY, category = b.category, icon = b.icon,
                walletIds = b.walletIds, period = if (custom) BudgetPeriod.CUSTOM else BudgetPeriod.MONTHLY,
                startDate = if (custom) from else null, endDate = if (custom) to else null, limit = b.amount,
                month = if (custom) from.substring(0, 7) else month, assignedCount = transactions.count { it.customBudgetId == b.id },
            )
            BudgetProgress(budget, spent, b.amount - spent, pct, budgetStatusOf(pct))
        }

        // Goals: the initial amount plus every contribution, per wallet.
        val goals = seed.goals.map { g ->
            val contributions = completed.filter { it.goalId == g.id }.groupBy { it.walletId }.mapValues { (_, list) -> round(list.sumOf(::inPrincipal), principal) }
            val current = g.initial + contributions.values.sum()
            val plan = g.plan?.let { p ->
                val next = at(p.next)
                GoalPlan(
                    amount = p.amount, frequency = RecurrenceInterval.valueOf(p.frequency), walletId = p.wallet, startDate = at(p.start),
                    endMode = GoalPlanEnd.valueOf(p.endMode), count = p.count, endDate = p.endDate?.let(at), autoConfirm = p.autoConfirm,
                    nextDate = next, active = p.active, due = p.active && !p.autoConfirm && next <= todayIso,
                )
            }
            Goal(
                g.id, g.name, g.target, current, g.target - current, if (g.target > 0) min(999, (current / g.target * 100).roundToInt()) else 0,
                g.targetDate?.let(at), g.icon, g.initial, plan, contributions,
            )
        }

        val series = seed.series.map { x ->
            val next = at(x.next)
            RecurringSeries(
                id = x.id, name = x.name, type = TransactionType.valueOf(x.type), amount = x.amount, walletId = x.wallet,
                category = x.category, subcategoryId = x.sub, paymentMethod = paymentMethodFor(walletById.getValue(x.wallet).type),
                interval = RecurrenceInterval.valueOf(x.interval), nextOccurrenceDate = next, isDue = x.active && next <= todayIso,
                active = x.active, currency = x.currency, occurrences = x.occurrences,
                occurrencesDone = transactions.count { it.recurringSeriesId == x.id }, endDate = x.endDate?.let(at), autoConfirm = x.autoConfirm,
            )
        }

        return GuestAccount(
            principal, seed.currencies, categories, wallets, transactions, files, budgets, goals, series,
            alerts(today, wallets, transactions, budgets, goals, series, principal),
        )
    }

    // The backend's alert rules (routes/alerts.ts, mirrored in web guestApi),
    // in its priority order.
    private fun alerts(
        today: LocalDate,
        wallets: List<Wallet>,
        transactions: List<Transaction>,
        budgets: List<BudgetProgress>,
        goals: List<Goal>,
        series: List<RecurringSeries>,
        principal: String,
    ): List<AppAlert> {
        val todayIso = today.toString()
        val weekAgo = today.minusDays(7).toString()
        val weekAhead = today.plusDays(7).toString()
        val walletName = { id: String -> wallets.firstOrNull { it.id == id }?.name ?: "" }
        val repaid = { id: String -> transactions.filter { it.parentLoanId == id }.sumOf { it.amount } }

        val seriesDue = series.filter { it.active && !it.autoConfirm && it.nextOccurrenceDate <= todayIso }
            .sortedBy { it.nextOccurrenceDate }
            .map { AppAlert.SeriesDue("series:${it.id}:${it.nextOccurrenceDate}", it.id, it.name, it.type, it.amount, it.category, it.nextOccurrenceDate, it.nextOccurrenceDate < todayIso) }
        val loans = transactions.filter { it.status == TransactionStatus.COMPLETED && it.loanKind != null && !it.loanSettled && it.dueDate != null && it.amount - repaid(it.id) > 0 }
            .sortedBy { it.dueDate }
            .map { AppAlert.LoanOpen("loan:${it.id}", it.id, it.loanKind!!, it.counterpartyName, it.amount - repaid(it.id), it.dueDate!!, it.dueDate < todayIso) }
        val month = todayIso.substring(0, 7)
        val budgetAlerts = budgets
            .filter { p ->
                val b = p.budget
                val from = b.startDate ?: "$month-01"
                val to = b.endDate ?: YearMonth.from(today).atEndOfMonth().toString()
                b.category != null && from <= YearMonth.from(today).atEndOfMonth().toString() && to >= "$month-01" && p.percentage >= 90
            }
            .sortedByDescending { it.percentage }
            .map { AppAlert.BudgetAtRisk("budget:${it.budget.id}:${it.budget.month}", it.budget.id, it.budget.name, it.budget.category!!, it.spent, it.budget.limit, it.percentage) }
        val near = goals.filter { it.percentage in 90..99 }.sortedByDescending { it.percentage }
            .map { AppAlert.GoalNear("goal:${it.id}", it.id, it.name, it.icon, it.percentage, it.remaining) }
        val planDue = goals.filter { it.plan?.due == true }
            .map { AppAlert.GoalPlanDue("goalplan:${it.id}:${it.plan!!.nextDate}", it.id, it.name, it.icon, it.plan.amount, principal, it.plan.walletId, it.plan.nextDate) }
        val auto = transactions
            .filter { t -> t.status == TransactionStatus.COMPLETED && t.goalId != null && t.date in weekAgo..todayIso && goals.firstOrNull { it.id == t.goalId }?.plan?.autoConfirm == true }
            .sortedByDescending { it.date }
            .map { t ->
                val g = goals.first { it.id == t.goalId }
                AppAlert.GoalPlanAuto("goalauto:${t.id}", g.id, g.name, g.icon, t.amount, t.currency, walletName(t.walletId), t.date)
            }
        val planned = transactions.filter { it.status == TransactionStatus.PLANNED && it.loanKind == null && it.date in todayIso..weekAhead }
            .sortedBy { it.date }
            .map { AppAlert.TxPlanned("planned:${it.id}", it.id, it.description, it.subcategoryId ?: it.category, it.amount, it.currency, walletName(it.walletId), it.date) }
        return seriesDue + loans + budgetAlerts + near + planDue + auto + planned
    }
}
