package com.s2nova.app.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.s2nova.app.data.AppContainer
import com.s2nova.app.data.model.AppLanguage
import com.s2nova.app.data.model.CategoryId
import com.s2nova.app.data.model.PaymentMethod

// Small hand-rolled dictionary, same scope/approach as web's
// src/lib/i18n/translations.ts. Covers every screen except auth (no user/
// language preference exists yet before login) and the barcode scanner
// (explicitly out of scope — see AGENTS.md).
enum class StringKey {
    NAV_HOME, NAV_REPORTS, NAV_BUDGETS, NAV_PLANS, NAV_PROFILE, NAV_ADD,
    TITLE_TRANSACTIONS, TITLE_REPORTS, TITLE_BUDGETS, TITLE_SETTINGS, TITLE_PROFILE,
    SETTINGS_PERSONAL_INFO, SETTINGS_FULL_NAME, SETTINGS_EMAIL,
    SETTINGS_SAVE_CHANGES, SETTINGS_PREFERENCES, SETTINGS_DARK_MODE, SETTINGS_NOTIFICATIONS,
    SETTINGS_BIOMETRIC, SETTINGS_CURRENCY_FORMAT, SETTINGS_LANGUAGE, SETTINGS_ABOUT,
        SETTINGS_CURRENT_PASSWORD,
                SETTINGS_PHONE, SETTINGS_CITY,
    SETTINGS_PRIVACY_SESSION, SETTINGS_BLUR_BALANCE, SETTINGS_BLUR_BALANCE_HELP_ON, SETTINGS_BLUR_BALANCE_HELP_OFF,
    SETTINGS_AUTO_LOCK, SETTINGS_AUTO_LOCK_NEVER,     SETTINGS_AUTO_LOCK_HELP_NEVER,     HOME_BALANCE_TAP_TO_REVEAL,
    HOME_GREETING_MORNING, HOME_GREETING_AFTERNOON, HOME_GREETING_EVENING,
    APP_LOCK_TITLE, APP_LOCK_SUBTITLE, APP_LOCK_ERROR, APP_LOCK_UNLOCK,

    ADD_TXN_TITLE_NEW, ADD_TXN_TITLE_EDIT, ADD_TXN_EXPENSE, ADD_TXN_INCOME,
    ADD_TXN_AMOUNT, ADD_TXN_DESCRIPTION, ADD_TXN_DESCRIPTION_PLACEHOLDER,
    ADD_TXN_CATEGORY, ADD_TXN_PAYMENT_METHOD, ADD_TXN_NOTE, ADD_TXN_NOTE_PLACEHOLDER,
    ADD_TXN_SAVE_NEW, ADD_TXN_SAVE_EDIT, ADD_TXN_ERROR_AMOUNT, ADD_TXN_ERROR_DESCRIPTION,
    ADD_TXN_SUGGESTED_BADGE, ADD_TXN_TITLE_SUGGESTION_NOTE, ADD_TXN_WALLET_METHOD_NOTE,
    ADD_TXN_SELECT_CATEGORY_TITLE, ADD_TXN_CHANGE_CATEGORY_CD,
    ADD_TXN_SUBCATEGORY, ADD_TXN_SUBCATEGORY_NONE, ADD_TXN_CHANGE_CATEGORY,

    ADD_ACTION_MANUAL_TITLE, ADD_ACTION_MANUAL_SUBTITLE,
    ADD_ACTION_SCAN_TITLE, ADD_ACTION_SCAN_SUBTITLE,

    PROFILE_LOGOUT, PROFILE_MEMBER_SINCE,
    PROFILE_WALLETS_DETAIL, PROFILE_RECURRING_DETAIL, PROFILE_RECURRING_DETAIL_EMPTY,
    PROFILE_LOANS_DETAIL_WITH_DEBT, PROFILE_LOANS_DETAIL_NO_DEBT, PROFILE_LOANS_DETAIL_EMPTY,
    PROFILE_SETTINGS_DETAIL,

    CATEGORY_FOOD, CATEGORY_TRANSPORTATION, CATEGORY_SHOPPING, CATEGORY_HEALTH,
    CATEGORY_EDUCATION, CATEGORY_ENTERTAINMENT, CATEGORY_BILLS, CATEGORY_SUBSCRIPTIONS,
    CATEGORY_SALARY, CATEGORY_FREELANCE, CATEGORY_GIFT, CATEGORY_OTHER,

    PAYMENT_CASH, PAYMENT_DEBIT_CARD, PAYMENT_CREDIT_CARD, PAYMENT_BANK_TRANSFER,
    PAYMENT_NEQUI, PAYMENT_DAVIPLATA,

    COMMON_CANCEL, COMMON_SAVE, COMMON_BACK,

    SCANNER_TITLE, SCANNER_CLOSE_CD, SCANNER_PERMISSION_MESSAGE, SCANNER_PERMISSION_BUTTON,
    SCANNER_NOT_FOUND, SCANNER_TRY_AGAIN, SCANNER_HINT, SCANNER_MANUAL_PLACEHOLDER,
    SCANNER_DISCARD, SCANNER_CONFIRM_PURCHASE, SCANNER_NOTIF_TITLE,
    SCANNER_NOTIF_MESSAGE_PREFIX, SCANNER_NOTIF_MESSAGE_MIDDLE,

    HOME_BALANCE, HOME_INCOME, HOME_EXPENSES, HOME_SAVINGS,
    HOME_EXPENSE_SUMMARY, HOME_NO_EXPENSES, HOME_RECENT_TXNS, HOME_SEE_ALL,

    NOTIF_MARK_ALL_READ, NOTIF_EMPTY, NOTIF_UNREAD_SUFFIX, NOTIF_ALL_CAUGHT_UP,

    REPORTS_RANGE_3M, REPORTS_RANGE_6M, REPORTS_RANGE_12M,
    REPORTS_SUBTITLE_3M, REPORTS_SUBTITLE_6M, REPORTS_SUBTITLE_12M,
    REPORTS_SAVINGS_RATE,
    REPORTS_PERIOD_TOTALS, REPORTS_INCOME_VS_EXPENSES, REPORTS_SPEND_BY_CATEGORY,

    TXN_LIST_FILTER_ALL, TXN_LIST_FILTER_PENDING, TXN_LIST_EMPTY_TITLE, TXN_LIST_EMPTY_SUBTITLE,
    TXN_LIST_TODAY, TXN_LIST_YESTERDAY,

    TXN_DETAIL_TITLE, TXN_DETAIL_EDIT_CD, TXN_DETAIL_NOT_FOUND, TXN_DETAIL_DATE,
    TXN_DETAIL_MERCHANT, TXN_DETAIL_NOTE, TXN_DETAIL_DELETE, TXN_DETAIL_DELETE_DIALOG_TITLE,
    TXN_DETAIL_DELETE_CONFIRM_PREFIX, TXN_DETAIL_DELETE_CONFIRM_SUFFIX, TXN_DETAIL_DELETE_CONFIRM,

    BUDGETS_MONTH_LABEL, BUDGETS_UTILIZED, BUDGETS_NEW, BUDGETS_MONTHLY_LIMIT,
    BUDGETS_SPENT_LABEL, BUDGETS_LIMIT_TOTAL, BUDGETS_DAYS_LEFT_NOTE,
    BUDGETS_EDIT_TITLE_PREFIX, BUDGETS_CREATE, BUDGETS_OF, BUDGETS_REMAINING, BUDGETS_OVER_LIMIT,
    BUDGET_STATUS_OVER, BUDGET_STATUS_NEAR, BUDGET_STATUS_ON_TRACK,
    BUDGETS_NAME_OPTIONAL, BUDGETS_NAME_PLACEHOLDER,
    BUDGETS_DELETE, BUDGETS_DELETE_CONFIRM_TITLE, BUDGETS_DELETE_CONFIRM_BODY,
    BUDGETS_EDIT_TITLE, BUDGETS_CATEGORY_AUTO_NOTE, BUDGETS_CATEGORY_NOTE,
    BUDGETS_NAME, BUDGETS_EMPTY, BUDGETS_CATEGORY_TAKEN, COMMON_SAVE_ERROR,

    ADD_TXN_TRANSFER, ADD_TXN_TRANSFER_TO, ADD_TXN_WALLET, ADD_TXN_MORE_OPTIONS,
    ADD_TXN_BUDGET, ADD_TXN_GOAL, ADD_TXN_NONE, ADD_TXN_UPCOMING, ADD_TXN_UPCOMING_HINT,
    ADD_TXN_RECURRING_HINT, ADD_TXN_LENT, ADD_TXN_BORROWED, ADD_TXN_LOAN_HINT,
    ADD_TXN_COUNTERPARTY, ADD_TXN_COUNTERPARTY_PLACEHOLDER, ADD_TXN_DUE_DATE,
    ADD_TXN_ERROR_WALLET, ADD_TXN_ERROR_TRANSFER_WALLET,
    ADD_TXN_NO_WALLET_TITLE, ADD_TXN_NO_WALLET_SUBTITLE, ADD_TXN_NO_WALLET_CTA,
    RECURRENCE_WEEKLY, RECURRENCE_MONTHLY, RECURRENCE_YEARLY,

    WALLETS_TITLE, WALLETS_NEW, WALLETS_NAME, WALLETS_TYPE, WALLETS_INITIAL_BALANCE,
    WALLETS_CREATE, WALLETS_EMPTY_TITLE, WALLETS_EMPTY_SUBTITLE, WALLETS_FOOTER_NOTE,
    WALLET_TYPE_CASH, WALLET_TYPE_BANK_DEBIT, WALLET_TYPE_BANK_CREDIT, WALLET_TYPE_SAVINGS,
    WALLET_TYPE_CRYPTO, WALLET_TYPE_NEQUI, WALLET_TYPE_DAVIPLATA, WALLET_TYPE_OTHER,
    WALLETS_DELETE, WALLETS_DELETE_CONFIRM_TITLE, WALLETS_DELETE_CONFIRM, WALLETS_DELETE_REASSIGN_LABEL, WALLETS_DELETE_ONLY_WALLET,
    WALLETS_EDIT_TITLE, WALLETS_CURRENT_BALANCE, WALLETS_TYPE_AUTO_NOTE, WALLETS_TYPE_NOTE,

    GOALS_TITLE, GOALS_NEW, GOALS_EMPTY, GOALS_NAME, GOALS_NAME_PLACEHOLDER,
    GOALS_CATEGORY_NOTE, GOALS_NOTE_NONE, GOALS_NOTE_DONE, GOALS_NOTE_LEFT, GOAL_PAY_NOTE,
    GOALS_DELETE_NAMED, GOALS_DELETE_HAS_BALANCE, GOALS_DELETE_ORIGIN, GOALS_DELETE_NO_ORIGIN,
    GOALS_DELETE_ALL_TO, GOALS_DELETE_ONE_MOVE, GOALS_DELETE_AND_RETURN,
    GOALS_TARGET_AMOUNT, GOALS_CREATE, GOALS_CONTRIBUTE,
    GOALS_EDIT_TITLE, GOALS_SAVE, GOALS_THEME_LABEL, GOALS_TARGET_DATE_OPTIONAL,
    GOALS_DELETE, GOALS_DELETE_CONFIRM_TITLE, GOALS_DELETE_CONFIRM_BODY,
    GOALS_DELETE_RETURN_FUNDS_TITLE, GOALS_DELETE_RETURN_FUNDS_BODY, GOALS_DELETE_ERROR,

    GOAL_CONTRIBUTION_TITLE, GOAL_CONTRIBUTION_AMOUNT, GOAL_CONTRIBUTION_WALLET,
    GOAL_CONTRIBUTION_SAVE, GOAL_CONTRIBUTION_SAVED, GOAL_CONTRIBUTION_DESCRIPTION_PREFIX,
    GOAL_CONTRIBUTION_ERROR_AMOUNT, GOAL_CONTRIBUTION_ERROR_WALLET,

    COMMON_UNDO, COMMON_SESSION_EXPIRED,

    RECURRING_TITLE, RECURRING_NEW, RECURRING_EMPTY, RECURRING_NAME, RECURRING_NAME_PLACEHOLDER,
    RECURRING_AMOUNT, RECURRING_TYPE, RECURRING_INTERVAL, RECURRING_START_DATE, RECURRING_CREATE,
    RECURRING_DUE_TODAY, RECURRING_NEXT_DUE, RECURRING_CONFIRM, RECURRING_CONFIRMED_TOAST, RECURRING_SKIP,
    RECURRING_OVERDUE, RECURRING_OVERDUE_SINCE, RECURRING_NOTE,
    RECURRING_PAUSE, RECURRING_RESUME, RECURRING_PAUSED, RECURRING_EDIT,
    RECURRING_EDIT_TITLE, RECURRING_DELETE, RECURRING_DELETE_CONFIRM_TITLE, RECURRING_DELETE_CONFIRM_BODY,
    RECURRING_CATEGORY_AUTO_NOTE,

    LOANS_TITLE, LOANS_EMPTY, LOANS_LENT_TAB, LOANS_BORROWED_TAB,
    LOANS_SETTLE, LOANS_SETTLED, LOANS_SETTLED_TOAST, LOANS_DUE, LOANS_NO_DUE_DATE,
    LOANS_SUMMARY_LENT, LOANS_SUMMARY_BORROWED, LOANS_RECORD_ONE, LOANS_RECORD_MANY,
    LOANS_SETTLED_WORD_ONE, LOANS_SETTLED_WORD_MANY, LOANS_NEW_LENT, LOANS_NEW_BORROWED,
    LOANS_OUTSTANDING, LOANS_PAID_PREFIX, LOANS_REGISTER_PAYMENT, LOANS_SETTLE_ALL_SHORTCUT,
    LOANS_PAYMENT_WALLET_LENT, LOANS_PAYMENT_WALLET_BORROWED, LOANS_PAYMENT_TITLE,
    LOANS_FORM_COUNTERPARTY, LOANS_FORM_COUNTERPARTY_PLACEHOLDER, LOANS_FORM_AMOUNT,
    LOANS_FORM_WALLET, LOANS_FORM_DUE_DATE, LOANS_EDIT_TITLE, LOANS_DELETE,
    LOANS_DELETE_CONFIRM_TITLE, LOANS_DELETE_CONFIRM_BODY,
    LOANS_FORM_PERSON_LENT, LOANS_FORM_PERSON_BORROWED, LOANS_FORM_WALLET_LENT, LOANS_FORM_WALLET_BORROWED,
    LOANS_EDIT_ACTION,
    DATE_PICKER_TODAY, DATE_PICKER_NO_DATE, DATE_PICKER_USE_DATE, DATE_PICKER_CHOOSE,
    PLANS_TAB, TITLE_PLANS,
    LOANS_EMPTY_LENT, LOANS_EMPTY_BORROWED, LOANS_DIRECTION, LOANS_DUE_OPTIONAL, LOANS_NO_DATE,
    LOANS_PAY_TITLE_LENT, LOANS_PAY_TITLE_BORROWED, LOANS_PAY_NOTE, LOANS_SETTLED_NOTE, LOANS_PAID_NOTE,
    GOAL_CATEGORY_EMERGENCY, GOAL_CATEGORY_TRAVEL, GOAL_CATEGORY_EDUCATION, GOAL_CATEGORY_HOUSING,
    GOAL_CATEGORY_VEHICLE, GOAL_CATEGORY_TECHNOLOGY, GOAL_CATEGORY_HEALTH, GOAL_CATEGORY_DEBT,
    GOAL_CATEGORY_RETIREMENT, GOAL_CATEGORY_OTHER,

    SETTINGS_REPLAY_TUTORIAL, SETTINGS_TUTORIAL_HINT,
    SETTINGS_LOCK_1_MINUTE, SETTINGS_LOCK_MINUTES, SETTINGS_LOCK_1_HOUR,
    SETTINGS_AUTO_LOCK_HELP_PASSWORD_AFTER, SETTINGS_AUTO_LOCK_HELP_BIOMETRIC_AFTER,
    TUTORIAL_STEP_OF, TUTORIAL_SKIP, TUTORIAL_BACK, TUTORIAL_NEXT, TUTORIAL_DONE,
    TUTORIAL_1_TITLE, TUTORIAL_1_BODY, TUTORIAL_2_TITLE, TUTORIAL_2_BODY,
    TUTORIAL_3_TITLE, TUTORIAL_3_BODY, TUTORIAL_4_TITLE, TUTORIAL_4_BODY,

    ONBOARDING_SKIP, ONBOARDING_BACK, ONBOARDING_NEXT, ONBOARDING_FINISH,
    ONBOARDING_WELCOME_TITLE, ONBOARDING_WELCOME_SUBTITLE, ONBOARDING_GET_STARTED,
    ONBOARDING_WELCOME_POINT_TRACK, ONBOARDING_WELCOME_POINT_SCAN, ONBOARDING_WELCOME_POINT_ANALYZE,
    ONBOARDING_INCOME_TITLE, ONBOARDING_INCOME_SUBTITLE, ONBOARDING_INCOME_LABEL,
    ONBOARDING_WALLET_TITLE, ONBOARDING_WALLET_SUBTITLE, ONBOARDING_WALLET_NAME_PLACEHOLDER,
    ONBOARDING_BUDGET_TITLE, ONBOARDING_BUDGET_SUBTITLE, ONBOARDING_BUDGET_NO_INCOME,
    ONBOARDING_BUDGET_NEEDS, ONBOARDING_BUDGET_WANTS, ONBOARDING_BUDGET_SAVINGS, ONBOARDING_BUDGET_ACCEPT,
    ONBOARDING_TUTORIAL_TRACK_TITLE, ONBOARDING_TUTORIAL_TRACK_BODY,
    ONBOARDING_TUTORIAL_SCAN_TITLE, ONBOARDING_TUTORIAL_SCAN_BODY,
    ONBOARDING_TUTORIAL_ORGANIZE_TITLE, ONBOARDING_TUTORIAL_ORGANIZE_BODY,
    ONBOARDING_TUTORIAL_ANALYZE_TITLE, ONBOARDING_TUTORIAL_ANALYZE_BODY,
    ONBOARDING_TUTORIAL_READY_TITLE, ONBOARDING_TUTORIAL_READY_BODY,
    NAV_TRANSACTIONS,
    HOME_MONTH_INCOME,
    HOME_MONTH_EXPENSES,
    HOME_WALLET_ONE,
    HOME_WALLET_MANY,
    HOME_ADD_FIRST_WALLET,
    HOME_UPCOMING_7_DAYS,
    HOME_UPCOMING_LINK,
    HOME_UPCOMING_EMPTY,
    HOME_UPCOMING_TODAY,
    HOME_UPCOMING_DUE_TODAY,
    HOME_UPCOMING_SCHEDULED,
    HOME_SYNC_ERROR,
    COMMON_RETRY,
    COMMON_DISMISS,
    AMOUNT_HIDDEN,
    ALERT_SERIES_DUE_TITLE,
    ALERT_SERIES_OVERDUE_TITLE,
    ALERT_SERIES_BODY,
    ALERT_LOAN_LENT_TITLE,
    ALERT_LOAN_BORROWED_TITLE,
    ALERT_LOAN_BODY,
    ALERT_BUDGET_TITLE,
    ALERT_BUDGET_BODY,
    ALERT_GOAL_TITLE,
    ALERT_GOAL_BODY,
}

private val ES: Map<StringKey, String> = mapOf(
    StringKey.NAV_HOME to "Inicio",
    StringKey.NAV_REPORTS to "Reportes",
    StringKey.NAV_BUDGETS to "Presupuestos",
    StringKey.NAV_PLANS to "Planes",
    StringKey.NAV_PROFILE to "Perfil",
    StringKey.NAV_ADD to "Agregar",
    StringKey.TITLE_TRANSACTIONS to "Movimientos",
    StringKey.TITLE_REPORTS to "Reportes",
    StringKey.TITLE_BUDGETS to "Presupuestos",
    StringKey.TITLE_SETTINGS to "Ajustes",
    StringKey.TITLE_PROFILE to "Perfil",
    StringKey.SETTINGS_PERSONAL_INFO to "Información personal",
    StringKey.SETTINGS_FULL_NAME to "Nombre completo",
    StringKey.SETTINGS_EMAIL to "Correo",
    StringKey.SETTINGS_SAVE_CHANGES to "Guardar cambios",
    StringKey.SETTINGS_CURRENT_PASSWORD to "Contraseña actual",
    StringKey.SETTINGS_PREFERENCES to "Preferencias",
    StringKey.SETTINGS_DARK_MODE to "Modo oscuro",
    StringKey.SETTINGS_NOTIFICATIONS to "Notificaciones",
    StringKey.SETTINGS_BIOMETRIC to "Ingreso biométrico",
    StringKey.SETTINGS_CURRENCY_FORMAT to "Formato de moneda",
    StringKey.SETTINGS_LANGUAGE to "Idioma",
    StringKey.SETTINGS_ABOUT to "Acerca de",
    StringKey.SETTINGS_PHONE to "Teléfono",
    StringKey.SETTINGS_CITY to "Ciudad",
    StringKey.SETTINGS_PRIVACY_SESSION to "Privacidad y sesión",
    StringKey.SETTINGS_BLUR_BALANCE to "Difuminar el saldo total",
    StringKey.SETTINGS_BLUR_BALANCE_HELP_ON to "En Inicio el saldo aparece oculto; tócalo para mostrarlo.",
    StringKey.SETTINGS_BLUR_BALANCE_HELP_OFF to "El saldo se muestra siempre al abrir Inicio.",
    StringKey.SETTINGS_AUTO_LOCK to "Cierre de sesión automático",
    StringKey.SETTINGS_AUTO_LOCK_NEVER to "Nunca",
    StringKey.SETTINGS_AUTO_LOCK_HELP_NEVER to "La sesión permanece abierta hasta que cierres manualmente.",
    StringKey.HOME_BALANCE_TAP_TO_REVEAL to "Toca para mostrar",
    StringKey.APP_LOCK_TITLE to "Sesión bloqueada",
    StringKey.APP_LOCK_SUBTITLE to "Ingresa tu contraseña para continuar.",
    StringKey.APP_LOCK_ERROR to "Contraseña incorrecta.",
    StringKey.APP_LOCK_UNLOCK to "Desbloquear",

    StringKey.ADD_TXN_TITLE_NEW to "Nuevo movimiento",
    StringKey.ADD_TXN_TITLE_EDIT to "Editar movimiento",
    StringKey.ADD_TXN_EXPENSE to "Gasto",
    StringKey.ADD_TXN_INCOME to "Ingreso",
    StringKey.ADD_TXN_AMOUNT to "Monto",
    StringKey.ADD_TXN_DESCRIPTION to "Título",
    StringKey.ADD_TXN_DESCRIPTION_PLACEHOLDER to "Ej. Mercado semanal",
    StringKey.ADD_TXN_SUGGESTED_BADGE to "SUGERIDO",
    StringKey.ADD_TXN_TITLE_SUGGESTION_NOTE to "Se sugiere a partir de la categoría, la subcategoría y el monto. Puedes editarlo.",
    StringKey.ADD_TXN_WALLET_METHOD_NOTE to "El método de pago lo deriva el servidor a partir de la billetera.",
    StringKey.ADD_TXN_CATEGORY to "Categoría",
    StringKey.ADD_TXN_PAYMENT_METHOD to "Método de pago",
    StringKey.ADD_TXN_NOTE to "Nota (opcional)",
    StringKey.ADD_TXN_NOTE_PLACEHOLDER to "Agrega una nota",
    StringKey.ADD_TXN_SAVE_NEW to "Guardar movimiento",
    StringKey.ADD_TXN_SAVE_EDIT to "Guardar cambios",
    StringKey.ADD_TXN_ERROR_AMOUNT to "Ingresa un monto válido.",
    StringKey.ADD_TXN_ERROR_DESCRIPTION to "Ingresa una descripción.",
    StringKey.ADD_TXN_SELECT_CATEGORY_TITLE to "Selecciona una categoría",
    StringKey.ADD_TXN_SUBCATEGORY to "Subcategoría",
    StringKey.ADD_TXN_SUBCATEGORY_NONE to "Ninguna",
    StringKey.ADD_TXN_CHANGE_CATEGORY to "← Cambiar categoría",
    StringKey.ADD_TXN_CHANGE_CATEGORY_CD to "Cambiar categoría",

    StringKey.ADD_ACTION_MANUAL_TITLE to "Registrar manualmente",
    StringKey.ADD_ACTION_MANUAL_SUBTITLE to "Gasto, ingreso o transferencia",
    StringKey.ADD_ACTION_SCAN_TITLE to "Escanear código",
    StringKey.ADD_ACTION_SCAN_SUBTITLE to "Lee el código de barras de un producto",

    StringKey.PROFILE_LOGOUT to "Cerrar sesión",
    StringKey.PROFILE_MEMBER_SINCE to "desde",
    StringKey.PROFILE_WALLETS_DETAIL to "activas",
    StringKey.PROFILE_RECURRING_DETAIL to "series activas",
    StringKey.PROFILE_RECURRING_DETAIL_EMPTY to "Sin series recurrentes",
    StringKey.PROFILE_LOANS_DETAIL_WITH_DEBT to "Debes",
    StringKey.PROFILE_LOANS_DETAIL_NO_DEBT to "sin deudas",
    StringKey.PROFILE_LOANS_DETAIL_EMPTY to "Sin préstamos registrados",
    StringKey.PROFILE_SETTINGS_DETAIL to "Idioma, moneda, seguridad",

    StringKey.CATEGORY_FOOD to "Alimentación",
    StringKey.CATEGORY_TRANSPORTATION to "Transporte",
    StringKey.CATEGORY_SHOPPING to "Compras",
    StringKey.CATEGORY_HEALTH to "Salud",
    StringKey.CATEGORY_EDUCATION to "Educación",
    StringKey.CATEGORY_ENTERTAINMENT to "Entretenimiento",
    StringKey.CATEGORY_BILLS to "Servicios",
    StringKey.CATEGORY_SUBSCRIPTIONS to "Suscripciones",
    StringKey.CATEGORY_SALARY to "Salario",
    StringKey.CATEGORY_FREELANCE to "Freelance",
    StringKey.CATEGORY_GIFT to "Obsequio",
    StringKey.CATEGORY_OTHER to "Otros",

    StringKey.PAYMENT_CASH to "Efectivo",
    StringKey.PAYMENT_DEBIT_CARD to "Tarjeta débito",
    StringKey.PAYMENT_CREDIT_CARD to "Tarjeta crédito",
    StringKey.PAYMENT_BANK_TRANSFER to "Transferencia",
    StringKey.PAYMENT_NEQUI to "Nequi",
    StringKey.PAYMENT_DAVIPLATA to "Daviplata",

    StringKey.COMMON_CANCEL to "Cancelar",
    StringKey.COMMON_SAVE to "Guardar",
    StringKey.COMMON_BACK to "Atrás",

    StringKey.SCANNER_TITLE to "Escanear código",
    StringKey.SCANNER_CLOSE_CD to "Cerrar",
    StringKey.SCANNER_PERMISSION_MESSAGE to "S2 Nova necesita acceso a la cámara para escanear códigos de barras.",
    StringKey.SCANNER_PERMISSION_BUTTON to "Permitir acceso a la cámara",
    StringKey.SCANNER_NOT_FOUND to "No encontramos ese producto.",
    StringKey.SCANNER_TRY_AGAIN to "Intentar de nuevo",
    StringKey.SCANNER_HINT to "Ubica el código de barras dentro del marco",
    StringKey.SCANNER_MANUAL_PLACEHOLDER to "O ingresa el código manualmente",
    StringKey.SCANNER_DISCARD to "Descartar",
    StringKey.SCANNER_CONFIRM_PURCHASE to "Registrar compra",
    StringKey.SCANNER_NOTIF_TITLE to "Compra registrada",
    StringKey.SCANNER_NOTIF_MESSAGE_PREFIX to "Se registró \"",
    StringKey.SCANNER_NOTIF_MESSAGE_MIDDLE to "\" — ",

    StringKey.HOME_GREETING_MORNING to "Buenos días,",
    StringKey.HOME_GREETING_AFTERNOON to "Buenas tardes,",
    StringKey.HOME_GREETING_EVENING to "Buenas noches,",
    StringKey.HOME_BALANCE to "SALDO TOTAL",
    StringKey.HOME_INCOME to "Ingresos",
    StringKey.HOME_EXPENSES to "Gastos",
    StringKey.HOME_SAVINGS to "Ahorro",
    StringKey.HOME_EXPENSE_SUMMARY to "Resumen de gastos",
    StringKey.HOME_NO_EXPENSES to "Sin gastos este mes.",
    StringKey.HOME_RECENT_TXNS to "Movimientos recientes",
    StringKey.HOME_SEE_ALL to "Ver todos",

    StringKey.NOTIF_MARK_ALL_READ to "Marcar leídas",
    StringKey.NOTIF_EMPTY to "Nada pendiente. Te avisamos cuando un cobro venza o un presupuesto se acerque al límite.",
    StringKey.NOTIF_UNREAD_SUFFIX to "sin leer",
    StringKey.NOTIF_ALL_CAUGHT_UP to "Todo al día",

    StringKey.REPORTS_RANGE_3M to "3M",
    StringKey.REPORTS_RANGE_6M to "6M",
    StringKey.REPORTS_RANGE_12M to "12M",
    StringKey.REPORTS_SUBTITLE_3M to "Últimos 3 meses",
    StringKey.REPORTS_SUBTITLE_6M to "Últimos 6 meses",
    StringKey.REPORTS_SUBTITLE_12M to "Últimos 12 meses",
    StringKey.REPORTS_SAVINGS_RATE to "Tasa de ahorro",
    StringKey.REPORTS_PERIOD_TOTALS to "Totales del periodo",
    StringKey.REPORTS_INCOME_VS_EXPENSES to "Ingresos vs gastos",
    StringKey.REPORTS_SPEND_BY_CATEGORY to "Gasto por categoría",

    StringKey.TXN_LIST_FILTER_ALL to "Todos",
    StringKey.TXN_LIST_FILTER_PENDING to "Pendientes",
    StringKey.TXN_LIST_EMPTY_TITLE to "Sin resultados",
    StringKey.TXN_LIST_EMPTY_SUBTITLE to "Ajusta los filtros.",
    StringKey.TXN_LIST_TODAY to "Hoy",
    StringKey.TXN_LIST_YESTERDAY to "Ayer",

    StringKey.TXN_DETAIL_TITLE to "Detalle del movimiento",
    StringKey.TXN_DETAIL_EDIT_CD to "Editar",
    StringKey.TXN_DETAIL_NOT_FOUND to "Este movimiento ya no existe.",
    StringKey.TXN_DETAIL_DATE to "Fecha",
    StringKey.TXN_DETAIL_MERCHANT to "Comercio",
    StringKey.TXN_DETAIL_NOTE to "Nota",
    StringKey.TXN_DETAIL_DELETE to "Eliminar movimiento",
    StringKey.TXN_DETAIL_DELETE_DIALOG_TITLE to "Eliminar transacción",
    StringKey.TXN_DETAIL_DELETE_CONFIRM_PREFIX to "¿Seguro que deseas eliminar",
    StringKey.TXN_DETAIL_DELETE_CONFIRM_SUFFIX to "? Esta acción no se puede deshacer.",
    StringKey.TXN_DETAIL_DELETE_CONFIRM to "Eliminar",

    StringKey.BUDGETS_MONTH_LABEL to "PRESUPUESTO DEL MES",
    StringKey.BUDGETS_UTILIZED to "utilizado",
    StringKey.BUDGETS_NEW to "Nuevo presupuesto",
    StringKey.BUDGETS_MONTHLY_LIMIT to "Límite mensual",
    StringKey.BUDGETS_SPENT_LABEL to "Gastado en presupuestos",
    StringKey.BUDGETS_LIMIT_TOTAL to "Límite total",
    StringKey.BUDGETS_DAYS_LEFT_NOTE to "Quedan %1\$d días y %2\$s disponibles",
    StringKey.BUDGETS_EDIT_TITLE_PREFIX to "Editar presupuesto de",
    StringKey.BUDGETS_CREATE to "Crear",
    StringKey.BUDGETS_OF to "de",
    StringKey.BUDGETS_REMAINING to "disponibles",
    StringKey.BUDGETS_OVER_LIMIT to "por encima del límite",
    StringKey.BUDGET_STATUS_OVER to "Excedido",
    StringKey.BUDGET_STATUS_NEAR to "Cerca del límite",
    StringKey.BUDGET_STATUS_ON_TRACK to "En curso",
    StringKey.BUDGETS_NAME_OPTIONAL to "Nombre (opcional)",
    StringKey.BUDGETS_NAME_PLACEHOLDER to "Vacaciones, estudio, mercado…",
    StringKey.BUDGETS_NAME to "Nombre",
    StringKey.BUDGETS_EMPTY to "Aún no tienes presupuestos. Crea el primero y se asignará una categoría según el nombre.",
    StringKey.COMMON_SAVE_ERROR to "No se pudo guardar. Inténtalo de nuevo.",
    StringKey.BUDGETS_CATEGORY_TAKEN to "Ya tienes un presupuesto para esa categoría este mes.",
    StringKey.BUDGETS_DELETE to "Eliminar presupuesto",
    StringKey.BUDGETS_DELETE_CONFIRM_TITLE to "Eliminar presupuesto",
    StringKey.BUDGETS_DELETE_CONFIRM_BODY to "Se dejará de rastrear esta categoría. Esta acción no se puede deshacer.",
    StringKey.BUDGETS_EDIT_TITLE to "Editar presupuesto",
    StringKey.BUDGETS_CATEGORY_AUTO_NOTE to "Categoría detectada por el nombre. Puedes cambiarla.",
    StringKey.BUDGETS_CATEGORY_NOTE to "La categoría se detecta por el nombre; al elegir una manualmente se respeta.",

    StringKey.ADD_TXN_TRANSFER to "Transferencia",
    StringKey.ADD_TXN_TRANSFER_TO to "Transferir a",
    StringKey.ADD_TXN_WALLET to "Billetera",
    StringKey.ADD_TXN_MORE_OPTIONS to "Más opciones",
    StringKey.ADD_TXN_BUDGET to "Presupuesto",
    StringKey.ADD_TXN_GOAL to "Meta",
    StringKey.ADD_TXN_NONE to "Ninguno",
    StringKey.ADD_TXN_UPCOMING to "Próximo",
    StringKey.ADD_TXN_UPCOMING_HINT to "Aún no ha ocurrido — no afecta tu saldo todavía.",
    StringKey.ADD_TXN_RECURRING_HINT to "¿Es un pago o ingreso recurrente? Gestiónalo en Programados →",
    StringKey.ADD_TXN_LENT to "Es un préstamo que hice",
    StringKey.ADD_TXN_BORROWED to "Es dinero que me prestaron",
    StringKey.ADD_TXN_LOAN_HINT to "Se marcará como pendiente hasta que lo liquides.",
    StringKey.ADD_TXN_COUNTERPARTY to "Persona",
    StringKey.ADD_TXN_COUNTERPARTY_PLACEHOLDER to "¿A quién / de quién?",
    StringKey.ADD_TXN_DUE_DATE to "Fecha límite (opcional)",
    StringKey.ADD_TXN_ERROR_WALLET to "Selecciona un wallet.",
    StringKey.ADD_TXN_ERROR_TRANSFER_WALLET to "Selecciona el wallet de destino.",
    StringKey.ADD_TXN_NO_WALLET_TITLE to "Aún no tienes wallets",
    StringKey.ADD_TXN_NO_WALLET_SUBTITLE to "Crea un wallet (efectivo, banco, ahorros...) antes de registrar movimientos.",
    StringKey.ADD_TXN_NO_WALLET_CTA to "Crear wallet",
    StringKey.RECURRENCE_WEEKLY to "Semanal",
    StringKey.RECURRENCE_MONTHLY to "Mensual",
    StringKey.RECURRENCE_YEARLY to "Anual",

    StringKey.WALLETS_TITLE to "Billeteras",
    StringKey.WALLETS_NEW to "Nueva billetera",
    StringKey.WALLETS_NAME to "Nombre",
    StringKey.WALLETS_TYPE to "Tipo",
    StringKey.WALLETS_INITIAL_BALANCE to "Saldo inicial",
    StringKey.WALLETS_CREATE to "Crear",
    StringKey.WALLETS_EMPTY_TITLE to "Sin billeteras todavía",
    StringKey.WALLETS_EMPTY_SUBTITLE to "Crea tu primera billetera para empezar a registrar movimientos.",
    StringKey.WALLETS_FOOTER_NOTE to "en total · el saldo de Inicio es la suma de estas billeteras.",
    StringKey.WALLET_TYPE_CASH to "Efectivo",
    StringKey.WALLET_TYPE_BANK_DEBIT to "Cuenta débito",
    StringKey.WALLET_TYPE_BANK_CREDIT to "Tarjeta de crédito",
    StringKey.WALLET_TYPE_SAVINGS to "Ahorros",
    StringKey.WALLET_TYPE_CRYPTO to "Bitcoin/Cripto",
    StringKey.WALLET_TYPE_NEQUI to "Nequi",
    StringKey.WALLET_TYPE_DAVIPLATA to "Daviplata",
    StringKey.WALLET_TYPE_OTHER to "Otro",
    StringKey.WALLETS_DELETE to "Eliminar billetera",
    StringKey.WALLETS_DELETE_CONFIRM_TITLE to "Eliminar billetera",
    StringKey.WALLETS_DELETE_CONFIRM to "Eliminar",
    StringKey.WALLETS_DELETE_REASSIGN_LABEL to "Mover el historial y saldo a",
    StringKey.WALLETS_DELETE_ONLY_WALLET to "Necesitas al menos otra billetera para mover el historial de esta antes de eliminarla.",
    StringKey.WALLETS_EDIT_TITLE to "Editar billetera",
    StringKey.WALLETS_CURRENT_BALANCE to "Saldo actual",
    StringKey.WALLETS_TYPE_AUTO_NOTE to "Tipo detectado por el nombre. Puedes cambiarlo.",
    StringKey.WALLETS_TYPE_NOTE to "El tipo define el ícono y el método de pago que deriva el servidor.",

    StringKey.GOALS_TITLE to "Metas",
    StringKey.GOALS_NEW to "Nueva meta",
    StringKey.GOALS_EMPTY to "Aún no tienes metas. Crea la primera y la categoría se sugiere por el nombre.",
    StringKey.GOALS_NAME to "Nombre",
    StringKey.GOALS_NAME_PLACEHOLDER to "Viaje a Perú, cuota inicial…",
    StringKey.GOALS_CATEGORY_NOTE to "Las categorías de metas describen para qué ahorras.",
    StringKey.GOALS_NOTE_NONE to "Sin abonos aún",
    StringKey.GOALS_NOTE_DONE to "Meta cumplida",
    StringKey.GOALS_NOTE_LEFT to "Faltan %s",
    StringKey.GOAL_PAY_NOTE to "%1\$s de %2\$s · el abono queda registrado en la billetera de origen",
    StringKey.GOALS_DELETE_NAMED to "Eliminar “%s”",
    StringKey.GOALS_DELETE_HAS_BALANCE to "La meta tiene %s ahorrados. Elige a dónde vuelve ese dinero.",
    StringKey.GOALS_DELETE_ORIGIN to "Devolver a su origen",
    StringKey.GOALS_DELETE_NO_ORIGIN to "Sin abonos registrados",
    StringKey.GOALS_DELETE_ALL_TO to "Todo a %s",
    StringKey.GOALS_DELETE_ONE_MOVE to "Un solo movimiento de %s",
    StringKey.GOALS_DELETE_AND_RETURN to "Eliminar y devolver %s",
    StringKey.GOALS_TARGET_AMOUNT to "Monto objetivo",
    StringKey.GOALS_CREATE to "Crear",
    StringKey.GOALS_CONTRIBUTE to "Abonar",
    StringKey.GOALS_EDIT_TITLE to "Editar meta",
    StringKey.GOALS_SAVE to "Guardar",
    StringKey.GOALS_THEME_LABEL to "Ícono",
    StringKey.GOALS_TARGET_DATE_OPTIONAL to "Fecha objetivo (opcional)",
    StringKey.GOALS_DELETE to "Eliminar meta",
    StringKey.GOALS_DELETE_CONFIRM_TITLE to "Eliminar meta",
    StringKey.GOALS_DELETE_CONFIRM_BODY to "Esta acción no se puede deshacer.",
    StringKey.GOALS_DELETE_RETURN_FUNDS_TITLE to "Devolver fondos ahorrados",
    StringKey.GOALS_DELETE_RETURN_FUNDS_BODY to "Elige a qué wallet devolver el monto ahorrado en esta meta antes de eliminarla.",
    StringKey.GOALS_DELETE_ERROR to "No se pudo eliminar la meta. Inténtalo de nuevo.",

    StringKey.GOAL_CONTRIBUTION_TITLE to "Abonar a",
    StringKey.GOAL_CONTRIBUTION_AMOUNT to "Monto del abono",
    StringKey.GOAL_CONTRIBUTION_WALLET to "Desde qué billetera",
    StringKey.GOAL_CONTRIBUTION_SAVE to "Abonar",
    StringKey.GOAL_CONTRIBUTION_SAVED to "Abono agregado",
    StringKey.GOAL_CONTRIBUTION_DESCRIPTION_PREFIX to "Abono a ",
    StringKey.GOAL_CONTRIBUTION_ERROR_AMOUNT to "Ingresa un monto válido.",
    StringKey.GOAL_CONTRIBUTION_ERROR_WALLET to "Elige un wallet de origen.",

    StringKey.COMMON_UNDO to "Deshacer",
    StringKey.COMMON_SESSION_EXPIRED to "Tu sesión expiró, inicia sesión de nuevo.",

    StringKey.RECURRING_TITLE to "Programados",
    StringKey.RECURRING_NEW to "Nueva serie recurrente",
    StringKey.RECURRING_EMPTY to "No tienes series recurrentes. Crea la primera con el + de arriba.",
    StringKey.RECURRING_NAME to "Nombre",
    StringKey.RECURRING_NAME_PLACEHOLDER to "Arriendo, gimnasio, salario…",
    StringKey.RECURRING_AMOUNT to "Monto",
    StringKey.RECURRING_TYPE to "Tipo",
    StringKey.RECURRING_INTERVAL to "Frecuencia",
    StringKey.RECURRING_START_DATE to "Próximo cobro",
    StringKey.RECURRING_CREATE to "Crear",
    StringKey.RECURRING_DUE_TODAY to "Vence hoy",
    StringKey.RECURRING_NEXT_DUE to "Próximo",
    StringKey.RECURRING_CONFIRM to "Confirmar",
    StringKey.RECURRING_SKIP to "Omitir",
    StringKey.RECURRING_OVERDUE to "Vencida",
    StringKey.RECURRING_OVERDUE_SINCE to "Venció",
    StringKey.RECURRING_NOTE to "La serie no mueve saldo hasta que confirmas cada cobro.",
    StringKey.RECURRING_CONFIRMED_TOAST to "Movimiento registrado",
    StringKey.RECURRING_PAUSE to "Pausar",
    StringKey.RECURRING_RESUME to "Reanudar",
    StringKey.RECURRING_EDIT to "Editar",
    StringKey.RECURRING_PAUSED to "Pausada",
    StringKey.RECURRING_EDIT_TITLE to "Editar serie",
    StringKey.RECURRING_DELETE to "Eliminar serie",
    StringKey.RECURRING_DELETE_CONFIRM_TITLE to "Eliminar serie recurrente",
    StringKey.RECURRING_DELETE_CONFIRM_BODY to "Esta acción no se puede deshacer.",
    StringKey.RECURRING_CATEGORY_AUTO_NOTE to "Categoría detectada por el nombre. Puedes cambiarla.",

    StringKey.LOANS_TITLE to "Préstamos",
    StringKey.LOANS_EMPTY_LENT to "No has prestado dinero. Registra el primero con el + de arriba.",
    StringKey.LOANS_EMPTY_BORROWED to "No tienes deudas registradas. Registra una con el + de arriba.",
    StringKey.LOANS_DIRECTION to "Dirección",
    StringKey.LOANS_DUE_OPTIONAL to "Vencimiento (opcional)",
    StringKey.LOANS_NO_DATE to "Sin fecha",
    StringKey.LOANS_PAY_TITLE_LENT to "Cobro de %s",
    StringKey.LOANS_PAY_TITLE_BORROWED to "Pagar a %s",
    StringKey.LOANS_PAY_NOTE to "Pendiente %1\$s de %2\$s",
    StringKey.LOANS_SETTLED_NOTE to "Saldado · %s",
    StringKey.LOANS_PAID_NOTE to " · abonado %1\$s de %2\$s",
    StringKey.LOANS_EMPTY to "No tienes préstamos registrados.",
    StringKey.LOANS_LENT_TAB to "Prestado",
    StringKey.LOANS_BORROWED_TAB to "Recibido",
    StringKey.LOANS_SETTLE to "Marcar como pagado",
    StringKey.LOANS_SETTLED to "Saldado",
    StringKey.LOANS_SETTLED_TOAST to "Préstamo liquidado",
    StringKey.LOANS_DUE to "Vence",
    StringKey.LOANS_NO_DUE_DATE to "Sin fecha de vencimiento",
    StringKey.LOANS_SUMMARY_LENT to "Te deben",
    StringKey.LOANS_SUMMARY_BORROWED to "Debes",
    StringKey.LOANS_RECORD_ONE to "registro",
    StringKey.LOANS_RECORD_MANY to "registros",
    StringKey.LOANS_SETTLED_WORD_ONE to "saldado",
    StringKey.LOANS_SETTLED_WORD_MANY to "saldados",
    StringKey.LOANS_NEW_LENT to "Registrar préstamo",
    StringKey.LOANS_NEW_BORROWED to "Registrar deuda",
    StringKey.LOANS_OUTSTANDING to "Pendiente",
    StringKey.LOANS_PAID_PREFIX to "abonado",
    StringKey.LOANS_REGISTER_PAYMENT to "Registrar abono",
    StringKey.LOANS_SETTLE_ALL_SHORTCUT to "Saldar todo",
    StringKey.LOANS_PAYMENT_WALLET_LENT to "Billetera que recibe el abono",
    StringKey.LOANS_PAYMENT_WALLET_BORROWED to "Billetera de donde sale el pago",
    StringKey.LOANS_PAYMENT_TITLE to "Registrar abono",
    StringKey.LOANS_FORM_COUNTERPARTY to "Contraparte",
    StringKey.LOANS_FORM_COUNTERPARTY_PLACEHOLDER to "Nombre de la contraparte",
    StringKey.LOANS_FORM_AMOUNT to "Monto",
    StringKey.LOANS_FORM_WALLET to "Wallet",
    StringKey.LOANS_FORM_DUE_DATE to "Vencimiento",
    StringKey.LOANS_EDIT_TITLE to "Editar préstamo",
    StringKey.LOANS_DELETE to "Eliminar registro",
    StringKey.LOANS_DELETE_CONFIRM_TITLE to "¿Eliminar este registro?",
    StringKey.LOANS_DELETE_CONFIRM_BODY to "Esta acción no se puede deshacer.",
    StringKey.LOANS_FORM_PERSON_LENT to "¿A quién le prestaste?",
    StringKey.LOANS_FORM_PERSON_BORROWED to "¿A quién le debes?",
    StringKey.LOANS_FORM_WALLET_LENT to "Billetera de donde salió",
    StringKey.LOANS_FORM_WALLET_BORROWED to "Billetera que recibió el dinero",
    StringKey.LOANS_EDIT_ACTION to "Editar",
    StringKey.DATE_PICKER_TODAY to "Hoy",
    StringKey.DATE_PICKER_NO_DATE to "Sin fecha",
    StringKey.DATE_PICKER_USE_DATE to "Usar esta fecha",
    StringKey.DATE_PICKER_CHOOSE to "Elegir fecha",
    StringKey.PLANS_TAB to "Préstamos",
    StringKey.TITLE_PLANS to "Planes",
    StringKey.GOAL_CATEGORY_EMERGENCY to "Emergencia",
    StringKey.GOAL_CATEGORY_TRAVEL to "Viaje",
    StringKey.GOAL_CATEGORY_EDUCATION to "Educación",
    StringKey.GOAL_CATEGORY_HOUSING to "Vivienda",
    StringKey.GOAL_CATEGORY_VEHICLE to "Vehículo",
    StringKey.GOAL_CATEGORY_TECHNOLOGY to "Tecnología",
    StringKey.GOAL_CATEGORY_HEALTH to "Salud",
    StringKey.GOAL_CATEGORY_DEBT to "Deuda",
    StringKey.GOAL_CATEGORY_RETIREMENT to "Retiro",
    StringKey.GOAL_CATEGORY_OTHER to "Otros",

    StringKey.SETTINGS_REPLAY_TUTORIAL to "Repetir el tutorial",
    StringKey.SETTINGS_TUTORIAL_HINT to "%s pasos · menos de un minuto",
    StringKey.SETTINGS_LOCK_1_MINUTE to "1 minuto",
    StringKey.SETTINGS_LOCK_MINUTES to "%s minutos",
    StringKey.SETTINGS_LOCK_1_HOUR to "1 hora",
    StringKey.SETTINGS_AUTO_LOCK_HELP_PASSWORD_AFTER to "Tras %s sin actividad pedimos tu contraseña de nuevo.",
    StringKey.SETTINGS_AUTO_LOCK_HELP_BIOMETRIC_AFTER to "Tras %s sin actividad pedimos tu huella de nuevo.",
    StringKey.TUTORIAL_STEP_OF to "PASO %s DE %s",
    StringKey.TUTORIAL_SKIP to "Saltar",
    StringKey.TUTORIAL_BACK to "Atrás",
    StringKey.TUTORIAL_NEXT to "Siguiente",
    StringKey.TUTORIAL_DONE to "Entendido",
    StringKey.TUTORIAL_1_TITLE to "Todo tu dinero en un solo saldo",
    StringKey.TUTORIAL_1_BODY to "El saldo de Inicio es la suma de tus billeteras. Agrégalas o edítalas desde Perfil › Billeteras y el total se recalcula solo.",
    StringKey.TUTORIAL_2_TITLE to "Registra con el botón +",
    StringKey.TUTORIAL_2_BODY to "El + del centro abre gasto, ingreso o transferencia. La categoría se sugiere por el nombre y puedes marcar el movimiento como próximo si aún no afecta el saldo.",
    StringKey.TUTORIAL_3_TITLE to "Presupuestos y metas viven en Planes",
    StringKey.TUTORIAL_3_BODY to "Un presupuesto pone un límite mensual por categoría. Una meta acumula abonos desde la billetera que elijas y recuerda de dónde vino cada peso.",
    StringKey.TUTORIAL_4_TITLE to "Lo que se repite, automatízalo",
    StringKey.TUTORIAL_4_BODY to "Programados guarda tus cobros fijos con su frecuencia. No mueven saldo hasta que confirmas cada uno, así que nada se descuenta por error.",

    StringKey.ONBOARDING_SKIP to "Omitir",
    StringKey.ONBOARDING_BACK to "Atrás",
    StringKey.ONBOARDING_NEXT to "Siguiente",
    StringKey.ONBOARDING_FINISH to "Empezar",
    StringKey.ONBOARDING_WELCOME_TITLE to "Bienvenido a S2 Nova",
    StringKey.ONBOARDING_WELCOME_SUBTITLE to "Tu dinero, bajo control, en un par de toques.",
    StringKey.ONBOARDING_GET_STARTED to "Comenzar",
    StringKey.ONBOARDING_WELCOME_POINT_TRACK to "Registra ingresos y gastos al instante",
    StringKey.ONBOARDING_WELCOME_POINT_SCAN to "Escanea productos para registrar compras",
    StringKey.ONBOARDING_WELCOME_POINT_ANALYZE to "Entiende tus hábitos desde el dashboard web",
    StringKey.ONBOARDING_INCOME_TITLE to "¿Cuánto ingresas al mes?",
    StringKey.ONBOARDING_INCOME_SUBTITLE to "Opcional — nos ayuda a sugerirte un presupuesto. Puedes omitir este paso.",
    StringKey.ONBOARDING_INCOME_LABEL to "Ingreso mensual aproximado",
    StringKey.ONBOARDING_WALLET_TITLE to "Crea tu primer wallet",
    StringKey.ONBOARDING_WALLET_SUBTITLE to "Aquí es donde entra el dinero que registres. Puedes agregar más después.",
    StringKey.ONBOARDING_WALLET_NAME_PLACEHOLDER to "Ej. Efectivo, Bancolombia...",
    StringKey.ONBOARDING_BUDGET_TITLE to "Una sugerencia de presupuesto",
    StringKey.ONBOARDING_BUDGET_SUBTITLE to "Basado en la regla 50/30/20 — solo una sugerencia, tú decides.",
    StringKey.ONBOARDING_BUDGET_NO_INCOME to "Sin un ingreso registrado no podemos calcular una sugerencia — puedes crear presupuestos manualmente después.",
    StringKey.ONBOARDING_BUDGET_NEEDS to "Necesidades",
    StringKey.ONBOARDING_BUDGET_WANTS to "Gustos",
    StringKey.ONBOARDING_BUDGET_SAVINGS to "Ahorro",
    StringKey.ONBOARDING_BUDGET_ACCEPT to "Aceptar sugerencia",
    StringKey.ONBOARDING_TUTORIAL_TRACK_TITLE to "Controla tu dinero",
    StringKey.ONBOARDING_TUTORIAL_TRACK_BODY to "Registra ingresos, gastos y transferencias entre tus wallets en segundos.",
    StringKey.ONBOARDING_TUTORIAL_SCAN_TITLE to "Escanea tus compras",
    StringKey.ONBOARDING_TUTORIAL_SCAN_BODY to "Usa la cámara para escanear un producto y registrar la compra al instante.",
    StringKey.ONBOARDING_TUTORIAL_ORGANIZE_TITLE to "Organiza tus finanzas",
    StringKey.ONBOARDING_TUTORIAL_ORGANIZE_BODY to "Crea wallets, presupuestos y objetivos para mantener todo en orden.",
    StringKey.ONBOARDING_TUTORIAL_ANALYZE_TITLE to "Entiende tus finanzas",
    StringKey.ONBOARDING_TUTORIAL_ANALYZE_BODY to "El dashboard web te muestra gráficas, tendencias y reportes detallados.",
    StringKey.ONBOARDING_TUTORIAL_READY_TITLE to "¡Listo!",
    StringKey.ONBOARDING_TUTORIAL_READY_BODY to "Ya puedes empezar a usar S2 Nova.",
    StringKey.NAV_TRANSACTIONS to "Movimientos",
    StringKey.HOME_MONTH_INCOME to "Ingresos del mes",
    StringKey.HOME_MONTH_EXPENSES to "Gastos del mes",
    StringKey.HOME_WALLET_ONE to "billetera",
    StringKey.HOME_WALLET_MANY to "billeteras",
    StringKey.HOME_ADD_FIRST_WALLET to "Agrega tu primera billetera",
    StringKey.HOME_UPCOMING_7_DAYS to "Próximos 7 días",
    StringKey.HOME_UPCOMING_LINK to "Programados",
    StringKey.HOME_UPCOMING_EMPTY to "Nada programado para esta semana.",
    StringKey.HOME_UPCOMING_TODAY to "HOY",
    StringKey.HOME_UPCOMING_DUE_TODAY to "Vence hoy · confírmalo para que afecte el saldo",
    StringKey.HOME_UPCOMING_SCHEDULED to "Programado · %1\$s",
    StringKey.HOME_SYNC_ERROR to "No pudimos actualizar tus datos.",
    StringKey.COMMON_RETRY to "Reintentar",
    StringKey.COMMON_DISMISS to "Descartar",
    StringKey.AMOUNT_HIDDEN to "Monto oculto",
    StringKey.ALERT_SERIES_DUE_TITLE to "%1\$s vence hoy",
    StringKey.ALERT_SERIES_OVERDUE_TITLE to "%1\$s venció el %2\$s",
    StringKey.ALERT_SERIES_BODY to "%1\$s · confírmalo para que afecte el saldo",
    StringKey.ALERT_LOAN_LENT_TITLE to "%1\$s te debe",
    StringKey.ALERT_LOAN_BORROWED_TITLE to "Le debes a %1\$s",
    StringKey.ALERT_LOAN_BODY to "%1\$s · vence %2\$s",
    StringKey.ALERT_BUDGET_TITLE to "%1\$s al %2\$d%% del límite",
    StringKey.ALERT_BUDGET_BODY to "%1\$s de %2\$s este mes",
    StringKey.ALERT_GOAL_TITLE to "%1\$s está al %2\$d%%",
    StringKey.ALERT_GOAL_BODY to "Faltan %1\$s para cumplirla",
)

private val EN: Map<StringKey, String> = mapOf(
    StringKey.NAV_HOME to "Home",
    StringKey.NAV_REPORTS to "Reports",
    StringKey.NAV_BUDGETS to "Budgets",
    StringKey.NAV_PLANS to "Plans",
    StringKey.NAV_PROFILE to "Profile",
    StringKey.NAV_ADD to "Add",
    StringKey.TITLE_TRANSACTIONS to "Transactions",
    StringKey.TITLE_REPORTS to "Reports",
    StringKey.TITLE_BUDGETS to "Budgets",
    StringKey.TITLE_SETTINGS to "Settings",
    StringKey.TITLE_PROFILE to "Profile",
    StringKey.SETTINGS_PERSONAL_INFO to "Personal information",
    StringKey.SETTINGS_FULL_NAME to "Full name",
    StringKey.SETTINGS_EMAIL to "Email",
    StringKey.SETTINGS_SAVE_CHANGES to "Save changes",
    StringKey.SETTINGS_CURRENT_PASSWORD to "Current password",
    StringKey.SETTINGS_PREFERENCES to "Preferences",
    StringKey.SETTINGS_DARK_MODE to "Dark mode",
    StringKey.SETTINGS_NOTIFICATIONS to "Notifications",
    StringKey.SETTINGS_BIOMETRIC to "Biometric sign-in",
    StringKey.SETTINGS_CURRENCY_FORMAT to "Currency format",
    StringKey.SETTINGS_LANGUAGE to "Language",
    StringKey.SETTINGS_ABOUT to "About",
    StringKey.SETTINGS_PHONE to "Phone",
    StringKey.SETTINGS_CITY to "City",
    StringKey.SETTINGS_PRIVACY_SESSION to "Privacy and session",
    StringKey.SETTINGS_BLUR_BALANCE to "Blur total balance",
    StringKey.SETTINGS_BLUR_BALANCE_HELP_ON to "Home hides the balance by default; tap it to reveal.",
    StringKey.SETTINGS_BLUR_BALANCE_HELP_OFF to "The balance always shows when you open Home.",
    StringKey.SETTINGS_AUTO_LOCK to "Automatic session lock",
    StringKey.SETTINGS_AUTO_LOCK_NEVER to "Never",
    StringKey.SETTINGS_AUTO_LOCK_HELP_NEVER to "The session stays open until you sign out manually.",
    StringKey.HOME_BALANCE_TAP_TO_REVEAL to "Tap to reveal",
    StringKey.APP_LOCK_TITLE to "Session locked",
    StringKey.APP_LOCK_SUBTITLE to "Enter your password to continue.",
    StringKey.APP_LOCK_ERROR to "Incorrect password.",
    StringKey.APP_LOCK_UNLOCK to "Unlock",

    StringKey.ADD_TXN_TITLE_NEW to "New transaction",
    StringKey.ADD_TXN_TITLE_EDIT to "Edit transaction",
    StringKey.ADD_TXN_EXPENSE to "Expense",
    StringKey.ADD_TXN_INCOME to "Income",
    StringKey.ADD_TXN_AMOUNT to "Amount",
    StringKey.ADD_TXN_DESCRIPTION to "Title",
    StringKey.ADD_TXN_DESCRIPTION_PLACEHOLDER to "E.g. Weekly groceries",
    StringKey.ADD_TXN_SUGGESTED_BADGE to "SUGGESTED",
    StringKey.ADD_TXN_TITLE_SUGGESTION_NOTE to "Suggested from the category, subcategory, and amount. You can edit it.",
    StringKey.ADD_TXN_WALLET_METHOD_NOTE to "The payment method is derived by the server from the wallet.",
    StringKey.ADD_TXN_CATEGORY to "Category",
    StringKey.ADD_TXN_PAYMENT_METHOD to "Payment method",
    StringKey.ADD_TXN_NOTE to "Note (optional)",
    StringKey.ADD_TXN_NOTE_PLACEHOLDER to "Add a note",
    StringKey.ADD_TXN_SAVE_NEW to "Save transaction",
    StringKey.ADD_TXN_SAVE_EDIT to "Save changes",
    StringKey.ADD_TXN_ERROR_AMOUNT to "Enter a valid amount.",
    StringKey.ADD_TXN_ERROR_DESCRIPTION to "Enter a description.",
    StringKey.ADD_TXN_SELECT_CATEGORY_TITLE to "Choose a category",
    StringKey.ADD_TXN_SUBCATEGORY to "Subcategory",
    StringKey.ADD_TXN_SUBCATEGORY_NONE to "None",
    StringKey.ADD_TXN_CHANGE_CATEGORY to "← Change category",
    StringKey.ADD_TXN_CHANGE_CATEGORY_CD to "Change category",

    StringKey.ADD_ACTION_MANUAL_TITLE to "Record manually",
    StringKey.ADD_ACTION_MANUAL_SUBTITLE to "Expense, income or transfer",
    StringKey.ADD_ACTION_SCAN_TITLE to "Scan code",
    StringKey.ADD_ACTION_SCAN_SUBTITLE to "Read a product's barcode",

    StringKey.PROFILE_LOGOUT to "Log out",
    StringKey.PROFILE_MEMBER_SINCE to "since",
    StringKey.PROFILE_WALLETS_DETAIL to "active",
    StringKey.PROFILE_RECURRING_DETAIL to "active series",
    StringKey.PROFILE_RECURRING_DETAIL_EMPTY to "No recurring series",
    StringKey.PROFILE_LOANS_DETAIL_WITH_DEBT to "You owe",
    StringKey.PROFILE_LOANS_DETAIL_NO_DEBT to "no debt",
    StringKey.PROFILE_LOANS_DETAIL_EMPTY to "No loans on record",
    StringKey.PROFILE_SETTINGS_DETAIL to "Language, currency, security",

    StringKey.CATEGORY_FOOD to "Food",
    StringKey.CATEGORY_TRANSPORTATION to "Transportation",
    StringKey.CATEGORY_SHOPPING to "Shopping",
    StringKey.CATEGORY_HEALTH to "Health",
    StringKey.CATEGORY_EDUCATION to "Education",
    StringKey.CATEGORY_ENTERTAINMENT to "Entertainment",
    StringKey.CATEGORY_BILLS to "Bills",
    StringKey.CATEGORY_SUBSCRIPTIONS to "Subscriptions",
    StringKey.CATEGORY_SALARY to "Salary",
    StringKey.CATEGORY_FREELANCE to "Freelance",
    StringKey.CATEGORY_GIFT to "Gift",
    StringKey.CATEGORY_OTHER to "Other",

    StringKey.PAYMENT_CASH to "Cash",
    StringKey.PAYMENT_DEBIT_CARD to "Debit card",
    StringKey.PAYMENT_CREDIT_CARD to "Credit card",
    StringKey.PAYMENT_BANK_TRANSFER to "Bank transfer",
    StringKey.PAYMENT_NEQUI to "Nequi",
    StringKey.PAYMENT_DAVIPLATA to "Daviplata",

    StringKey.COMMON_CANCEL to "Cancel",
    StringKey.COMMON_SAVE to "Save",
    StringKey.COMMON_BACK to "Back",

    StringKey.SCANNER_TITLE to "Scan barcode",
    StringKey.SCANNER_CLOSE_CD to "Close",
    StringKey.SCANNER_PERMISSION_MESSAGE to "S2 Nova needs camera access to scan barcodes.",
    StringKey.SCANNER_PERMISSION_BUTTON to "Allow camera access",
    StringKey.SCANNER_NOT_FOUND to "We couldn't find that product.",
    StringKey.SCANNER_TRY_AGAIN to "Try again",
    StringKey.SCANNER_HINT to "Position the barcode inside the frame",
    StringKey.SCANNER_MANUAL_PLACEHOLDER to "Or enter the code manually",
    StringKey.SCANNER_DISCARD to "Discard",
    StringKey.SCANNER_CONFIRM_PURCHASE to "Record purchase",
    StringKey.SCANNER_NOTIF_TITLE to "Purchase recorded",
    StringKey.SCANNER_NOTIF_MESSAGE_PREFIX to "Registered \"",
    StringKey.SCANNER_NOTIF_MESSAGE_MIDDLE to "\" — ",

    StringKey.HOME_GREETING_MORNING to "Good morning,",
    StringKey.HOME_GREETING_AFTERNOON to "Good afternoon,",
    StringKey.HOME_GREETING_EVENING to "Good evening,",
    StringKey.HOME_BALANCE to "TOTAL BALANCE",
    StringKey.HOME_INCOME to "Income",
    StringKey.HOME_EXPENSES to "Expenses",
    StringKey.HOME_SAVINGS to "Savings",
    StringKey.HOME_EXPENSE_SUMMARY to "Expense summary",
    StringKey.HOME_NO_EXPENSES to "No expenses this month.",
    StringKey.HOME_RECENT_TXNS to "Recent transactions",
    StringKey.HOME_SEE_ALL to "See all",

    StringKey.NOTIF_MARK_ALL_READ to "Mark all as read",
    StringKey.NOTIF_EMPTY to "Nothing pending. We'll let you know when a charge is due or a budget nears its limit.",
    StringKey.NOTIF_UNREAD_SUFFIX to "unread",
    StringKey.NOTIF_ALL_CAUGHT_UP to "All caught up",

    StringKey.REPORTS_RANGE_3M to "3M",
    StringKey.REPORTS_RANGE_6M to "6M",
    StringKey.REPORTS_RANGE_12M to "12M",
    StringKey.REPORTS_SUBTITLE_3M to "Last 3 months",
    StringKey.REPORTS_SUBTITLE_6M to "Last 6 months",
    StringKey.REPORTS_SUBTITLE_12M to "Last 12 months",
    StringKey.REPORTS_SAVINGS_RATE to "Savings rate",
    StringKey.REPORTS_PERIOD_TOTALS to "Period totals",
    StringKey.REPORTS_INCOME_VS_EXPENSES to "Income vs expenses",
    StringKey.REPORTS_SPEND_BY_CATEGORY to "Spend by category",

    StringKey.TXN_LIST_FILTER_ALL to "All",
    StringKey.TXN_LIST_FILTER_PENDING to "Pending",
    StringKey.TXN_LIST_EMPTY_TITLE to "No results",
    StringKey.TXN_LIST_EMPTY_SUBTITLE to "Adjust your filters.",
    StringKey.TXN_LIST_TODAY to "Today",
    StringKey.TXN_LIST_YESTERDAY to "Yesterday",

    StringKey.TXN_DETAIL_TITLE to "Transaction detail",
    StringKey.TXN_DETAIL_EDIT_CD to "Edit",
    StringKey.TXN_DETAIL_NOT_FOUND to "This transaction no longer exists.",
    StringKey.TXN_DETAIL_DATE to "Date",
    StringKey.TXN_DETAIL_MERCHANT to "Merchant",
    StringKey.TXN_DETAIL_NOTE to "Note",
    StringKey.TXN_DETAIL_DELETE to "Delete transaction",
    StringKey.TXN_DETAIL_DELETE_DIALOG_TITLE to "Delete transaction",
    StringKey.TXN_DETAIL_DELETE_CONFIRM_PREFIX to "Are you sure you want to delete",
    StringKey.TXN_DETAIL_DELETE_CONFIRM_SUFFIX to "? This action cannot be undone.",
    StringKey.TXN_DETAIL_DELETE_CONFIRM to "Delete",

    StringKey.BUDGETS_MONTH_LABEL to "THIS MONTH'S BUDGET",
    StringKey.BUDGETS_UTILIZED to "used",
    StringKey.BUDGETS_NEW to "New budget",
    StringKey.BUDGETS_MONTHLY_LIMIT to "Monthly limit",
    StringKey.BUDGETS_SPENT_LABEL to "Spent on budgets",
    StringKey.BUDGETS_LIMIT_TOTAL to "Total limit",
    StringKey.BUDGETS_DAYS_LEFT_NOTE to "%1\$d days left and %2\$s available",
    StringKey.BUDGETS_EDIT_TITLE_PREFIX to "Edit budget for",
    StringKey.BUDGETS_CREATE to "Create",
    StringKey.BUDGETS_OF to "of",
    StringKey.BUDGETS_REMAINING to "remaining",
    StringKey.BUDGETS_OVER_LIMIT to "over the limit",
    StringKey.BUDGET_STATUS_OVER to "Over budget",
    StringKey.BUDGET_STATUS_NEAR to "Near limit",
    StringKey.BUDGET_STATUS_ON_TRACK to "On track",
    StringKey.BUDGETS_NAME_OPTIONAL to "Name (optional)",
    StringKey.BUDGETS_NAME_PLACEHOLDER to "Vacation, studies, groceries…",
    StringKey.BUDGETS_NAME to "Name",
    StringKey.BUDGETS_EMPTY to "You have no budgets yet. Create the first one and a category is assigned from its name.",
    StringKey.COMMON_SAVE_ERROR to "Couldn't save. Please try again.",
    StringKey.BUDGETS_CATEGORY_TAKEN to "You already have a budget for that category this month.",
    StringKey.BUDGETS_DELETE to "Delete budget",
    StringKey.BUDGETS_DELETE_CONFIRM_TITLE to "Delete budget",
    StringKey.BUDGETS_DELETE_CONFIRM_BODY to "This category will stop being tracked. This action can't be undone.",
    StringKey.BUDGETS_EDIT_TITLE to "Edit budget",
    StringKey.BUDGETS_CATEGORY_AUTO_NOTE to "Category detected from the name. You can change it.",
    StringKey.BUDGETS_CATEGORY_NOTE to "The category is detected from the name; picking one manually locks it in.",

    StringKey.ADD_TXN_TRANSFER to "Transfer",
    StringKey.ADD_TXN_TRANSFER_TO to "Transfer to",
    StringKey.ADD_TXN_WALLET to "Wallet",
    StringKey.ADD_TXN_MORE_OPTIONS to "More options",
    StringKey.ADD_TXN_BUDGET to "Budget",
    StringKey.ADD_TXN_GOAL to "Goal",
    StringKey.ADD_TXN_NONE to "None",
    StringKey.ADD_TXN_UPCOMING to "Upcoming",
    StringKey.ADD_TXN_UPCOMING_HINT to "Hasn't happened yet — won't affect your balance yet.",
    StringKey.ADD_TXN_RECURRING_HINT to "Is this a recurring payment or income? Manage it under Scheduled →",
    StringKey.ADD_TXN_LENT to "This is money I lent",
    StringKey.ADD_TXN_BORROWED to "This is money I borrowed",
    StringKey.ADD_TXN_LOAN_HINT to "Tracked as outstanding until you settle it.",
    StringKey.ADD_TXN_COUNTERPARTY to "Person",
    StringKey.ADD_TXN_COUNTERPARTY_PLACEHOLDER to "Who to / from?",
    StringKey.ADD_TXN_DUE_DATE to "Due date (optional)",
    StringKey.ADD_TXN_ERROR_WALLET to "Select a wallet.",
    StringKey.ADD_TXN_ERROR_TRANSFER_WALLET to "Select the destination wallet.",
    StringKey.ADD_TXN_NO_WALLET_TITLE to "No wallets yet",
    StringKey.ADD_TXN_NO_WALLET_SUBTITLE to "Create a wallet (cash, bank, savings...) before recording transactions.",
    StringKey.ADD_TXN_NO_WALLET_CTA to "Create wallet",
    StringKey.RECURRENCE_WEEKLY to "Weekly",
    StringKey.RECURRENCE_MONTHLY to "Monthly",
    StringKey.RECURRENCE_YEARLY to "Yearly",

    StringKey.WALLETS_TITLE to "Wallets",
    StringKey.WALLETS_NEW to "New wallet",
    StringKey.WALLETS_NAME to "Name",
    StringKey.WALLETS_TYPE to "Type",
    StringKey.WALLETS_INITIAL_BALANCE to "Initial balance",
    StringKey.WALLETS_CREATE to "Create",
    StringKey.WALLETS_EMPTY_TITLE to "No wallets yet",
    StringKey.WALLETS_EMPTY_SUBTITLE to "Create your first wallet to start recording transactions.",
    StringKey.WALLETS_FOOTER_NOTE to "in total · Home's balance is the sum of these wallets.",
    StringKey.WALLET_TYPE_CASH to "Cash",
    StringKey.WALLET_TYPE_BANK_DEBIT to "Debit account",
    StringKey.WALLET_TYPE_BANK_CREDIT to "Credit card",
    StringKey.WALLET_TYPE_SAVINGS to "Savings",
    StringKey.WALLET_TYPE_CRYPTO to "Bitcoin/Crypto",
    StringKey.WALLET_TYPE_NEQUI to "Nequi",
    StringKey.WALLET_TYPE_DAVIPLATA to "Daviplata",
    StringKey.WALLET_TYPE_OTHER to "Other",
    StringKey.WALLETS_DELETE to "Delete wallet",
    StringKey.WALLETS_DELETE_CONFIRM_TITLE to "Delete wallet",
    StringKey.WALLETS_DELETE_CONFIRM to "Delete",
    StringKey.WALLETS_DELETE_REASSIGN_LABEL to "Move history and balance to",
    StringKey.WALLETS_DELETE_ONLY_WALLET to "You need at least one other wallet to move this wallet's history to before deleting it.",
    StringKey.WALLETS_EDIT_TITLE to "Edit wallet",
    StringKey.WALLETS_CURRENT_BALANCE to "Current balance",
    StringKey.WALLETS_TYPE_AUTO_NOTE to "Type detected from the name. You can change it.",
    StringKey.WALLETS_TYPE_NOTE to "The type sets the icon and the payment method the server derives.",

    StringKey.GOALS_TITLE to "Goals",
    StringKey.GOALS_NEW to "New goal",
    StringKey.GOALS_EMPTY to "No goals yet. Create one like \"Car Payment\".",
    StringKey.GOALS_NAME to "Name",
    StringKey.GOALS_NAME_PLACEHOLDER to "Trip to Peru, down payment…",
    StringKey.GOALS_CATEGORY_NOTE to "Goal categories describe what you're saving for.",
    StringKey.GOALS_NOTE_NONE to "No contributions yet",
    StringKey.GOALS_NOTE_DONE to "Goal reached",
    StringKey.GOALS_NOTE_LEFT to "%s to go",
    StringKey.GOAL_PAY_NOTE to "%1\$s of %2\$s · the contribution is recorded in the source wallet",
    StringKey.GOALS_DELETE_NAMED to "Delete “%s”",
    StringKey.GOALS_DELETE_HAS_BALANCE to "This goal holds %s. Choose where that money goes back to.",
    StringKey.GOALS_DELETE_ORIGIN to "Return to where it came from",
    StringKey.GOALS_DELETE_NO_ORIGIN to "No contributions recorded",
    StringKey.GOALS_DELETE_ALL_TO to "All to %s",
    StringKey.GOALS_DELETE_ONE_MOVE to "A single movement of %s",
    StringKey.GOALS_DELETE_AND_RETURN to "Delete and return %s",
    StringKey.GOALS_TARGET_AMOUNT to "Target amount",
    StringKey.GOALS_CREATE to "Create",
    StringKey.GOALS_CONTRIBUTE to "Contribute",
    StringKey.GOALS_EDIT_TITLE to "Edit goal",
    StringKey.GOALS_SAVE to "Save",
    StringKey.GOALS_THEME_LABEL to "Icon",
    StringKey.GOALS_TARGET_DATE_OPTIONAL to "Target date (optional)",
    StringKey.GOALS_DELETE to "Delete goal",
    StringKey.GOALS_DELETE_CONFIRM_TITLE to "Delete goal",
    StringKey.GOALS_DELETE_CONFIRM_BODY to "This action can't be undone.",
    StringKey.GOALS_DELETE_RETURN_FUNDS_TITLE to "Return saved funds",
    StringKey.GOALS_DELETE_RETURN_FUNDS_BODY to "Choose which wallet should receive this goal's saved amount before deleting it.",
    StringKey.GOALS_DELETE_ERROR to "Couldn't delete the goal. Please try again.",

    StringKey.GOAL_CONTRIBUTION_TITLE to "Contribute to",
    StringKey.GOAL_CONTRIBUTION_AMOUNT to "Amount to add",
    StringKey.GOAL_CONTRIBUTION_WALLET to "From which wallet",
    StringKey.GOAL_CONTRIBUTION_SAVE to "Contribute",
    StringKey.GOAL_CONTRIBUTION_SAVED to "Contribution added",
    StringKey.GOAL_CONTRIBUTION_DESCRIPTION_PREFIX to "Contribution to ",
    StringKey.GOAL_CONTRIBUTION_ERROR_AMOUNT to "Enter a valid amount.",
    StringKey.GOAL_CONTRIBUTION_ERROR_WALLET to "Choose a source wallet.",

    StringKey.COMMON_UNDO to "Undo",
    StringKey.COMMON_SESSION_EXPIRED to "Your session expired, please sign in again.",

    StringKey.RECURRING_TITLE to "Scheduled",
    StringKey.RECURRING_NEW to "New recurring series",
    StringKey.RECURRING_EMPTY to "No recurring series yet. Create the first one with the + above.",
    StringKey.RECURRING_NAME to "Name",
    StringKey.RECURRING_NAME_PLACEHOLDER to "Rent, gym, salary…",
    StringKey.RECURRING_AMOUNT to "Amount",
    StringKey.RECURRING_TYPE to "Type",
    StringKey.RECURRING_INTERVAL to "Frequency",
    StringKey.RECURRING_START_DATE to "Next charge",
    StringKey.RECURRING_CREATE to "Create",
    StringKey.RECURRING_DUE_TODAY to "Due today",
    StringKey.RECURRING_NEXT_DUE to "Next",
    StringKey.RECURRING_CONFIRM to "Confirm",
    StringKey.RECURRING_SKIP to "Skip",
    StringKey.RECURRING_OVERDUE to "Overdue",
    StringKey.RECURRING_OVERDUE_SINCE to "Due",
    StringKey.RECURRING_NOTE to "A series doesn't move your balance until you confirm each charge.",
    StringKey.RECURRING_CONFIRMED_TOAST to "Transaction recorded",
    StringKey.RECURRING_PAUSE to "Pause",
    StringKey.RECURRING_RESUME to "Resume",
    StringKey.RECURRING_EDIT to "Edit",
    StringKey.RECURRING_PAUSED to "Paused",
    StringKey.RECURRING_EDIT_TITLE to "Edit series",
    StringKey.RECURRING_DELETE to "Delete series",
    StringKey.RECURRING_DELETE_CONFIRM_TITLE to "Delete recurring series",
    StringKey.RECURRING_DELETE_CONFIRM_BODY to "This action can't be undone.",
    StringKey.RECURRING_CATEGORY_AUTO_NOTE to "Category detected from the name. You can change it.",

    StringKey.LOANS_TITLE to "Loans",
    StringKey.LOANS_EMPTY_LENT to "You haven't lent any money. Record the first one with the + above.",
    StringKey.LOANS_EMPTY_BORROWED to "You have no debts on record. Add one with the + above.",
    StringKey.LOANS_DIRECTION to "Direction",
    StringKey.LOANS_DUE_OPTIONAL to "Due date (optional)",
    StringKey.LOANS_NO_DATE to "No date",
    StringKey.LOANS_PAY_TITLE_LENT to "Payment from %s",
    StringKey.LOANS_PAY_TITLE_BORROWED to "Pay %s",
    StringKey.LOANS_PAY_NOTE to "%1\$s outstanding of %2\$s",
    StringKey.LOANS_SETTLED_NOTE to "Settled · %s",
    StringKey.LOANS_PAID_NOTE to " · %1\$s paid of %2\$s",
    StringKey.LOANS_EMPTY to "No lent or borrowed money on record.",
    StringKey.LOANS_LENT_TAB to "Lent",
    StringKey.LOANS_BORROWED_TAB to "Borrowed",
    StringKey.LOANS_SETTLE to "Mark as settled",
    StringKey.LOANS_SETTLED to "Settled",
    StringKey.LOANS_SETTLED_TOAST to "Loan settled",
    StringKey.LOANS_DUE to "Due",
    StringKey.LOANS_NO_DUE_DATE to "No due date",
    StringKey.LOANS_SUMMARY_LENT to "They owe you",
    StringKey.LOANS_SUMMARY_BORROWED to "You owe",
    StringKey.LOANS_RECORD_ONE to "record",
    StringKey.LOANS_RECORD_MANY to "records",
    StringKey.LOANS_SETTLED_WORD_ONE to "settled",
    StringKey.LOANS_SETTLED_WORD_MANY to "settled",
    StringKey.LOANS_NEW_LENT to "Record a loan",
    StringKey.LOANS_NEW_BORROWED to "Record a debt",
    StringKey.LOANS_OUTSTANDING to "Outstanding",
    StringKey.LOANS_PAID_PREFIX to "paid",
    StringKey.LOANS_REGISTER_PAYMENT to "Record payment",
    StringKey.LOANS_SETTLE_ALL_SHORTCUT to "Settle all",
    StringKey.LOANS_PAYMENT_WALLET_LENT to "Wallet receiving the payment",
    StringKey.LOANS_PAYMENT_WALLET_BORROWED to "Wallet the payment comes from",
    StringKey.LOANS_PAYMENT_TITLE to "Record payment",
    StringKey.LOANS_FORM_COUNTERPARTY to "Counterparty",
    StringKey.LOANS_FORM_COUNTERPARTY_PLACEHOLDER to "Person's name",
    StringKey.LOANS_FORM_AMOUNT to "Amount",
    StringKey.LOANS_FORM_WALLET to "Wallet",
    StringKey.LOANS_FORM_DUE_DATE to "Due date",
    StringKey.LOANS_EDIT_TITLE to "Edit loan",
    StringKey.LOANS_DELETE to "Delete loan",
    StringKey.LOANS_DELETE_CONFIRM_TITLE to "Delete this record?",
    StringKey.LOANS_DELETE_CONFIRM_BODY to "This action can't be undone.",
    StringKey.LOANS_FORM_PERSON_LENT to "Who did you lend to?",
    StringKey.LOANS_FORM_PERSON_BORROWED to "Who do you owe?",
    StringKey.LOANS_FORM_WALLET_LENT to "Wallet the money came from",
    StringKey.LOANS_FORM_WALLET_BORROWED to "Wallet that received the money",
    StringKey.LOANS_EDIT_ACTION to "Edit",
    StringKey.DATE_PICKER_TODAY to "Today",
    StringKey.DATE_PICKER_NO_DATE to "No date",
    StringKey.DATE_PICKER_USE_DATE to "Use this date",
    StringKey.DATE_PICKER_CHOOSE to "Choose date",
    StringKey.PLANS_TAB to "Loans",
    StringKey.TITLE_PLANS to "Plans",
    StringKey.GOAL_CATEGORY_EMERGENCY to "Emergency",
    StringKey.GOAL_CATEGORY_TRAVEL to "Travel",
    StringKey.GOAL_CATEGORY_EDUCATION to "Education",
    StringKey.GOAL_CATEGORY_HOUSING to "Housing",
    StringKey.GOAL_CATEGORY_VEHICLE to "Vehicle",
    StringKey.GOAL_CATEGORY_TECHNOLOGY to "Technology",
    StringKey.GOAL_CATEGORY_HEALTH to "Health",
    StringKey.GOAL_CATEGORY_DEBT to "Debt",
    StringKey.GOAL_CATEGORY_RETIREMENT to "Retirement",
    StringKey.GOAL_CATEGORY_OTHER to "Other",

    StringKey.SETTINGS_REPLAY_TUTORIAL to "Replay the tutorial",
    StringKey.SETTINGS_TUTORIAL_HINT to "%s steps · under a minute",
    StringKey.SETTINGS_LOCK_1_MINUTE to "1 minute",
    StringKey.SETTINGS_LOCK_MINUTES to "%s minutes",
    StringKey.SETTINGS_LOCK_1_HOUR to "1 hour",
    StringKey.SETTINGS_AUTO_LOCK_HELP_PASSWORD_AFTER to "After %s without activity we ask for your password again.",
    StringKey.SETTINGS_AUTO_LOCK_HELP_BIOMETRIC_AFTER to "After %s without activity we ask for your fingerprint again.",
    StringKey.TUTORIAL_STEP_OF to "STEP %s OF %s",
    StringKey.TUTORIAL_SKIP to "Skip",
    StringKey.TUTORIAL_BACK to "Back",
    StringKey.TUTORIAL_NEXT to "Next",
    StringKey.TUTORIAL_DONE to "Got it",
    StringKey.TUTORIAL_1_TITLE to "All your money in one balance",
    StringKey.TUTORIAL_1_BODY to "Inicio's balance is the sum of your wallets. Add or edit them from Profile › Wallets and the total updates itself.",
    StringKey.TUTORIAL_2_TITLE to "Record with the + button",
    StringKey.TUTORIAL_2_BODY to "The + in the middle opens an expense, income or transfer. The category is suggested from the name, and you can mark it as upcoming if it doesn't affect the balance yet.",
    StringKey.TUTORIAL_3_TITLE to "Budgets and goals live in Plans",
    StringKey.TUTORIAL_3_BODY to "A budget sets a monthly limit per category. A goal collects contributions from the wallet you pick and remembers where every peso came from.",
    StringKey.TUTORIAL_4_TITLE to "Automate what repeats",
    StringKey.TUTORIAL_4_BODY to "Scheduled keeps your fixed charges with their frequency. They don't move the balance until you confirm each one, so nothing is taken by mistake.",

    StringKey.ONBOARDING_SKIP to "Skip",
    StringKey.ONBOARDING_BACK to "Back",
    StringKey.ONBOARDING_NEXT to "Next",
    StringKey.ONBOARDING_FINISH to "Get started",
    StringKey.ONBOARDING_WELCOME_TITLE to "Welcome to S2 Nova",
    StringKey.ONBOARDING_WELCOME_SUBTITLE to "Your money, under control, in a couple of taps.",
    StringKey.ONBOARDING_GET_STARTED to "Get started",
    StringKey.ONBOARDING_WELCOME_POINT_TRACK to "Track income and expenses instantly",
    StringKey.ONBOARDING_WELCOME_POINT_SCAN to "Scan products to register purchases",
    StringKey.ONBOARDING_WELCOME_POINT_ANALYZE to "Understand your habits from the web dashboard",
    StringKey.ONBOARDING_INCOME_TITLE to "How much do you earn a month?",
    StringKey.ONBOARDING_INCOME_SUBTITLE to "Optional — helps us suggest a budget. You can skip this step.",
    StringKey.ONBOARDING_INCOME_LABEL to "Approximate monthly income",
    StringKey.ONBOARDING_WALLET_TITLE to "Create your first wallet",
    StringKey.ONBOARDING_WALLET_SUBTITLE to "This is where the money you record goes. You can add more later.",
    StringKey.ONBOARDING_WALLET_NAME_PLACEHOLDER to "E.g. Cash, Checking...",
    StringKey.ONBOARDING_BUDGET_TITLE to "A budget suggestion",
    StringKey.ONBOARDING_BUDGET_SUBTITLE to "Based on the 50/30/20 rule — just a suggestion, you decide.",
    StringKey.ONBOARDING_BUDGET_NO_INCOME to "Without an income on record we can't compute a suggestion — you can create budgets manually later.",
    StringKey.ONBOARDING_BUDGET_NEEDS to "Needs",
    StringKey.ONBOARDING_BUDGET_WANTS to "Wants",
    StringKey.ONBOARDING_BUDGET_SAVINGS to "Savings",
    StringKey.ONBOARDING_BUDGET_ACCEPT to "Accept suggestion",
    StringKey.ONBOARDING_TUTORIAL_TRACK_TITLE to "Track your money",
    StringKey.ONBOARDING_TUTORIAL_TRACK_BODY to "Record income, expenses, and transfers between your wallets in seconds.",
    StringKey.ONBOARDING_TUTORIAL_SCAN_TITLE to "Scan your purchases",
    StringKey.ONBOARDING_TUTORIAL_SCAN_BODY to "Use the camera to scan a product and register the purchase instantly.",
    StringKey.ONBOARDING_TUTORIAL_ORGANIZE_TITLE to "Organize your finances",
    StringKey.ONBOARDING_TUTORIAL_ORGANIZE_BODY to "Create wallets, budgets, and goals to keep everything in order.",
    StringKey.ONBOARDING_TUTORIAL_ANALYZE_TITLE to "Understand your finances",
    StringKey.ONBOARDING_TUTORIAL_ANALYZE_BODY to "The web dashboard shows you charts, trends, and detailed reports.",
    StringKey.ONBOARDING_TUTORIAL_READY_TITLE to "You're ready!",
    StringKey.ONBOARDING_TUTORIAL_READY_BODY to "You can now start using S2 Nova.",
    StringKey.NAV_TRANSACTIONS to "Transactions",
    StringKey.HOME_MONTH_INCOME to "Income this month",
    StringKey.HOME_MONTH_EXPENSES to "Expenses this month",
    StringKey.HOME_WALLET_ONE to "wallet",
    StringKey.HOME_WALLET_MANY to "wallets",
    StringKey.HOME_ADD_FIRST_WALLET to "Add your first wallet",
    StringKey.HOME_UPCOMING_7_DAYS to "Next 7 days",
    StringKey.HOME_UPCOMING_LINK to "Scheduled",
    StringKey.HOME_UPCOMING_EMPTY to "Nothing scheduled this week.",
    StringKey.HOME_UPCOMING_TODAY to "TODAY",
    StringKey.HOME_UPCOMING_DUE_TODAY to "Due today · confirm it so it affects your balance",
    StringKey.HOME_UPCOMING_SCHEDULED to "Scheduled · %1\$s",
    StringKey.HOME_SYNC_ERROR to "We couldn't update your data.",
    StringKey.COMMON_RETRY to "Retry",
    StringKey.COMMON_DISMISS to "Dismiss",
    StringKey.AMOUNT_HIDDEN to "Hidden amount",
    StringKey.ALERT_SERIES_DUE_TITLE to "%1\$s is due today",
    StringKey.ALERT_SERIES_OVERDUE_TITLE to "%1\$s was due %2\$s",
    StringKey.ALERT_SERIES_BODY to "%1\$s · confirm it so it affects your balance",
    StringKey.ALERT_LOAN_LENT_TITLE to "%1\$s owes you",
    StringKey.ALERT_LOAN_BORROWED_TITLE to "You owe %1\$s",
    StringKey.ALERT_LOAN_BODY to "%1\$s · due %2\$s",
    StringKey.ALERT_BUDGET_TITLE to "%1\$s at %2\$d%% of its limit",
    StringKey.ALERT_BUDGET_BODY to "%1\$s of %2\$s this month",
    StringKey.ALERT_GOAL_TITLE to "%1\$s is at %2\$d%%",
    StringKey.ALERT_GOAL_BODY to "%1\$s left to reach it",
)

fun stringFor(key: StringKey, language: AppLanguage): String =
    (if (language == AppLanguage.EN) EN else ES).getValue(key)

// Maps mock-data ids to their StringKey so every screen that shows a
// category/payment-method name goes through the same translated lookup
// instead of reading the (Spanish-only) `label` field on the mock data
// directly.
fun categoryStringKey(id: CategoryId): StringKey = when (id) {
    CategoryId.FOOD -> StringKey.CATEGORY_FOOD
    CategoryId.TRANSPORTATION -> StringKey.CATEGORY_TRANSPORTATION
    CategoryId.SHOPPING -> StringKey.CATEGORY_SHOPPING
    CategoryId.HEALTH -> StringKey.CATEGORY_HEALTH
    CategoryId.EDUCATION -> StringKey.CATEGORY_EDUCATION
    CategoryId.ENTERTAINMENT -> StringKey.CATEGORY_ENTERTAINMENT
    CategoryId.BILLS -> StringKey.CATEGORY_BILLS
    CategoryId.SUBSCRIPTIONS -> StringKey.CATEGORY_SUBSCRIPTIONS
    CategoryId.SALARY -> StringKey.CATEGORY_SALARY
    CategoryId.FREELANCE -> StringKey.CATEGORY_FREELANCE
    CategoryId.GIFT -> StringKey.CATEGORY_GIFT
    CategoryId.OTHER -> StringKey.CATEGORY_OTHER
}

fun paymentMethodStringKey(id: PaymentMethod): StringKey = when (id) {
    PaymentMethod.CASH -> StringKey.PAYMENT_CASH
    PaymentMethod.DEBIT_CARD -> StringKey.PAYMENT_DEBIT_CARD
    PaymentMethod.CREDIT_CARD -> StringKey.PAYMENT_CREDIT_CARD
    PaymentMethod.BANK_TRANSFER -> StringKey.PAYMENT_BANK_TRANSFER
    PaymentMethod.NEQUI -> StringKey.PAYMENT_NEQUI
    PaymentMethod.DAVIPLATA -> StringKey.PAYMENT_DAVIPLATA
}

fun budgetStatusStringKey(status: com.s2nova.app.data.model.BudgetStatus): StringKey = when (status) {
    com.s2nova.app.data.model.BudgetStatus.OVER_BUDGET -> StringKey.BUDGET_STATUS_OVER
    com.s2nova.app.data.model.BudgetStatus.NEAR_LIMIT -> StringKey.BUDGET_STATUS_NEAR
    com.s2nova.app.data.model.BudgetStatus.ON_TRACK -> StringKey.BUDGET_STATUS_ON_TRACK
}

@Composable
fun rememberStrings(): (StringKey) -> String {
    val user by AppContainer.authRepository.currentUser.collectAsStateWithLifecycle()
    val language = user?.preferences?.language ?: AppLanguage.ES
    return { key -> stringFor(key, language) }
}

@Composable
fun rememberAppLanguage(): AppLanguage {
    val user by AppContainer.authRepository.currentUser.collectAsStateWithLifecycle()
    return user?.preferences?.language ?: AppLanguage.ES
}
