package com.s2nova.app.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.s2nova.app.data.AppContainer
import com.s2nova.app.data.model.AppLanguage
import com.s2nova.app.data.model.CategoryId
import com.s2nova.app.data.model.PaymentMethod

// Small hand-rolled dictionary, same scope/approach as web's
// src/lib/i18n/translations.ts. Covers every screen except auth (no user/
// language preference exists yet before login) and the barcode scanner
// (explicitly out of scope — see AGENTS.md).
enum class StringKey {
    NAV_HOME, NAV_REPORTS, NAV_BUDGETS, NAV_PROFILE, NAV_ADD,
    TITLE_TRANSACTIONS, TITLE_REPORTS, TITLE_BUDGETS, TITLE_SETTINGS,
    SETTINGS_PERSONAL_INFO, SETTINGS_FULL_NAME, SETTINGS_EMAIL,
    SETTINGS_SAVE_CHANGES, SETTINGS_PREFERENCES, SETTINGS_DARK_MODE, SETTINGS_NOTIFICATIONS,
    SETTINGS_BIOMETRIC, SETTINGS_CURRENCY_FORMAT, SETTINGS_LANGUAGE, SETTINGS_ABOUT,
    SETTINGS_ABOUT_NOTE,
    SETTINGS_CHANGE_PASSWORD, SETTINGS_CREATE_PASSWORD, SETTINGS_CURRENT_PASSWORD,
    SETTINGS_NEW_PASSWORD, SETTINGS_CONFIRM_NEW_PASSWORD, SETTINGS_PASSWORD_MISMATCH,
    SETTINGS_PASSWORD_CHANGED, SETTINGS_CHANGE,

    ADD_TXN_TITLE_NEW, ADD_TXN_TITLE_EDIT, ADD_TXN_EXPENSE, ADD_TXN_INCOME,
    ADD_TXN_AMOUNT, ADD_TXN_DESCRIPTION, ADD_TXN_DESCRIPTION_PLACEHOLDER,
    ADD_TXN_CATEGORY, ADD_TXN_PAYMENT_METHOD, ADD_TXN_NOTE, ADD_TXN_NOTE_PLACEHOLDER,
    ADD_TXN_SAVE_NEW, ADD_TXN_SAVE_EDIT, ADD_TXN_ERROR_AMOUNT, ADD_TXN_ERROR_DESCRIPTION,
    ADD_TXN_SELECT_CATEGORY_TITLE, ADD_TXN_CHANGE_CATEGORY_CD,

    ADD_ACTION_MANUAL_TITLE, ADD_ACTION_MANUAL_SUBTITLE,
    ADD_ACTION_SCAN_TITLE, ADD_ACTION_SCAN_SUBTITLE,

    PROFILE_DEMO_ACCOUNT, PROFILE_TRANSACTIONS, PROFILE_BUDGETS, PROFILE_AVAILABLE,
    PROFILE_ACCOUNT_SECURITY, PROFILE_EDIT_PROFILE, PROFILE_CHANGE_PASSWORD, PROFILE_TWO_FACTOR,
    PROFILE_PREFERENCES, PROFILE_PRIVACY, PROFILE_LOGOUT,

    CATEGORY_FOOD, CATEGORY_TRANSPORTATION, CATEGORY_SHOPPING, CATEGORY_HEALTH,
    CATEGORY_EDUCATION, CATEGORY_ENTERTAINMENT, CATEGORY_BILLS, CATEGORY_SUBSCRIPTIONS,
    CATEGORY_SALARY, CATEGORY_FREELANCE, CATEGORY_OTHER,

    PAYMENT_CASH, PAYMENT_DEBIT_CARD, PAYMENT_CREDIT_CARD, PAYMENT_BANK_TRANSFER,
    PAYMENT_NEQUI, PAYMENT_DAVIPLATA,

    COMMON_CANCEL, COMMON_SAVE, COMMON_BACK,

    SCANNER_TITLE, SCANNER_CLOSE_CD, SCANNER_PERMISSION_MESSAGE, SCANNER_PERMISSION_BUTTON,
    SCANNER_NOT_FOUND, SCANNER_TRY_AGAIN, SCANNER_HINT, SCANNER_MANUAL_PLACEHOLDER,
    SCANNER_DISCARD, SCANNER_CONFIRM_PURCHASE, SCANNER_NOTIF_TITLE,
    SCANNER_NOTIF_MESSAGE_PREFIX, SCANNER_NOTIF_MESSAGE_MIDDLE,

    HOME_GREETING, HOME_BALANCE, HOME_INCOME, HOME_EXPENSES, HOME_SAVINGS,
    HOME_EXPENSE_SUMMARY, HOME_NO_EXPENSES, HOME_RECENT_TXNS, HOME_SEE_ALL,
    HOME_UPCOMING_PAYMENTS, HOME_WALLET_COUNT_SUFFIX,

    NOTIF_MARK_ALL_READ, NOTIF_EMPTY,

    REPORTS_RANGE_3M, REPORTS_RANGE_6M, REPORTS_RANGE_12M,
    REPORTS_SAVINGS_RATE,
    REPORTS_PERIOD_TOTALS, REPORTS_INCOME_VS_EXPENSES, REPORTS_SPEND_BY_CATEGORY,

    TXN_LIST_SEARCH_PLACEHOLDER, TXN_LIST_FILTER_ALL, TXN_LIST_FILTER_PENDING, TXN_LIST_EMPTY_TITLE, TXN_LIST_EMPTY_SUBTITLE,

    TXN_DETAIL_TITLE, TXN_DETAIL_EDIT_CD, TXN_DETAIL_NOT_FOUND, TXN_DETAIL_DATE,
    TXN_DETAIL_MERCHANT, TXN_DETAIL_NOTE, TXN_DETAIL_DELETE, TXN_DETAIL_DELETE_DIALOG_TITLE,
    TXN_DETAIL_DELETE_CONFIRM_PREFIX, TXN_DETAIL_DELETE_CONFIRM_SUFFIX, TXN_DETAIL_DELETE_CONFIRM,

    BUDGETS_MONTH_LABEL, BUDGETS_UTILIZED, BUDGETS_NEW, BUDGETS_MONTHLY_LIMIT,
    BUDGETS_EDIT_TITLE_PREFIX, BUDGETS_CREATE, BUDGETS_OF, BUDGETS_REMAINING, BUDGETS_OVER_LIMIT,
    BUDGET_STATUS_OVER, BUDGET_STATUS_NEAR, BUDGET_STATUS_ON_TRACK,
    BUDGETS_NAME_OPTIONAL, BUDGETS_NAME_PLACEHOLDER,

    ADD_TXN_TRANSFER, ADD_TXN_TRANSFER_TO, ADD_TXN_WALLET, ADD_TXN_MORE_OPTIONS,
    ADD_TXN_BUDGET, ADD_TXN_GOAL, ADD_TXN_NONE, ADD_TXN_UPCOMING, ADD_TXN_UPCOMING_HINT,
    ADD_TXN_RECURRING_HINT, ADD_TXN_LENT, ADD_TXN_BORROWED, ADD_TXN_LOAN_HINT,
    ADD_TXN_COUNTERPARTY, ADD_TXN_COUNTERPARTY_PLACEHOLDER, ADD_TXN_DUE_DATE,
    ADD_TXN_ERROR_WALLET, ADD_TXN_ERROR_TRANSFER_WALLET,
    ADD_TXN_NO_WALLET_TITLE, ADD_TXN_NO_WALLET_SUBTITLE, ADD_TXN_NO_WALLET_CTA,
    RECURRENCE_WEEKLY, RECURRENCE_MONTHLY, RECURRENCE_YEARLY,

    WALLETS_TITLE, WALLETS_NEW, WALLETS_NAME, WALLETS_TYPE, WALLETS_INITIAL_BALANCE,
    WALLETS_CREATE, WALLETS_EMPTY_TITLE, WALLETS_EMPTY_SUBTITLE, WALLETS_FOOTER_NOTE,
    WALLET_TYPE_CASH, WALLET_TYPE_BANK_DEBIT, WALLET_TYPE_BANK_CREDIT, WALLET_TYPE_SAVINGS,
    WALLET_TYPE_CRYPTO, WALLET_TYPE_NEQUI, WALLET_TYPE_DAVIPLATA, WALLET_TYPE_OTHER,

    GOALS_TITLE, GOALS_NEW, GOALS_EMPTY, GOALS_NAME, GOALS_NAME_PLACEHOLDER,
    GOALS_TARGET_AMOUNT, GOALS_CREATE, GOALS_CONTRIBUTE,

    GOAL_CONTRIBUTION_TITLE, GOAL_CONTRIBUTION_AMOUNT, GOAL_CONTRIBUTION_WALLET,
    GOAL_CONTRIBUTION_SAVE, GOAL_CONTRIBUTION_SAVED, GOAL_CONTRIBUTION_DESCRIPTION_PREFIX,
    GOAL_CONTRIBUTION_ERROR_AMOUNT, GOAL_CONTRIBUTION_ERROR_WALLET,

    COMMON_UNDO,

    RECURRING_TITLE, RECURRING_NEW, RECURRING_EMPTY, RECURRING_NAME, RECURRING_NAME_PLACEHOLDER,
    RECURRING_AMOUNT, RECURRING_TYPE, RECURRING_INTERVAL, RECURRING_START_DATE, RECURRING_CREATE,
    RECURRING_DUE_TODAY, RECURRING_NEXT_DUE, RECURRING_CONFIRM, RECURRING_CONFIRMED_TOAST,
    RECURRING_PAUSE, RECURRING_RESUME, RECURRING_PAUSED,

    LOANS_TITLE, LOANS_EMPTY, LOANS_LENT_TAB, LOANS_BORROWED_TAB,
    LOANS_SETTLE, LOANS_SETTLED, LOANS_SETTLED_TOAST, LOANS_DUE, LOANS_NO_DUE_DATE,

    SETTINGS_REPLAY_TUTORIAL,

    ONBOARDING_SKIP, ONBOARDING_BACK, ONBOARDING_NEXT, ONBOARDING_FINISH,
    ONBOARDING_WELCOME_TITLE, ONBOARDING_WELCOME_SUBTITLE, ONBOARDING_GET_STARTED,
    ONBOARDING_WELCOME_POINT_TRACK, ONBOARDING_WELCOME_POINT_SCAN, ONBOARDING_WELCOME_POINT_ANALYZE,
    ONBOARDING_INCOME_TITLE, ONBOARDING_INCOME_SUBTITLE, ONBOARDING_INCOME_LABEL,
    ONBOARDING_WALLET_TITLE, ONBOARDING_WALLET_SUBTITLE, ONBOARDING_WALLET_NAME_PLACEHOLDER,
    ONBOARDING_BUDGET_TITLE, ONBOARDING_BUDGET_SUBTITLE, ONBOARDING_BUDGET_NO_INCOME,
    ONBOARDING_BUDGET_NEEDS, ONBOARDING_BUDGET_WANTS, ONBOARDING_BUDGET_SAVINGS, ONBOARDING_BUDGET_ACCEPT,
    ONBOARDING_TUTORIAL_TRACK_TITLE, ONBOARDING_TUTORIAL_TRACK_BODY,
    ONBOARDING_TUTORIAL_SCAN_TITLE, ONBOARDING_TUTORIAL_SCAN_BODY,
    ONBOARDING_TUTORIAL_ORGANIZE_TITLE, ONBOARDING_TUTORIAL_ORGANIZE_BODY,
    ONBOARDING_TUTORIAL_ANALYZE_TITLE, ONBOARDING_TUTORIAL_ANALYZE_BODY,
    ONBOARDING_TUTORIAL_READY_TITLE, ONBOARDING_TUTORIAL_READY_BODY,
}

private val ES: Map<StringKey, String> = mapOf(
    StringKey.NAV_HOME to "Inicio",
    StringKey.NAV_REPORTS to "Reportes",
    StringKey.NAV_BUDGETS to "Presupuesto",
    StringKey.NAV_PROFILE to "Perfil",
    StringKey.NAV_ADD to "Agregar",
    StringKey.TITLE_TRANSACTIONS to "Movimientos",
    StringKey.TITLE_REPORTS to "Reportes",
    StringKey.TITLE_BUDGETS to "Presupuestos",
    StringKey.TITLE_SETTINGS to "Configuración",
    StringKey.SETTINGS_PERSONAL_INFO to "Información personal",
    StringKey.SETTINGS_FULL_NAME to "Nombre completo",
    StringKey.SETTINGS_EMAIL to "Correo electrónico",
    StringKey.SETTINGS_SAVE_CHANGES to "Guardar cambios",
    StringKey.SETTINGS_CHANGE_PASSWORD to "Cambiar contraseña",
    StringKey.SETTINGS_CREATE_PASSWORD to "Crear contraseña",
    StringKey.SETTINGS_CURRENT_PASSWORD to "Contraseña actual",
    StringKey.SETTINGS_NEW_PASSWORD to "Nueva contraseña",
    StringKey.SETTINGS_CONFIRM_NEW_PASSWORD to "Confirmar nueva contraseña",
    StringKey.SETTINGS_PASSWORD_MISMATCH to "Las contraseñas no coinciden.",
    StringKey.SETTINGS_PASSWORD_CHANGED to "Contraseña actualizada. Vuelve a iniciar sesión.",
    StringKey.SETTINGS_CHANGE to "Cambiar",
    StringKey.SETTINGS_PREFERENCES to "Preferencias",
    StringKey.SETTINGS_DARK_MODE to "Modo oscuro",
    StringKey.SETTINGS_NOTIFICATIONS to "Notificaciones",
    StringKey.SETTINGS_BIOMETRIC to "Inicio biométrico",
    StringKey.SETTINGS_CURRENCY_FORMAT to "Formato de moneda",
    StringKey.SETTINGS_LANGUAGE to "Idioma",
    StringKey.SETTINGS_ABOUT to "Acerca de",
    StringKey.SETTINGS_ABOUT_NOTE to "Datos de demostración, sin conexión a un backend real.",

    StringKey.ADD_TXN_TITLE_NEW to "Agregar movimiento",
    StringKey.ADD_TXN_TITLE_EDIT to "Editar movimiento",
    StringKey.ADD_TXN_EXPENSE to "Gasto",
    StringKey.ADD_TXN_INCOME to "Ingreso",
    StringKey.ADD_TXN_AMOUNT to "Monto",
    StringKey.ADD_TXN_DESCRIPTION to "Descripción",
    StringKey.ADD_TXN_DESCRIPTION_PLACEHOLDER to "Ej. Mercado semanal",
    StringKey.ADD_TXN_CATEGORY to "Categoría",
    StringKey.ADD_TXN_PAYMENT_METHOD to "Método de pago",
    StringKey.ADD_TXN_NOTE to "Nota (opcional)",
    StringKey.ADD_TXN_NOTE_PLACEHOLDER to "Agrega una nota",
    StringKey.ADD_TXN_SAVE_NEW to "Guardar movimiento",
    StringKey.ADD_TXN_SAVE_EDIT to "Guardar cambios",
    StringKey.ADD_TXN_ERROR_AMOUNT to "Ingresa un monto válido.",
    StringKey.ADD_TXN_ERROR_DESCRIPTION to "Ingresa una descripción.",
    StringKey.ADD_TXN_SELECT_CATEGORY_TITLE to "Elige una categoría",
    StringKey.ADD_TXN_CHANGE_CATEGORY_CD to "Cambiar categoría",

    StringKey.ADD_ACTION_MANUAL_TITLE to "Agregar manualmente",
    StringKey.ADD_ACTION_MANUAL_SUBTITLE to "Registra un ingreso o gasto",
    StringKey.ADD_ACTION_SCAN_TITLE to "Escanear código de barras",
    StringKey.ADD_ACTION_SCAN_SUBTITLE to "Registra una compra al instante",

    StringKey.PROFILE_DEMO_ACCOUNT to "Cuenta demo",
    StringKey.PROFILE_TRANSACTIONS to "Transacciones",
    StringKey.PROFILE_BUDGETS to "Presupuestos",
    StringKey.PROFILE_AVAILABLE to "Disponible",
    StringKey.PROFILE_ACCOUNT_SECURITY to "CUENTA Y SEGURIDAD",
    StringKey.PROFILE_EDIT_PROFILE to "Editar perfil",
    StringKey.PROFILE_CHANGE_PASSWORD to "Cambiar contraseña",
    StringKey.PROFILE_TWO_FACTOR to "Autenticación de dos factores",
    StringKey.PROFILE_PREFERENCES to "PREFERENCIAS",
    StringKey.PROFILE_PRIVACY to "Privacidad y seguridad",
    StringKey.PROFILE_LOGOUT to "Cerrar sesión",

    StringKey.CATEGORY_FOOD to "Alimentación",
    StringKey.CATEGORY_TRANSPORTATION to "Transporte",
    StringKey.CATEGORY_SHOPPING to "Compras",
    StringKey.CATEGORY_HEALTH to "Salud",
    StringKey.CATEGORY_EDUCATION to "Educación",
    StringKey.CATEGORY_ENTERTAINMENT to "Entretenimiento",
    StringKey.CATEGORY_BILLS to "Servicios",
    StringKey.CATEGORY_SUBSCRIPTIONS to "Suscripciones",
    StringKey.CATEGORY_SALARY to "Salario",
    StringKey.CATEGORY_FREELANCE to "Freelance",
    StringKey.CATEGORY_OTHER to "Otros",

    StringKey.PAYMENT_CASH to "Efectivo",
    StringKey.PAYMENT_DEBIT_CARD to "Tarjeta débito",
    StringKey.PAYMENT_CREDIT_CARD to "Tarjeta crédito",
    StringKey.PAYMENT_BANK_TRANSFER to "Transferencia",
    StringKey.PAYMENT_NEQUI to "Nequi",
    StringKey.PAYMENT_DAVIPLATA to "Daviplata",

    StringKey.COMMON_CANCEL to "Cancelar",
    StringKey.COMMON_SAVE to "Guardar",
    StringKey.COMMON_BACK to "Atrás",

    StringKey.SCANNER_TITLE to "Escanear código",
    StringKey.SCANNER_CLOSE_CD to "Cerrar",
    StringKey.SCANNER_PERMISSION_MESSAGE to "S2 Nova necesita acceso a la cámara para escanear códigos de barras.",
    StringKey.SCANNER_PERMISSION_BUTTON to "Permitir acceso a la cámara",
    StringKey.SCANNER_NOT_FOUND to "No encontramos ese producto.",
    StringKey.SCANNER_TRY_AGAIN to "Intentar de nuevo",
    StringKey.SCANNER_HINT to "Ubica el código de barras dentro del marco",
    StringKey.SCANNER_MANUAL_PLACEHOLDER to "O ingresa el código manualmente",
    StringKey.SCANNER_DISCARD to "Descartar",
    StringKey.SCANNER_CONFIRM_PURCHASE to "Registrar compra",
    StringKey.SCANNER_NOTIF_TITLE to "Compra registrada",
    StringKey.SCANNER_NOTIF_MESSAGE_PREFIX to "Se registró \"",
    StringKey.SCANNER_NOTIF_MESSAGE_MIDDLE to "\" — ",

    StringKey.HOME_GREETING to "HOLA",
    StringKey.HOME_BALANCE to "SALDO ACTUAL",
    StringKey.HOME_INCOME to "Ingresos",
    StringKey.HOME_EXPENSES to "Gastos",
    StringKey.HOME_SAVINGS to "Ahorro",
    StringKey.HOME_EXPENSE_SUMMARY to "Resumen de gastos",
    StringKey.HOME_NO_EXPENSES to "Sin gastos este mes.",
    StringKey.HOME_RECENT_TXNS to "Movimientos recientes",
    StringKey.HOME_SEE_ALL to "Ver todos",
    StringKey.HOME_UPCOMING_PAYMENTS to "Próximos pagos",
    StringKey.HOME_WALLET_COUNT_SUFFIX to "billeteras",

    StringKey.NOTIF_MARK_ALL_READ to "Marcar todo leído",
    StringKey.NOTIF_EMPTY to "No tienes notificaciones.",

    StringKey.REPORTS_RANGE_3M to "3M",
    StringKey.REPORTS_RANGE_6M to "6M",
    StringKey.REPORTS_RANGE_12M to "12M",
    StringKey.REPORTS_SAVINGS_RATE to "Tasa de ahorro",
    StringKey.REPORTS_PERIOD_TOTALS to "Totales del periodo",
    StringKey.REPORTS_INCOME_VS_EXPENSES to "Ingresos vs gastos",
    StringKey.REPORTS_SPEND_BY_CATEGORY to "Gasto por categoría",

    StringKey.TXN_LIST_SEARCH_PLACEHOLDER to "Buscar por descripción o comercio",
    StringKey.TXN_LIST_FILTER_ALL to "Todos",
    StringKey.TXN_LIST_FILTER_PENDING to "Pendientes",
    StringKey.TXN_LIST_EMPTY_TITLE to "Sin resultados",
    StringKey.TXN_LIST_EMPTY_SUBTITLE to "Ajusta la búsqueda o los filtros.",

    StringKey.TXN_DETAIL_TITLE to "Detalle del movimiento",
    StringKey.TXN_DETAIL_EDIT_CD to "Editar",
    StringKey.TXN_DETAIL_NOT_FOUND to "Este movimiento ya no existe.",
    StringKey.TXN_DETAIL_DATE to "Fecha",
    StringKey.TXN_DETAIL_MERCHANT to "Comercio",
    StringKey.TXN_DETAIL_NOTE to "Nota",
    StringKey.TXN_DETAIL_DELETE to "Eliminar movimiento",
    StringKey.TXN_DETAIL_DELETE_DIALOG_TITLE to "Eliminar transacción",
    StringKey.TXN_DETAIL_DELETE_CONFIRM_PREFIX to "¿Seguro que deseas eliminar",
    StringKey.TXN_DETAIL_DELETE_CONFIRM_SUFFIX to "? Esta acción no se puede deshacer.",
    StringKey.TXN_DETAIL_DELETE_CONFIRM to "Eliminar",

    StringKey.BUDGETS_MONTH_LABEL to "PRESUPUESTO DEL MES",
    StringKey.BUDGETS_UTILIZED to "utilizado",
    StringKey.BUDGETS_NEW to "Nuevo presupuesto",
    StringKey.BUDGETS_MONTHLY_LIMIT to "Límite mensual",
    StringKey.BUDGETS_EDIT_TITLE_PREFIX to "Editar presupuesto de",
    StringKey.BUDGETS_CREATE to "Crear",
    StringKey.BUDGETS_OF to "de",
    StringKey.BUDGETS_REMAINING to "disponibles",
    StringKey.BUDGETS_OVER_LIMIT to "por encima del límite",
    StringKey.BUDGET_STATUS_OVER to "Excedido",
    StringKey.BUDGET_STATUS_NEAR to "Cerca del límite",
    StringKey.BUDGET_STATUS_ON_TRACK to "En curso",
    StringKey.BUDGETS_NAME_OPTIONAL to "Nombre (opcional)",
    StringKey.BUDGETS_NAME_PLACEHOLDER to "Ej. Vacaciones",

    StringKey.ADD_TXN_TRANSFER to "Transferencia",
    StringKey.ADD_TXN_TRANSFER_TO to "Transferir a",
    StringKey.ADD_TXN_WALLET to "Wallet",
    StringKey.ADD_TXN_MORE_OPTIONS to "Más opciones",
    StringKey.ADD_TXN_BUDGET to "Presupuesto (opcional)",
    StringKey.ADD_TXN_GOAL to "Objetivo (opcional)",
    StringKey.ADD_TXN_NONE to "Ninguno",
    StringKey.ADD_TXN_UPCOMING to "Próximo",
    StringKey.ADD_TXN_UPCOMING_HINT to "Aún no ha ocurrido — no afecta tu saldo todavía.",
    StringKey.ADD_TXN_RECURRING_HINT to "¿Es un pago o ingreso recurrente? Gestiónalo en Recurrentes →",
    StringKey.ADD_TXN_LENT to "Es un préstamo que hice",
    StringKey.ADD_TXN_BORROWED to "Es dinero que me prestaron",
    StringKey.ADD_TXN_LOAN_HINT to "Se marcará como pendiente hasta que lo liquides.",
    StringKey.ADD_TXN_COUNTERPARTY to "Persona",
    StringKey.ADD_TXN_COUNTERPARTY_PLACEHOLDER to "¿A quién / de quién?",
    StringKey.ADD_TXN_DUE_DATE to "Fecha límite (opcional)",
    StringKey.ADD_TXN_ERROR_WALLET to "Selecciona una wallet.",
    StringKey.ADD_TXN_ERROR_TRANSFER_WALLET to "Selecciona la wallet de destino.",
    StringKey.ADD_TXN_NO_WALLET_TITLE to "Aún no tienes wallets",
    StringKey.ADD_TXN_NO_WALLET_SUBTITLE to "Crea una wallet (efectivo, banco, ahorros...) antes de registrar movimientos.",
    StringKey.ADD_TXN_NO_WALLET_CTA to "Crear wallet",
    StringKey.RECURRENCE_WEEKLY to "Semanal",
    StringKey.RECURRENCE_MONTHLY to "Mensual",
    StringKey.RECURRENCE_YEARLY to "Anual",

    StringKey.WALLETS_TITLE to "Mis wallets",
    StringKey.WALLETS_NEW to "Nueva wallet",
    StringKey.WALLETS_NAME to "Nombre",
    StringKey.WALLETS_TYPE to "Tipo",
    StringKey.WALLETS_INITIAL_BALANCE to "Saldo inicial",
    StringKey.WALLETS_CREATE to "Crear",
    StringKey.WALLETS_EMPTY_TITLE to "Sin wallets todavía",
    StringKey.WALLETS_EMPTY_SUBTITLE to "Crea tu primera wallet para empezar a registrar movimientos.",
    StringKey.WALLETS_FOOTER_NOTE to "El saldo total de Inicio es la suma de estas wallets.",
    StringKey.WALLET_TYPE_CASH to "Efectivo",
    StringKey.WALLET_TYPE_BANK_DEBIT to "Cuenta débito",
    StringKey.WALLET_TYPE_BANK_CREDIT to "Tarjeta de crédito",
    StringKey.WALLET_TYPE_SAVINGS to "Ahorros",
    StringKey.WALLET_TYPE_CRYPTO to "Bitcoin/Cripto",
    StringKey.WALLET_TYPE_NEQUI to "Nequi",
    StringKey.WALLET_TYPE_DAVIPLATA to "Daviplata",
    StringKey.WALLET_TYPE_OTHER to "Otro",

    StringKey.GOALS_TITLE to "Objetivos",
    StringKey.GOALS_NEW to "Nuevo objetivo",
    StringKey.GOALS_EMPTY to "Aún no tienes objetivos. Crea uno como \"Cuota del carro\".",
    StringKey.GOALS_NAME to "Nombre",
    StringKey.GOALS_NAME_PLACEHOLDER to "Ej. Cuota del carro",
    StringKey.GOALS_TARGET_AMOUNT to "Monto objetivo",
    StringKey.GOALS_CREATE to "Crear",
    StringKey.GOALS_CONTRIBUTE to "Abonar",

    StringKey.GOAL_CONTRIBUTION_TITLE to "Abonar a objetivo",
    StringKey.GOAL_CONTRIBUTION_AMOUNT to "Monto a abonar",
    StringKey.GOAL_CONTRIBUTION_WALLET to "Desde",
    StringKey.GOAL_CONTRIBUTION_SAVE to "Abonar",
    StringKey.GOAL_CONTRIBUTION_SAVED to "Abono agregado",
    StringKey.GOAL_CONTRIBUTION_DESCRIPTION_PREFIX to "Abono a ",
    StringKey.GOAL_CONTRIBUTION_ERROR_AMOUNT to "Ingresa un monto válido.",
    StringKey.GOAL_CONTRIBUTION_ERROR_WALLET to "Elige una wallet de origen.",

    StringKey.COMMON_UNDO to "Deshacer",

    StringKey.RECURRING_TITLE to "Recurrentes",
    StringKey.RECURRING_NEW to "Nuevo recurrente",
    StringKey.RECURRING_EMPTY to "Sin pagos o ingresos recurrentes todavía.",
    StringKey.RECURRING_NAME to "Nombre",
    StringKey.RECURRING_NAME_PLACEHOLDER to "Ej. Netflix, Salario, Arriendo",
    StringKey.RECURRING_AMOUNT to "Monto",
    StringKey.RECURRING_TYPE to "Tipo",
    StringKey.RECURRING_INTERVAL to "Frecuencia",
    StringKey.RECURRING_START_DATE to "Primera fecha",
    StringKey.RECURRING_CREATE to "Crear",
    StringKey.RECURRING_DUE_TODAY to "Vence hoy",
    StringKey.RECURRING_NEXT_DUE to "Próximo",
    StringKey.RECURRING_CONFIRM to "Confirmar",
    StringKey.RECURRING_CONFIRMED_TOAST to "Movimiento registrado",
    StringKey.RECURRING_PAUSE to "Pausar",
    StringKey.RECURRING_RESUME to "Reanudar",
    StringKey.RECURRING_PAUSED to "Pausado",

    StringKey.LOANS_TITLE to "Préstamos",
    StringKey.LOANS_EMPTY to "No tienes préstamos registrados.",
    StringKey.LOANS_LENT_TAB to "Prestado",
    StringKey.LOANS_BORROWED_TAB to "Recibido",
    StringKey.LOANS_SETTLE to "Marcar como pagado",
    StringKey.LOANS_SETTLED to "Pagado",
    StringKey.LOANS_SETTLED_TOAST to "Préstamo liquidado",
    StringKey.LOANS_DUE to "Vence",
    StringKey.LOANS_NO_DUE_DATE to "Sin fecha límite",

    StringKey.SETTINGS_REPLAY_TUTORIAL to "Ver el tutorial de nuevo",

    StringKey.ONBOARDING_SKIP to "Omitir",
    StringKey.ONBOARDING_BACK to "Atrás",
    StringKey.ONBOARDING_NEXT to "Siguiente",
    StringKey.ONBOARDING_FINISH to "Empezar",
    StringKey.ONBOARDING_WELCOME_TITLE to "Bienvenido a S2 Nova",
    StringKey.ONBOARDING_WELCOME_SUBTITLE to "Tu dinero, bajo control, en un par de toques.",
    StringKey.ONBOARDING_GET_STARTED to "Comenzar",
    StringKey.ONBOARDING_WELCOME_POINT_TRACK to "Registra ingresos y gastos al instante",
    StringKey.ONBOARDING_WELCOME_POINT_SCAN to "Escanea productos para registrar compras",
    StringKey.ONBOARDING_WELCOME_POINT_ANALYZE to "Entiende tus hábitos desde el dashboard web",
    StringKey.ONBOARDING_INCOME_TITLE to "¿Cuánto ingresas al mes?",
    StringKey.ONBOARDING_INCOME_SUBTITLE to "Opcional — nos ayuda a sugerirte un presupuesto. Puedes omitir este paso.",
    StringKey.ONBOARDING_INCOME_LABEL to "Ingreso mensual aproximado",
    StringKey.ONBOARDING_WALLET_TITLE to "Crea tu primera wallet",
    StringKey.ONBOARDING_WALLET_SUBTITLE to "Aquí es donde entra el dinero que registres. Puedes agregar más después.",
    StringKey.ONBOARDING_WALLET_NAME_PLACEHOLDER to "Ej. Efectivo, Bancolombia...",
    StringKey.ONBOARDING_BUDGET_TITLE to "Una sugerencia de presupuesto",
    StringKey.ONBOARDING_BUDGET_SUBTITLE to "Basado en la regla 50/30/20 — solo una sugerencia, tú decides.",
    StringKey.ONBOARDING_BUDGET_NO_INCOME to "Sin un ingreso registrado no podemos calcular una sugerencia — puedes crear presupuestos manualmente después.",
    StringKey.ONBOARDING_BUDGET_NEEDS to "Necesidades",
    StringKey.ONBOARDING_BUDGET_WANTS to "Gustos",
    StringKey.ONBOARDING_BUDGET_SAVINGS to "Ahorro",
    StringKey.ONBOARDING_BUDGET_ACCEPT to "Aceptar sugerencia",
    StringKey.ONBOARDING_TUTORIAL_TRACK_TITLE to "Controla tu dinero",
    StringKey.ONBOARDING_TUTORIAL_TRACK_BODY to "Registra ingresos, gastos y transferencias entre tus wallets en segundos.",
    StringKey.ONBOARDING_TUTORIAL_SCAN_TITLE to "Escanea tus compras",
    StringKey.ONBOARDING_TUTORIAL_SCAN_BODY to "Usa la cámara para escanear un producto y registrar la compra al instante.",
    StringKey.ONBOARDING_TUTORIAL_ORGANIZE_TITLE to "Organiza tus finanzas",
    StringKey.ONBOARDING_TUTORIAL_ORGANIZE_BODY to "Crea wallets, presupuestos y objetivos para mantener todo en orden.",
    StringKey.ONBOARDING_TUTORIAL_ANALYZE_TITLE to "Entiende tus finanzas",
    StringKey.ONBOARDING_TUTORIAL_ANALYZE_BODY to "El dashboard web te muestra gráficas, tendencias y reportes detallados.",
    StringKey.ONBOARDING_TUTORIAL_READY_TITLE to "¡Listo!",
    StringKey.ONBOARDING_TUTORIAL_READY_BODY to "Ya puedes empezar a usar S2 Nova.",
)

private val EN: Map<StringKey, String> = mapOf(
    StringKey.NAV_HOME to "Home",
    StringKey.NAV_REPORTS to "Reports",
    StringKey.NAV_BUDGETS to "Budget",
    StringKey.NAV_PROFILE to "Profile",
    StringKey.NAV_ADD to "Add",
    StringKey.TITLE_TRANSACTIONS to "Transactions",
    StringKey.TITLE_REPORTS to "Reports",
    StringKey.TITLE_BUDGETS to "Budgets",
    StringKey.TITLE_SETTINGS to "Settings",
    StringKey.SETTINGS_PERSONAL_INFO to "Personal information",
    StringKey.SETTINGS_FULL_NAME to "Full name",
    StringKey.SETTINGS_EMAIL to "Email address",
    StringKey.SETTINGS_SAVE_CHANGES to "Save changes",
    StringKey.SETTINGS_CHANGE_PASSWORD to "Change password",
    StringKey.SETTINGS_CREATE_PASSWORD to "Create password",
    StringKey.SETTINGS_CURRENT_PASSWORD to "Current password",
    StringKey.SETTINGS_NEW_PASSWORD to "New password",
    StringKey.SETTINGS_CONFIRM_NEW_PASSWORD to "Confirm new password",
    StringKey.SETTINGS_PASSWORD_MISMATCH to "Passwords don't match.",
    StringKey.SETTINGS_PASSWORD_CHANGED to "Password updated. Please log in again.",
    StringKey.SETTINGS_CHANGE to "Change",
    StringKey.SETTINGS_PREFERENCES to "Preferences",
    StringKey.SETTINGS_DARK_MODE to "Dark mode",
    StringKey.SETTINGS_NOTIFICATIONS to "Notifications",
    StringKey.SETTINGS_BIOMETRIC to "Biometric login",
    StringKey.SETTINGS_CURRENCY_FORMAT to "Currency format",
    StringKey.SETTINGS_LANGUAGE to "Language",
    StringKey.SETTINGS_ABOUT to "About",
    StringKey.SETTINGS_ABOUT_NOTE to "Demo data, not connected to a real backend.",

    StringKey.ADD_TXN_TITLE_NEW to "Add transaction",
    StringKey.ADD_TXN_TITLE_EDIT to "Edit transaction",
    StringKey.ADD_TXN_EXPENSE to "Expense",
    StringKey.ADD_TXN_INCOME to "Income",
    StringKey.ADD_TXN_AMOUNT to "Amount",
    StringKey.ADD_TXN_DESCRIPTION to "Description",
    StringKey.ADD_TXN_DESCRIPTION_PLACEHOLDER to "E.g. Weekly groceries",
    StringKey.ADD_TXN_CATEGORY to "Category",
    StringKey.ADD_TXN_PAYMENT_METHOD to "Payment method",
    StringKey.ADD_TXN_NOTE to "Note (optional)",
    StringKey.ADD_TXN_NOTE_PLACEHOLDER to "Add a note",
    StringKey.ADD_TXN_SAVE_NEW to "Save transaction",
    StringKey.ADD_TXN_SAVE_EDIT to "Save changes",
    StringKey.ADD_TXN_ERROR_AMOUNT to "Enter a valid amount.",
    StringKey.ADD_TXN_ERROR_DESCRIPTION to "Enter a description.",
    StringKey.ADD_TXN_SELECT_CATEGORY_TITLE to "Choose a category",
    StringKey.ADD_TXN_CHANGE_CATEGORY_CD to "Change category",

    StringKey.ADD_ACTION_MANUAL_TITLE to "Add manually",
    StringKey.ADD_ACTION_MANUAL_SUBTITLE to "Record an expense or income",
    StringKey.ADD_ACTION_SCAN_TITLE to "Scan barcode",
    StringKey.ADD_ACTION_SCAN_SUBTITLE to "Record a purchase instantly",

    StringKey.PROFILE_DEMO_ACCOUNT to "Demo account",
    StringKey.PROFILE_TRANSACTIONS to "Transactions",
    StringKey.PROFILE_BUDGETS to "Budgets",
    StringKey.PROFILE_AVAILABLE to "Available",
    StringKey.PROFILE_ACCOUNT_SECURITY to "ACCOUNT & SECURITY",
    StringKey.PROFILE_EDIT_PROFILE to "Edit profile",
    StringKey.PROFILE_CHANGE_PASSWORD to "Change password",
    StringKey.PROFILE_TWO_FACTOR to "Two-factor authentication",
    StringKey.PROFILE_PREFERENCES to "PREFERENCES",
    StringKey.PROFILE_PRIVACY to "Privacy & security",
    StringKey.PROFILE_LOGOUT to "Log out",

    StringKey.CATEGORY_FOOD to "Food",
    StringKey.CATEGORY_TRANSPORTATION to "Transportation",
    StringKey.CATEGORY_SHOPPING to "Shopping",
    StringKey.CATEGORY_HEALTH to "Health",
    StringKey.CATEGORY_EDUCATION to "Education",
    StringKey.CATEGORY_ENTERTAINMENT to "Entertainment",
    StringKey.CATEGORY_BILLS to "Bills",
    StringKey.CATEGORY_SUBSCRIPTIONS to "Subscriptions",
    StringKey.CATEGORY_SALARY to "Salary",
    StringKey.CATEGORY_FREELANCE to "Freelance",
    StringKey.CATEGORY_OTHER to "Other",

    StringKey.PAYMENT_CASH to "Cash",
    StringKey.PAYMENT_DEBIT_CARD to "Debit card",
    StringKey.PAYMENT_CREDIT_CARD to "Credit card",
    StringKey.PAYMENT_BANK_TRANSFER to "Bank transfer",
    StringKey.PAYMENT_NEQUI to "Nequi",
    StringKey.PAYMENT_DAVIPLATA to "Daviplata",

    StringKey.COMMON_CANCEL to "Cancel",
    StringKey.COMMON_SAVE to "Save",
    StringKey.COMMON_BACK to "Back",

    StringKey.SCANNER_TITLE to "Scan barcode",
    StringKey.SCANNER_CLOSE_CD to "Close",
    StringKey.SCANNER_PERMISSION_MESSAGE to "S2 Nova needs camera access to scan barcodes.",
    StringKey.SCANNER_PERMISSION_BUTTON to "Allow camera access",
    StringKey.SCANNER_NOT_FOUND to "We couldn't find that product.",
    StringKey.SCANNER_TRY_AGAIN to "Try again",
    StringKey.SCANNER_HINT to "Position the barcode inside the frame",
    StringKey.SCANNER_MANUAL_PLACEHOLDER to "Or enter the code manually",
    StringKey.SCANNER_DISCARD to "Discard",
    StringKey.SCANNER_CONFIRM_PURCHASE to "Record purchase",
    StringKey.SCANNER_NOTIF_TITLE to "Purchase recorded",
    StringKey.SCANNER_NOTIF_MESSAGE_PREFIX to "Registered \"",
    StringKey.SCANNER_NOTIF_MESSAGE_MIDDLE to "\" — ",

    StringKey.HOME_GREETING to "HELLO",
    StringKey.HOME_BALANCE to "CURRENT BALANCE",
    StringKey.HOME_INCOME to "Income",
    StringKey.HOME_EXPENSES to "Expenses",
    StringKey.HOME_SAVINGS to "Savings",
    StringKey.HOME_EXPENSE_SUMMARY to "Expense summary",
    StringKey.HOME_NO_EXPENSES to "No expenses this month.",
    StringKey.HOME_RECENT_TXNS to "Recent transactions",
    StringKey.HOME_SEE_ALL to "See all",
    StringKey.HOME_UPCOMING_PAYMENTS to "Upcoming payments",
    StringKey.HOME_WALLET_COUNT_SUFFIX to "wallets",

    StringKey.NOTIF_MARK_ALL_READ to "Mark all as read",
    StringKey.NOTIF_EMPTY to "You have no notifications.",

    StringKey.REPORTS_RANGE_3M to "3M",
    StringKey.REPORTS_RANGE_6M to "6M",
    StringKey.REPORTS_RANGE_12M to "12M",
    StringKey.REPORTS_SAVINGS_RATE to "Savings rate",
    StringKey.REPORTS_PERIOD_TOTALS to "Period totals",
    StringKey.REPORTS_INCOME_VS_EXPENSES to "Income vs expenses",
    StringKey.REPORTS_SPEND_BY_CATEGORY to "Spend by category",

    StringKey.TXN_LIST_SEARCH_PLACEHOLDER to "Search by description or merchant",
    StringKey.TXN_LIST_FILTER_ALL to "All",
    StringKey.TXN_LIST_FILTER_PENDING to "Pending",
    StringKey.TXN_LIST_EMPTY_TITLE to "No results",
    StringKey.TXN_LIST_EMPTY_SUBTITLE to "Adjust your search or filters.",

    StringKey.TXN_DETAIL_TITLE to "Transaction detail",
    StringKey.TXN_DETAIL_EDIT_CD to "Edit",
    StringKey.TXN_DETAIL_NOT_FOUND to "This transaction no longer exists.",
    StringKey.TXN_DETAIL_DATE to "Date",
    StringKey.TXN_DETAIL_MERCHANT to "Merchant",
    StringKey.TXN_DETAIL_NOTE to "Note",
    StringKey.TXN_DETAIL_DELETE to "Delete transaction",
    StringKey.TXN_DETAIL_DELETE_DIALOG_TITLE to "Delete transaction",
    StringKey.TXN_DETAIL_DELETE_CONFIRM_PREFIX to "Are you sure you want to delete",
    StringKey.TXN_DETAIL_DELETE_CONFIRM_SUFFIX to "? This action cannot be undone.",
    StringKey.TXN_DETAIL_DELETE_CONFIRM to "Delete",

    StringKey.BUDGETS_MONTH_LABEL to "THIS MONTH'S BUDGET",
    StringKey.BUDGETS_UTILIZED to "used",
    StringKey.BUDGETS_NEW to "New budget",
    StringKey.BUDGETS_MONTHLY_LIMIT to "Monthly limit",
    StringKey.BUDGETS_EDIT_TITLE_PREFIX to "Edit budget for",
    StringKey.BUDGETS_CREATE to "Create",
    StringKey.BUDGETS_OF to "of",
    StringKey.BUDGETS_REMAINING to "remaining",
    StringKey.BUDGETS_OVER_LIMIT to "over the limit",
    StringKey.BUDGET_STATUS_OVER to "Over budget",
    StringKey.BUDGET_STATUS_NEAR to "Near limit",
    StringKey.BUDGET_STATUS_ON_TRACK to "On track",
    StringKey.BUDGETS_NAME_OPTIONAL to "Name (optional)",
    StringKey.BUDGETS_NAME_PLACEHOLDER to "E.g. Vacation",

    StringKey.ADD_TXN_TRANSFER to "Transfer",
    StringKey.ADD_TXN_TRANSFER_TO to "Transfer to",
    StringKey.ADD_TXN_WALLET to "Wallet",
    StringKey.ADD_TXN_MORE_OPTIONS to "More options",
    StringKey.ADD_TXN_BUDGET to "Budget (optional)",
    StringKey.ADD_TXN_GOAL to "Goal (optional)",
    StringKey.ADD_TXN_NONE to "None",
    StringKey.ADD_TXN_UPCOMING to "Upcoming",
    StringKey.ADD_TXN_UPCOMING_HINT to "Hasn't happened yet — won't affect your balance yet.",
    StringKey.ADD_TXN_RECURRING_HINT to "Is this a recurring payment or income? Manage it under Recurring →",
    StringKey.ADD_TXN_LENT to "This is money I lent",
    StringKey.ADD_TXN_BORROWED to "This is money I borrowed",
    StringKey.ADD_TXN_LOAN_HINT to "Tracked as outstanding until you settle it.",
    StringKey.ADD_TXN_COUNTERPARTY to "Person",
    StringKey.ADD_TXN_COUNTERPARTY_PLACEHOLDER to "Who to / from?",
    StringKey.ADD_TXN_DUE_DATE to "Due date (optional)",
    StringKey.ADD_TXN_ERROR_WALLET to "Select a wallet.",
    StringKey.ADD_TXN_ERROR_TRANSFER_WALLET to "Select the destination wallet.",
    StringKey.ADD_TXN_NO_WALLET_TITLE to "No wallets yet",
    StringKey.ADD_TXN_NO_WALLET_SUBTITLE to "Create a wallet (cash, bank, savings...) before recording transactions.",
    StringKey.ADD_TXN_NO_WALLET_CTA to "Create wallet",
    StringKey.RECURRENCE_WEEKLY to "Weekly",
    StringKey.RECURRENCE_MONTHLY to "Monthly",
    StringKey.RECURRENCE_YEARLY to "Yearly",

    StringKey.WALLETS_TITLE to "My wallets",
    StringKey.WALLETS_NEW to "New wallet",
    StringKey.WALLETS_NAME to "Name",
    StringKey.WALLETS_TYPE to "Type",
    StringKey.WALLETS_INITIAL_BALANCE to "Initial balance",
    StringKey.WALLETS_CREATE to "Create",
    StringKey.WALLETS_EMPTY_TITLE to "No wallets yet",
    StringKey.WALLETS_EMPTY_SUBTITLE to "Create your first wallet to start recording transactions.",
    StringKey.WALLETS_FOOTER_NOTE to "Home's total balance is the sum of these wallets.",
    StringKey.WALLET_TYPE_CASH to "Cash",
    StringKey.WALLET_TYPE_BANK_DEBIT to "Debit account",
    StringKey.WALLET_TYPE_BANK_CREDIT to "Credit card",
    StringKey.WALLET_TYPE_SAVINGS to "Savings",
    StringKey.WALLET_TYPE_CRYPTO to "Bitcoin/Crypto",
    StringKey.WALLET_TYPE_NEQUI to "Nequi",
    StringKey.WALLET_TYPE_DAVIPLATA to "Daviplata",
    StringKey.WALLET_TYPE_OTHER to "Other",

    StringKey.GOALS_TITLE to "Goals",
    StringKey.GOALS_NEW to "New goal",
    StringKey.GOALS_EMPTY to "No goals yet. Create one like \"Car Payment\".",
    StringKey.GOALS_NAME to "Name",
    StringKey.GOALS_NAME_PLACEHOLDER to "E.g. Car Payment",
    StringKey.GOALS_TARGET_AMOUNT to "Target amount",
    StringKey.GOALS_CREATE to "Create",
    StringKey.GOALS_CONTRIBUTE to "Contribute",

    StringKey.GOAL_CONTRIBUTION_TITLE to "Contribute to goal",
    StringKey.GOAL_CONTRIBUTION_AMOUNT to "Amount to add",
    StringKey.GOAL_CONTRIBUTION_WALLET to "From",
    StringKey.GOAL_CONTRIBUTION_SAVE to "Contribute",
    StringKey.GOAL_CONTRIBUTION_SAVED to "Contribution added",
    StringKey.GOAL_CONTRIBUTION_DESCRIPTION_PREFIX to "Contribution to ",
    StringKey.GOAL_CONTRIBUTION_ERROR_AMOUNT to "Enter a valid amount.",
    StringKey.GOAL_CONTRIBUTION_ERROR_WALLET to "Choose a source wallet.",

    StringKey.COMMON_UNDO to "Undo",

    StringKey.RECURRING_TITLE to "Recurring",
    StringKey.RECURRING_NEW to "New recurring",
    StringKey.RECURRING_EMPTY to "No recurring payments or income yet.",
    StringKey.RECURRING_NAME to "Name",
    StringKey.RECURRING_NAME_PLACEHOLDER to "E.g. Netflix, Salary, Rent",
    StringKey.RECURRING_AMOUNT to "Amount",
    StringKey.RECURRING_TYPE to "Type",
    StringKey.RECURRING_INTERVAL to "Frequency",
    StringKey.RECURRING_START_DATE to "First date",
    StringKey.RECURRING_CREATE to "Create",
    StringKey.RECURRING_DUE_TODAY to "Due today",
    StringKey.RECURRING_NEXT_DUE to "Next",
    StringKey.RECURRING_CONFIRM to "Confirm",
    StringKey.RECURRING_CONFIRMED_TOAST to "Transaction recorded",
    StringKey.RECURRING_PAUSE to "Pause",
    StringKey.RECURRING_RESUME to "Resume",
    StringKey.RECURRING_PAUSED to "Paused",

    StringKey.LOANS_TITLE to "Loans",
    StringKey.LOANS_EMPTY to "No lent or borrowed money on record.",
    StringKey.LOANS_LENT_TAB to "Lent",
    StringKey.LOANS_BORROWED_TAB to "Borrowed",
    StringKey.LOANS_SETTLE to "Mark as settled",
    StringKey.LOANS_SETTLED to "Settled",
    StringKey.LOANS_SETTLED_TOAST to "Loan settled",
    StringKey.LOANS_DUE to "Due",
    StringKey.LOANS_NO_DUE_DATE to "No due date",

    StringKey.SETTINGS_REPLAY_TUTORIAL to "Watch the tutorial again",

    StringKey.ONBOARDING_SKIP to "Skip",
    StringKey.ONBOARDING_BACK to "Back",
    StringKey.ONBOARDING_NEXT to "Next",
    StringKey.ONBOARDING_FINISH to "Get started",
    StringKey.ONBOARDING_WELCOME_TITLE to "Welcome to S2 Nova",
    StringKey.ONBOARDING_WELCOME_SUBTITLE to "Your money, under control, in a couple of taps.",
    StringKey.ONBOARDING_GET_STARTED to "Get started",
    StringKey.ONBOARDING_WELCOME_POINT_TRACK to "Track income and expenses instantly",
    StringKey.ONBOARDING_WELCOME_POINT_SCAN to "Scan products to register purchases",
    StringKey.ONBOARDING_WELCOME_POINT_ANALYZE to "Understand your habits from the web dashboard",
    StringKey.ONBOARDING_INCOME_TITLE to "How much do you earn a month?",
    StringKey.ONBOARDING_INCOME_SUBTITLE to "Optional — helps us suggest a budget. You can skip this step.",
    StringKey.ONBOARDING_INCOME_LABEL to "Approximate monthly income",
    StringKey.ONBOARDING_WALLET_TITLE to "Create your first wallet",
    StringKey.ONBOARDING_WALLET_SUBTITLE to "This is where the money you record goes. You can add more later.",
    StringKey.ONBOARDING_WALLET_NAME_PLACEHOLDER to "E.g. Cash, Checking...",
    StringKey.ONBOARDING_BUDGET_TITLE to "A budget suggestion",
    StringKey.ONBOARDING_BUDGET_SUBTITLE to "Based on the 50/30/20 rule — just a suggestion, you decide.",
    StringKey.ONBOARDING_BUDGET_NO_INCOME to "Without an income on record we can't compute a suggestion — you can create budgets manually later.",
    StringKey.ONBOARDING_BUDGET_NEEDS to "Needs",
    StringKey.ONBOARDING_BUDGET_WANTS to "Wants",
    StringKey.ONBOARDING_BUDGET_SAVINGS to "Savings",
    StringKey.ONBOARDING_BUDGET_ACCEPT to "Accept suggestion",
    StringKey.ONBOARDING_TUTORIAL_TRACK_TITLE to "Track your money",
    StringKey.ONBOARDING_TUTORIAL_TRACK_BODY to "Record income, expenses, and transfers between your wallets in seconds.",
    StringKey.ONBOARDING_TUTORIAL_SCAN_TITLE to "Scan your purchases",
    StringKey.ONBOARDING_TUTORIAL_SCAN_BODY to "Use the camera to scan a product and register the purchase instantly.",
    StringKey.ONBOARDING_TUTORIAL_ORGANIZE_TITLE to "Organize your finances",
    StringKey.ONBOARDING_TUTORIAL_ORGANIZE_BODY to "Create wallets, budgets, and goals to keep everything in order.",
    StringKey.ONBOARDING_TUTORIAL_ANALYZE_TITLE to "Understand your finances",
    StringKey.ONBOARDING_TUTORIAL_ANALYZE_BODY to "The web dashboard shows you charts, trends, and detailed reports.",
    StringKey.ONBOARDING_TUTORIAL_READY_TITLE to "You're ready!",
    StringKey.ONBOARDING_TUTORIAL_READY_BODY to "You can now start using S2 Nova.",
)

fun stringFor(key: StringKey, language: AppLanguage): String =
    (if (language == AppLanguage.EN) EN else ES).getValue(key)

// Maps mock-data ids to their StringKey so every screen that shows a
// category/payment-method name goes through the same translated lookup
// instead of reading the (Spanish-only) `label` field on the mock data
// directly.
fun categoryStringKey(id: CategoryId): StringKey = when (id) {
    CategoryId.FOOD -> StringKey.CATEGORY_FOOD
    CategoryId.TRANSPORTATION -> StringKey.CATEGORY_TRANSPORTATION
    CategoryId.SHOPPING -> StringKey.CATEGORY_SHOPPING
    CategoryId.HEALTH -> StringKey.CATEGORY_HEALTH
    CategoryId.EDUCATION -> StringKey.CATEGORY_EDUCATION
    CategoryId.ENTERTAINMENT -> StringKey.CATEGORY_ENTERTAINMENT
    CategoryId.BILLS -> StringKey.CATEGORY_BILLS
    CategoryId.SUBSCRIPTIONS -> StringKey.CATEGORY_SUBSCRIPTIONS
    CategoryId.SALARY -> StringKey.CATEGORY_SALARY
    CategoryId.FREELANCE -> StringKey.CATEGORY_FREELANCE
    CategoryId.OTHER -> StringKey.CATEGORY_OTHER
}

fun paymentMethodStringKey(id: PaymentMethod): StringKey = when (id) {
    PaymentMethod.CASH -> StringKey.PAYMENT_CASH
    PaymentMethod.DEBIT_CARD -> StringKey.PAYMENT_DEBIT_CARD
    PaymentMethod.CREDIT_CARD -> StringKey.PAYMENT_CREDIT_CARD
    PaymentMethod.BANK_TRANSFER -> StringKey.PAYMENT_BANK_TRANSFER
    PaymentMethod.NEQUI -> StringKey.PAYMENT_NEQUI
    PaymentMethod.DAVIPLATA -> StringKey.PAYMENT_DAVIPLATA
}

fun budgetStatusStringKey(status: com.s2nova.app.data.model.BudgetStatus): StringKey = when (status) {
    com.s2nova.app.data.model.BudgetStatus.OVER_BUDGET -> StringKey.BUDGET_STATUS_OVER
    com.s2nova.app.data.model.BudgetStatus.NEAR_LIMIT -> StringKey.BUDGET_STATUS_NEAR
    com.s2nova.app.data.model.BudgetStatus.ON_TRACK -> StringKey.BUDGET_STATUS_ON_TRACK
}

@Composable
fun rememberStrings(): (StringKey) -> String {
    val user by AppContainer.authRepository.currentUser.collectAsStateWithLifecycle()
    val language = user?.preferences?.language ?: AppLanguage.ES
    return { key -> stringFor(key, language) }
}
