package com.s2nova.app.ui

import android.content.Context
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.s2nova.app.data.model.AppLanguage
import com.s2nova.app.data.model.PaymentMethod

// The app's copy in Spanish and English, same approach as web's
// src/lib/i18n/translations.ts. Templates use String.format ("%1$s").
// Composables read it with rememberStrings(); code outside them with tr().
// Category names come from the taxonomy (nameEn), not from here.
enum class StringKey {
    NAV_HOME, NAV_REPORTS, NAV_PLANS, NAV_ADD, TITLE_TRANSACTIONS,
    TITLE_REPORTS, TITLE_BUDGETS, TITLE_SETTINGS, TITLE_PROFILE, SETTINGS_PERSONAL_INFO,
    SETTINGS_FULL_NAME, SETTINGS_EMAIL, SETTINGS_SAVE_CHANGES, SETTINGS_PREFERENCES, SETTINGS_DARK_MODE,
    SETTINGS_NOTIFICATIONS, SETTINGS_BIOMETRIC, SETTINGS_LANGUAGE, SETTINGS_ABOUT, SETTINGS_PHONE,
    SETTINGS_CITY, SETTINGS_PRIVACY_SESSION, SETTINGS_BLUR_BALANCE, SETTINGS_BLUR_BALANCE_HELP_ON, SETTINGS_BLUR_BALANCE_HELP_OFF,
    SETTINGS_AUTO_LOCK, SETTINGS_AUTO_LOCK_NEVER, SETTINGS_AUTO_LOCK_HELP_NEVER, HOME_BALANCE_TAP_TO_REVEAL, HOME_GREETING_MORNING,
    HOME_GREETING_AFTERNOON, HOME_GREETING_EVENING, ADD_TXN_PAYMENT_METHOD, ADD_ACTION_MANUAL_TITLE, ADD_ACTION_MANUAL_SUBTITLE,
    ADD_ACTION_SCAN_TITLE, ADD_ACTION_SCAN_SUBTITLE, PROFILE_LOGOUT, PROFILE_MEMBER_SINCE, PROFILE_WALLETS_DETAIL,
    PROFILE_RECURRING_DETAIL, PROFILE_RECURRING_DETAIL_EMPTY, PROFILE_SETTINGS_DETAIL, PAYMENT_CASH, PAYMENT_DEBIT_CARD,
    PAYMENT_CREDIT_CARD, PAYMENT_BANK_TRANSFER, PAYMENT_NEQUI, PAYMENT_DAVIPLATA, COMMON_CANCEL,
    COMMON_SAVE, COMMON_BACK, COMMON_DELETE, SCANNER_TITLE, SCANNER_CLOSE_CD,
    SCANNER_PERMISSION_MESSAGE, SCANNER_PERMISSION_BUTTON, SCANNER_NOT_FOUND, SCANNER_TRY_AGAIN, SCANNER_HINT,
    SCANNER_MANUAL_PLACEHOLDER, SCANNER_DISCARD, SCANNER_CONFIRM_PURCHASE, SCANNER_NOTIF_TITLE, SCANNER_NOTIF_MESSAGE_PREFIX,
    SCANNER_NOTIF_MESSAGE_MIDDLE, HOME_BALANCE, HOME_INCOME, HOME_EXPENSES, HOME_SAVINGS,
    HOME_RECENT_TXNS, HOME_SEE_ALL, NOTIF_MARK_ALL_READ, NOTIF_EMPTY, NOTIF_UNREAD_SUFFIX,
    NOTIF_ALL_CAUGHT_UP, REPORTS_RANGE_3M, REPORTS_RANGE_6M, REPORTS_RANGE_12M, REPORTS_SUBTITLE_3M,
    REPORTS_SUBTITLE_6M, REPORTS_SUBTITLE_12M, REPORTS_SAVINGS_RATE, REPORTS_PERIOD_TOTALS, REPORTS_INCOME_VS_EXPENSES,
    REPORTS_RANGE, REPORTS_SUMMARY_FLOW, REPORTS_TAP_MONTH, REPORTS_VS_PREVIOUS,
    REPORTS_SPEND_BY_CATEGORY, TXN_LIST_FILTER_ALL, TXN_LIST_FILTER_PENDING, TXN_LIST_TODAY, TXN_LIST_YESTERDAY,
    BUDGETS_NEW, BUDGETS_SPENT_LABEL, BUDGETS_LIMIT_TOTAL, BUDGETS_DAYS_LEFT_NOTE, BUDGETS_LAST_DAY_NOTE, PLAN_STATE_A11Y, BUDGET_STATUS_OVER,
    BUDGET_STATUS_NEAR, BUDGET_STATUS_ON_TRACK, BUDGETS_EMPTY, COMMON_SAVE_ERROR, ADD_TXN_NO_WALLET_SUBTITLE,
    RECURRENCE_WEEKLY, RECURRENCE_MONTHLY, RECURRENCE_YEARLY, WALLETS_TITLE, GOALS_TITLE,
    GOALS_NEW, GOALS_EMPTY, GOALS_NOTE_NONE, GOALS_NOTE_DONE, GOALS_NOTE_LEFT,
    GOAL_PAY_NOTE, GOALS_DELETE_NAMED, GOALS_DELETE_HAS_BALANCE, GOALS_DELETE_ORIGIN, GOALS_DELETE_NO_ORIGIN,
    GOALS_DELETE_ALL_TO, GOALS_DELETE_ONE_MOVE, GOALS_DELETE_AND_RETURN, GOALS_EDIT_TITLE, GOALS_DELETE,
    GOALS_DELETE_CONFIRM_BODY, GOALS_DELETE_ERROR, GOAL_CONTRIBUTION_TITLE, GOAL_CONTRIBUTION_AMOUNT, GOAL_CONTRIBUTION_WALLET,
    GOAL_CONTRIBUTION_SAVE, GOAL_CONTRIBUTION_SAVED, GOAL_CONTRIBUTION_DESCRIPTION_PREFIX, COMMON_UNDO, COMMON_SESSION_EXPIRED,
    COMMON_SESSION_IDLE, RECURRING_TITLE, RECURRING_NEW, RECURRING_EMPTY, RECURRING_DUE_TODAY,
    RECURRING_NEXT_DUE, RECURRING_CONFIRM, RECURRING_SKIP, RECURRING_OVERDUE, RECURRING_OVERDUE_SINCE,
    RECURRING_PAUSE, RECURRING_RESUME, RECURRING_PAUSED, RECURRING_EDIT, RECURRING_DELETE,
    RECURRING_DELETE_CONFIRM_TITLE, RECURRING_DELETE_CONFIRM_BODY, LOANS_LENT_TAB, LOANS_BORROWED_TAB, LOANS_SETTLED,
    LOANS_DUE, LOANS_NO_DUE_DATE, LOANS_SUMMARY_LENT, LOANS_SUMMARY_BORROWED, LOANS_RECORD_ONE,
    LOANS_RECORD_MANY, LOANS_SETTLED_WORD_ONE, LOANS_SETTLED_WORD_MANY, LOANS_NEW_LENT, LOANS_NEW_BORROWED,
    LOANS_REGISTER_PAYMENT, LOANS_SETTLE_ALL_SHORTCUT, LOANS_PAYMENT_WALLET_LENT, LOANS_PAYMENT_WALLET_BORROWED, LOANS_FORM_COUNTERPARTY_PLACEHOLDER,
    LOANS_FORM_AMOUNT, LOANS_EDIT_TITLE, LOANS_DELETE, LOANS_DELETE_CONFIRM_TITLE, LOANS_DELETE_CONFIRM_BODY,
    LOANS_FORM_PERSON_LENT, LOANS_FORM_PERSON_BORROWED, LOANS_FORM_WALLET_LENT, LOANS_FORM_WALLET_BORROWED, LOANS_EDIT_ACTION,
    DATE_PICKER_TODAY, DATE_PICKER_NO_DATE, DATE_PICKER_USE_DATE, DATE_PICKER_CHOOSE, PLANS_TAB,
    TITLE_PLANS, LOANS_EMPTY_LENT, LOANS_EMPTY_BORROWED, LOANS_DIRECTION, LOANS_DUE_OPTIONAL,
    LOANS_NO_DATE, LOANS_PAY_TITLE_LENT, LOANS_PAY_TITLE_BORROWED, LOANS_PAY_NOTE, LOANS_SETTLED_NOTE,
    LOANS_PAID_NOTE, SETTINGS_LOCK_1_MINUTE, SETTINGS_LOCK_MINUTES, SETTINGS_LOCK_1_HOUR, SETTINGS_AUTO_LOCK_HELP_PASSWORD_AFTER,
    SETTINGS_AUTO_LOCK_HELP_BIOMETRIC_AFTER, NAV_TRANSACTIONS, HOME_MONTH_INCOME, HOME_MONTH_EXPENSES, HOME_WALLET_ONE,
    HOME_WALLET_MANY, HOME_ADD_FIRST_WALLET, HOME_UPCOMING_7_DAYS, HOME_UPCOMING_LINK, HOME_UPCOMING_EMPTY,
    HOME_UPCOMING_TODAY, HOME_UPCOMING_DUE_TODAY, HOME_UPCOMING_SCHEDULED, HOME_SYNC_ERROR, COMMON_RETRY,
    HOME_ALERT_REVIEW, HOME_NEXT_PAYMENT, HOME_UPCOMING_MORE, HOME_VS, HOME_STAT_MORE, HOME_STAT_LESS, HOME_FAVORABLE, HOME_UNFAVORABLE, HOME_THIS_MONTH, HOME_SHOW_AMOUNTS, HOME_HIDE_AMOUNTS, HOME_BUDGETS_NONE,
    COMMON_DISMISS, AMOUNT_HIDDEN, ALERT_SERIES_DUE_TITLE, ALERT_SERIES_OVERDUE_TITLE, ALERT_SERIES_BODY,
    ALERT_LOAN_LENT_TITLE, ALERT_LOAN_BORROWED_TITLE, ALERT_LOAN_BODY, ALERT_BUDGET_TITLE, ALERT_BUDGET_BODY,
    ALERT_GOAL_TITLE, ALERT_GOAL_BODY, NM_FREQ_DAILY, NM_FREQ_WEEKLY, NM_FREQ_MONTHLY,
    NM_FREQ_YEARLY, NM_EVERY_DAILY, NM_EVERY_WEEKLY, NM_EVERY_MONTHLY, NM_EVERY_YEARLY,
    NM_NO_REPEAT, NM_REPEAT, NM_REPEAT_COUNT, NM_REPEAT_UNTIL, NM_REPEAT_NEVER,
    NM_SERIES_PAUSED, NM_SERIES_SAVED, NM_SERIES_ERR, NM_TOAST_SCHEDULED, NM_TOAST_SAVED,
    NM_ERR_SAVE, NM_EDIT_SERIES, NM_EDIT, NM_TITLE, NM_WALLET_IN,
    NM_WALLET_FROM, NM_WALLET, NM_WALLET_TO, NM_BUDGET_ADDS, NM_BUDGET_ADDS_TWO,
    NM_BUDGET_BY_CATEGORY, NM_BUDGET_CUSTOM, NM_BUDGET_WHEN_RECORDED, NM_BUDGET_WITH_THIS, NM_TITLE_PH,
    NM_NOTE_PH, NM_PHOTO, NM_DOCUMENT, NM_AUTOMATIC, NM_WITH_CONFIRMATION,
    NM_SAVE_SERIES, NM_SAVE_SCHEDULED, NM_SAVE_REPEAT, NM_SAVE, COMMON_DELETE_ERROR,
    NM_TYPE_EXPENSE, NM_TYPE_INCOME, NM_TYPE_TRANSFER, NM_CATEGORY, NM_TRANSFER_BETWEEN,
    NM_PICK_CATEGORY, NM_FX_APPROX, NM_FX_LATER, NM_SCHEDULED_CHIP, NM_NOW,
    NM_TODAY_AT, NM_ONE_ATTACHMENT, NM_ATTACH, NM_FROM, NM_BUDGET,
    NM_MORE, NM_NO_WALLET_TITLE, NM_NO_WALLET_BODY, NM_NO_WALLET_CTA, NM_SECTION_CURRENCY,
    NM_CURRENCY_HINT, NM_CURRENCY_OF, NM_MANAGE_CURRENCIES, NM_DONE, NM_SECTION_BPICK,
    NM_BPICK_AUTO, NM_BPICK_NONE, NM_NONE_M, NM_NONE_F, NM_BPICK_NONE_DETAIL,
    NM_MORE_OPTIONS, NM_TITLE_EXAMPLE, NM_NOTE_LABEL, NM_LOAN, NM_EXPANDED, NM_COLLAPSED, NM_OPTIONAL,
    NM_X_OF_Y, NM_SECTION_MORE, NM_LOAN_BORROWED, NM_LOAN_LENT, NM_LOAN_DETAIL,
    NM_GOAL, NM_CAT_INCOME, NM_CAT_EXPENSE, NM_CAT_STEP, NM_MANAGE_CATEGORIES,
    NM_SUBCATEGORY, NM_CHANGE_CATEGORY, NM_AMOUNT, NM_SECTION_WHEN, NM_YESTERDAY,
    NM_DAY_BEFORE, NM_LIKE_LAST, NM_FUTURE, NM_TOMORROW, NM_IN_A_WEEK,
    NM_TIME, NM_WHEN_FUTURE, NM_WHEN_PAST, NM_WHEN_TODAY, NM_ENDS,
    NM_ENDS_COUNT, NM_ENDS_UNTIL, NM_ENDS_NEVER, NM_TIME_1, NM_TIMES_N,
    NM_STARTS_TODAY, NM_STARTS_ON, NM_CHANGE, NM_EACH_DATE, NM_ASK,
    NM_ASK_DETAIL, NM_AUTO, NM_AUTO_DETAIL, NM_APPLY, NM_RECEIPT_FILE,
    NM_RECEIPT_PHOTO_FILE, NM_ERR_FILE_SIZE, NM_SECTION_ATTACH, NM_ATTACH_HINT, NM_ATTACH_CAMERA,
    NM_ATTACH_CAMERA_DETAIL, NM_ATTACH_GALLERY, NM_ATTACH_GALLERY_DETAIL, NM_ATTACH_DOC, NM_ATTACH_DOC_DETAIL,
    NM_SECTION_FROM, NM_FROM_HINT, NM_FROM_PH, NM_FROM_KIND, NM_FROM_EMPLOYER,
    NM_FROM_CLIENT, NM_FROM_FAMILY, NM_FROM_FRIEND, NM_FROM_OTHER, NM_RECENTS,
    NM_REMOVE_FROM, NM_KEYPAD, NM_CALCULATOR, COMMON_CLOSE, GOAL_EDIT,
    GOAL_NEW, PLAN_NAME, GOAL_NAME_PH, PLAN_ICON_GUESS, GOAL_ICON_PICK,
    PLAN_ICON, GOAL_TARGET, GOAL_INITIAL, GOAL_DATE, GOAL_PLAN,
    GOAL_PLAN_EMPTY, GOAL_DELETE, GOAL_SUM_GOAL, GOAL_SUM_COUNT, GOAL_SUM_DATE,
    GOAL_PLAN_AMOUNT, GOAL_FREQ, GOAL_FROM_WALLET, GOAL_STARTS, GOAL_ENDS_GOAL,
    GOAL_N_CONTRIBUTIONS, GOAL_ASK_DETAIL, GOAL_AUTO, GOAL_AUTO_DETAIL, GOAL_PLAN_REMOVE,
    GOAL_SAVED_NEXT, GOAL_DELETE_TITLE, GOAL_DELETE_SAVED, GOAL_DELETE_PLAN, GOAL_DELETE_NEXT,
    GOAL_TARGET_ON, GOAL_NO_TARGET, GOAL_OF, GOAL_NO_PAYMENTS, GOAL_MET,
    GOAL_LEFT, GOAL_NEXT, GOAL_PAY, GOAL_PLAN_TEXT_DAILY, GOAL_PLAN_TEXT_WEEKLY,
    GOAL_PLAN_TEXT_MONTHLY, GOAL_PAY_AMOUNT, BUD_EDIT, BUD_NEW, BUD_KIND_CATEGORY,
    BUD_KIND_CUSTOM, BUD_KIND_CUSTOM_HINT, BUD_KIND_CATEGORY_HINT, BUD_PH_CUSTOM, BUD_PH_CATEGORY,
    BUD_ICON_PICK, BUD_CAT_GUESS, BUD_CAT_AUTO, BUD_LIMIT, BUD_CATEGORY,
    BUD_WALLETS, BUD_N_WALLETS, BUD_RANGE, BUD_PERIOD, BUD_SCOPE_PICK,
    BUD_SCOPE_ONLY, BUD_SCOPE_ALL, BUD_SCOPE_FROM, BUD_SCOPE_ALL_WALLETS, BUD_SCOPE_NO_RESET,
    PLAN_STATE_NOT_STARTED, PLAN_STATE_OVER, PLAN_STATE_NEAR, PLAN_STATE_WATCH, PLAN_STATE_OK,
    BUD_SCOPE_RESET, BUD_DELETE, BUD_SUB_HINT, BUD_WALLETS_HINT, BUD_PERIOD_CUSTOM_HINT,
    BUD_PERIOD_MONTHLY_HINT, BUD_CAT_HINT, BUD_ICON_HINT, BUD_ALL, BUD_CUSTOM_RANGE,
    BUD_UNTIL, BUD_TAKEN, BUD_DELETE_TITLE, BUD_DELETE_SPENT, BUD_THIS_MONTH,
    BUD_DELETE_HISTORY, BUD_DELETE_KEEP, BUD_DELETE_ACK, BUD_SCOPE_CUSTOM, BUD_SCOPE_ONLY_WALLETS,
    MV_DELETED, MV_DELETE_TITLE, MV_DELETE_RECEIPT, MV_DELETE_REPEATS, MV_DELETE_BALANCE,
    MV_DELETE_ACK, MV_DELETE_ACK_RECEIPT, MV_DELETE, MV_TITLE, MV_EDIT,
    MV_GONE, MV_STATE_SCHEDULED, MV_STATE_RECORDED, MV_NOTE, MV_MERCHANT,
    MV_REPEATS, MV_RECEIPT, MV_RECEIPT_META, MV_RECEIPT_SEE, MV_RECEIPT_REPLACE,
    MV_RECEIPT_REMOVE, MV_RECEIPT_REMOVED, MV_RECEIPT_ATTACH, MV_RECEIPT_PREVIEW, MV_SHARE,
    MV_RECEIPT_DOWNLOAD, MV_RECEIPT_SAVED, MV_RECEIPT_LOADING, CAT_TITLE, CAT_TAB_EXPENSES,
    CAT_TAB_INCOME, CAT_SUBTITLE, CAT_SUB_ONE, CAT_SUB_MANY, CAT_HIDDEN,
    CAT_YOURS, CAT_ADD_SUB, CAT_EDIT_SUB, CAT_EDIT, CAT_NEW_SUB_IN,
    CAT_NEW, CAT_SUB_CUSTOM, CAT_SUB_BUILTIN, CAT_SUB_NEW_INCOME, CAT_SUB_NEW_EXPENSE,
    CAT_NAME_PH, CAT_INSIDE, CAT_NEW_MAIN, CAT_ICON_COLOR, CAT_PARENT_COLOR,
    CAT_SHOW, CAT_SHOW_HINT, CAT_SAVE, CAT_CREATE, CAT_ERR_NAME,
    CAT_ERR_TAKEN, LOAN_ERR_SAVE, CAT_DELETE_SUB, CAT_DELETE, CAT_SUB_OF,
    CAT_MAIN, CAT_AND_SUBS, CAT_MOVE_ONE, CAT_MOVE_MANY, CAT_DELETE_GONE,
    CAT_DELETE_ACK, WALLET_KIND_SAVINGS, WALLET_KIND_CHECKING, WALLET_KIND_CREDIT, WALLET_KIND_CASH,
    WALLET_TITLE, WALLET_EMPTY, WALLET_TOTAL, WALLET_SHARE, WALLET_TOTAL_LABEL, WALLET_TOTAL_NOTE, WALLET_EDIT, WALLET_NEW,
    WALLET_NAME_PH, WALLET_TYPE_GUESS, WALLET_TYPE_HINT, WALLET_TYPE, WALLET_CURRENCY,
    WALLET_CURRENCY_HINT, WALLET_BALANCE, WALLET_INITIAL, WALLET_ERR_SAVE, WALLET_DELETE,
    WALLET_LAST, WALLET_DELETE_TITLE, WALLET_DELETE_BALANCE, WALLET_DELETE_ONE, WALLET_DELETE_MANY,
    WALLET_DELETE_TOTAL, WALLET_DELETE_ACK, CONFIRM_WILL_DELETE, CONFIRM_CONTINUE, CONFIRM_CANT_UNDO,
    COMMON_BACK_TO, GUIDE_LABEL, GUIDE_SKIP, GUIDE_OK, GUIDE_INICIO_LABEL,
    GUIDE_INICIO_TITLE, GUIDE_INICIO_BODY, GUIDE_MOVIMIENTOS_LABEL, GUIDE_MOVIMIENTOS_TITLE, GUIDE_MOVIMIENTOS_BODY,
    GUIDE_PLANES_LABEL, GUIDE_PLANES_TITLE, GUIDE_PLANES_BODY, GUIDE_REPORTES_LABEL, GUIDE_REPORTES_TITLE,
    GUIDE_REPORTES_BODY, GUIDE_BILLETERAS_LABEL, GUIDE_BILLETERAS_TITLE, GUIDE_BILLETERAS_BODY, CUR_TITLE,
    CUR_PRINCIPAL, CUR_PRINCIPAL_BADGE, CUR_DETECTED, CUR_OTHERS, CUR_ONLY_PRINCIPAL,
    CUR_WALLET_ONE, CUR_WALLET_MANY, CUR_NO_WALLETS, CUR_REMOVE_TITLE, CUR_REMOVE_GONE,
    CUR_REMOVE_KEEP, CUR_REMOVE_ACK, CUR_REMOVE, CUR_ADD, CUR_RATES_NOTE,
    CUR_ADD_HINT, CUR_ADDED, FIRST_STEP, FIRST_WALLET_TITLE, FIRST_CURRENCY_TITLE,
    FIRST_WALLET_BODY, FIRST_CURRENCY_BODY, FIRST_DETECTED, FIRST_NAME_PH, FIRST_OTHER_CURRENCIES,
    FIRST_CREATE, FIRST_ERR, AUTH_LOGIN_TITLE, AUTH_LOGIN_SUB, AUTH_EMAIL,
    AUTH_PASSWORD, AUTH_NAME, AUTH_FORGOT, AUTH_ENTER, AUTH_BAD_CREDENTIALS,
    AUTH_GOOGLE_ERR, AUTH_GUEST, AUTH_GUEST_HINT, AUTH_NEW_HERE, AUTH_CREATE,
    AUTH_REGISTER_SUB, AUTH_REGISTER_ERR, AUTH_GOOGLE_REGISTER, AUTH_HAVE_ACCOUNT, AUTH_CHECK_EMAIL,
    AUTH_FORGOT_SENT, AUTH_FORGOT_HINT, AUTH_BACK_TO_LOGIN, AUTH_EMAIL_FULL, AUTH_SEND,
    SET_CAT_SUMMARY, SET_CAT_CUSTOM, SET_CUR_DETAIL, SET_GUIDES_TOAST, SET_GUIDES_AGAIN,
    SET_GUIDES_DETAIL, ALERT_PLAN_DUE_TITLE, ALERT_PLAN_DUE_BODY, ALERT_PLAN_DUE_TODAY, ALERT_PLAN_DUE_ON,
    ALERT_PLANNED_TITLE, ALERT_PLANNED_BODY, ALERT_PLAN_AUTO_TITLE, ALERT_PLAN_AUTO_BODY, GUEST_TITLE,
    GUEST_BODY, LOAN_DESC_LENT, LOAN_DESC_BORROWED, PLAN_CONFIRM, PLAN_SKIP,
    PLAN_DONE, PLAN_SKIPPED, TERMS_ACCEPT, TERMS_TERMS, TERMS_AND,
    TERMS_PRIVACY, PW_STRONG, PW_RULES, PW_HIDE, PW_SHOW,
    AUTH_GOOGLE, MV_EMPTY, MV_SCHEDULED_ONE, REP_WEEK, API_OFFLINE,
    API_EMAIL_TAKEN, API_EMAIL_TAKEN_GOOGLE, API_WRONG_PASSWORD, API_SAME_PASSWORD, API_PASSWORD_FIRST_EMAIL,
    API_PASSWORD_FIRST_DELETE, API_GUEST,
    AUTH_OR,
    MV_SCHEDULED,
}

private val ES: Map<StringKey, String> = mapOf(
    StringKey.NAV_HOME to "Inicio",
    StringKey.NAV_REPORTS to "Reportes",
    StringKey.NAV_PLANS to "Planes",
    StringKey.NAV_ADD to "Agregar",
    StringKey.TITLE_TRANSACTIONS to "Movimientos",
    StringKey.TITLE_REPORTS to "Reportes",
    StringKey.TITLE_BUDGETS to "Presupuestos",
    StringKey.TITLE_SETTINGS to "Ajustes",
    StringKey.TITLE_PROFILE to "Perfil",
    StringKey.SETTINGS_PERSONAL_INFO to "Información personal",
    StringKey.SETTINGS_FULL_NAME to "Nombre completo",
    StringKey.SETTINGS_EMAIL to "Correo",
    StringKey.SETTINGS_SAVE_CHANGES to "Guardar cambios",
    StringKey.SETTINGS_PREFERENCES to "Preferencias",
    StringKey.SETTINGS_DARK_MODE to "Modo oscuro",
    StringKey.SETTINGS_NOTIFICATIONS to "Notificaciones",
    StringKey.SETTINGS_BIOMETRIC to "Ingreso biométrico",
    StringKey.SETTINGS_LANGUAGE to "Idioma",
    StringKey.SETTINGS_ABOUT to "Acerca de",
    StringKey.SETTINGS_PHONE to "Teléfono",
    StringKey.SETTINGS_CITY to "Ciudad",
    StringKey.SETTINGS_PRIVACY_SESSION to "Privacidad y sesión",
    StringKey.SETTINGS_BLUR_BALANCE to "Difuminar el saldo total",
    StringKey.SETTINGS_BLUR_BALANCE_HELP_ON to "En Inicio el saldo aparece oculto; tócalo para mostrarlo.",
    StringKey.SETTINGS_BLUR_BALANCE_HELP_OFF to "El saldo se muestra siempre al abrir Inicio.",
    StringKey.SETTINGS_AUTO_LOCK to "Cierre de sesión automático",
    StringKey.SETTINGS_AUTO_LOCK_NEVER to "Nunca",
    StringKey.SETTINGS_AUTO_LOCK_HELP_NEVER to "La sesión permanece abierta hasta que cierres manualmente.",
    StringKey.HOME_BALANCE_TAP_TO_REVEAL to "Toca para mostrar",

    StringKey.ADD_TXN_PAYMENT_METHOD to "Método de pago",

    StringKey.ADD_ACTION_MANUAL_TITLE to "Registrar manualmente",
    StringKey.ADD_ACTION_MANUAL_SUBTITLE to "Gasto, ingreso o transferencia",
    StringKey.ADD_ACTION_SCAN_TITLE to "Escanear código",
    StringKey.ADD_ACTION_SCAN_SUBTITLE to "Lee el código de barras de un producto",

    StringKey.PROFILE_LOGOUT to "Cerrar sesión",
    StringKey.PROFILE_MEMBER_SINCE to "desde",
    StringKey.PROFILE_WALLETS_DETAIL to "activas",
    StringKey.PROFILE_RECURRING_DETAIL to "series activas",
    StringKey.PROFILE_RECURRING_DETAIL_EMPTY to "Sin series recurrentes",
    StringKey.PROFILE_SETTINGS_DETAIL to "Idioma, moneda, seguridad",


    StringKey.PAYMENT_CASH to "Efectivo",
    StringKey.PAYMENT_DEBIT_CARD to "Tarjeta débito",
    StringKey.PAYMENT_CREDIT_CARD to "Tarjeta crédito",
    StringKey.PAYMENT_BANK_TRANSFER to "Transferencia",
    StringKey.PAYMENT_NEQUI to "Nequi",
    StringKey.PAYMENT_DAVIPLATA to "Daviplata",

    StringKey.COMMON_CANCEL to "Cancelar",
    StringKey.COMMON_SAVE to "Guardar",
    StringKey.COMMON_BACK to "Atrás",
    StringKey.COMMON_DELETE to "Eliminar",

    StringKey.SCANNER_TITLE to "Escanear código",
    StringKey.SCANNER_CLOSE_CD to "Cerrar",
    StringKey.SCANNER_PERMISSION_MESSAGE to "S2 Nova necesita acceso a la cámara para escanear códigos de barras.",
    StringKey.SCANNER_PERMISSION_BUTTON to "Permitir acceso a la cámara",
    StringKey.SCANNER_NOT_FOUND to "No encontramos ese producto.",
    StringKey.SCANNER_TRY_AGAIN to "Intentar de nuevo",
    StringKey.SCANNER_HINT to "Ubica el código de barras dentro del marco",
    StringKey.SCANNER_MANUAL_PLACEHOLDER to "O ingresa el código manualmente",
    StringKey.SCANNER_DISCARD to "Descartar",
    StringKey.SCANNER_CONFIRM_PURCHASE to "Registrar compra",
    StringKey.SCANNER_NOTIF_TITLE to "Compra registrada",
    StringKey.SCANNER_NOTIF_MESSAGE_PREFIX to "Se registró \"",
    StringKey.SCANNER_NOTIF_MESSAGE_MIDDLE to "\" — ",

    StringKey.HOME_GREETING_MORNING to "Buenos días,",
    StringKey.HOME_GREETING_AFTERNOON to "Buenas tardes,",
    StringKey.HOME_GREETING_EVENING to "Buenas noches,",
    StringKey.HOME_BALANCE to "SALDO TOTAL",
    StringKey.HOME_INCOME to "Ingresos",
    StringKey.HOME_EXPENSES to "Gastos",
    StringKey.HOME_SAVINGS to "Ahorro",
    StringKey.HOME_RECENT_TXNS to "Movimientos recientes",
    StringKey.HOME_SEE_ALL to "Ver todos",

    StringKey.NOTIF_MARK_ALL_READ to "Marcar leídas",
    StringKey.NOTIF_EMPTY to "Nada pendiente. Te avisamos cuando un cobro venza o un presupuesto se acerque al límite.",
    StringKey.NOTIF_UNREAD_SUFFIX to "sin leer",
    StringKey.NOTIF_ALL_CAUGHT_UP to "Todo al día",

    StringKey.REPORTS_RANGE_3M to "3M",
    StringKey.REPORTS_RANGE_6M to "6M",
    StringKey.REPORTS_RANGE_12M to "12M",
    StringKey.REPORTS_SUBTITLE_3M to "Últimos 3 meses",
    StringKey.REPORTS_SUBTITLE_6M to "Últimos 6 meses",
    StringKey.REPORTS_SUBTITLE_12M to "Últimos 12 meses",
    StringKey.REPORTS_SAVINGS_RATE to "Tasa de ahorro",
    StringKey.REPORTS_PERIOD_TOTALS to "Totales del periodo",
    StringKey.REPORTS_INCOME_VS_EXPENSES to "Ingresos vs gastos",
    StringKey.REPORTS_SPEND_BY_CATEGORY to "Gasto por categoría",
    StringKey.REPORTS_RANGE to "Periodo",
    StringKey.REPORTS_SUMMARY_FLOW to "%1\$s: ingresos de %2\$s y gastos de %3\$s. El mes con más gasto fue %4\$s.",
    StringKey.REPORTS_TAP_MONTH to "Toca un mes para ver sus cifras",
    StringKey.REPORTS_VS_PREVIOUS to "vs periodo anterior",

    StringKey.TXN_LIST_FILTER_ALL to "Todos",
    StringKey.TXN_LIST_FILTER_PENDING to "Programados",
    StringKey.TXN_LIST_TODAY to "Hoy",
    StringKey.TXN_LIST_YESTERDAY to "Ayer",


    StringKey.BUDGETS_NEW to "Nuevo presupuesto",
    StringKey.BUDGETS_SPENT_LABEL to "Gastado en presupuestos",
    StringKey.BUDGETS_LIMIT_TOTAL to "Límite total",
    StringKey.BUDGETS_DAYS_LEFT_NOTE to "Quedan %1\$d días y %2\$s disponibles",
    StringKey.BUDGETS_LAST_DAY_NOTE to "Hoy cierra el mes · %1\$s disponibles",
    StringKey.PLAN_STATE_A11Y to "%1\$s, %2\$d por ciento, %3\$s, %4\$s de %5\$s, %6\$s",
    StringKey.BUDGET_STATUS_OVER to "Excedido",
    StringKey.BUDGET_STATUS_NEAR to "Cerca del límite",
    StringKey.BUDGET_STATUS_ON_TRACK to "En curso",
    StringKey.BUDGETS_EMPTY to "Aún no tienes presupuestos. Crea el primero y se asignará una categoría según el nombre.",
    StringKey.COMMON_SAVE_ERROR to "No se pudo guardar. Inténtalo de nuevo.",

    StringKey.ADD_TXN_NO_WALLET_SUBTITLE to "Crea un wallet (efectivo, banco, ahorros...) antes de registrar movimientos.",
    StringKey.RECURRENCE_WEEKLY to "Semanal",
    StringKey.RECURRENCE_MONTHLY to "Mensual",
    StringKey.RECURRENCE_YEARLY to "Anual",

    StringKey.WALLETS_TITLE to "Billeteras",

    StringKey.GOALS_TITLE to "Metas",
    StringKey.GOALS_NEW to "Nueva meta",
    StringKey.GOALS_EMPTY to "Aún no tienes metas. Crea la primera y la categoría se sugiere por el nombre.",
    StringKey.GOALS_NOTE_NONE to "Sin abonos aún",
    StringKey.GOALS_NOTE_DONE to "Meta cumplida",
    StringKey.GOALS_NOTE_LEFT to "Faltan %s",
    StringKey.GOAL_PAY_NOTE to "%1\$s de %2\$s · el abono queda registrado en la billetera de origen",
    StringKey.GOALS_DELETE_NAMED to "Eliminar “%s”",
    StringKey.GOALS_DELETE_HAS_BALANCE to "La meta tiene %s ahorrados. Elige a dónde vuelve ese dinero.",
    StringKey.GOALS_DELETE_ORIGIN to "Devolver a su origen",
    StringKey.GOALS_DELETE_NO_ORIGIN to "Sin abonos registrados",
    StringKey.GOALS_DELETE_ALL_TO to "Todo a %s",
    StringKey.GOALS_DELETE_ONE_MOVE to "Un solo movimiento de %s",
    StringKey.GOALS_DELETE_AND_RETURN to "Eliminar y devolver %s",
    StringKey.GOALS_EDIT_TITLE to "Editar meta",
    StringKey.GOALS_DELETE to "Eliminar meta",
    StringKey.GOALS_DELETE_CONFIRM_BODY to "Esta acción no se puede deshacer.",
    StringKey.GOALS_DELETE_ERROR to "No se pudo eliminar la meta. Inténtalo de nuevo.",

    StringKey.GOAL_CONTRIBUTION_TITLE to "Abonar a",
    StringKey.GOAL_CONTRIBUTION_AMOUNT to "Monto del abono",
    StringKey.GOAL_CONTRIBUTION_WALLET to "Desde qué billetera",
    StringKey.GOAL_CONTRIBUTION_SAVE to "Abonar",
    StringKey.GOAL_CONTRIBUTION_SAVED to "Abono agregado",
    StringKey.GOAL_CONTRIBUTION_DESCRIPTION_PREFIX to "Abono a ",

    StringKey.COMMON_UNDO to "Deshacer",
    StringKey.COMMON_SESSION_EXPIRED to "Tu sesión expiró, inicia sesión de nuevo.",
    StringKey.COMMON_SESSION_IDLE to "Cerramos tu sesión por inactividad. Vuelve a entrar.",

    StringKey.RECURRING_TITLE to "Programados",
    StringKey.RECURRING_NEW to "Nueva serie recurrente",
    StringKey.RECURRING_EMPTY to "No tienes series recurrentes. Crea la primera con el + de arriba.",
    StringKey.RECURRING_DUE_TODAY to "Vence hoy",
    StringKey.RECURRING_NEXT_DUE to "Próximo",
    StringKey.RECURRING_CONFIRM to "Confirmar",
    StringKey.RECURRING_SKIP to "Omitir",
    StringKey.RECURRING_OVERDUE to "Vencida",
    StringKey.RECURRING_OVERDUE_SINCE to "Venció",
    StringKey.RECURRING_PAUSE to "Pausar",
    StringKey.RECURRING_RESUME to "Reanudar",
    StringKey.RECURRING_EDIT to "Editar",
    StringKey.RECURRING_PAUSED to "Pausada",
    StringKey.RECURRING_DELETE to "Eliminar programado",
    StringKey.RECURRING_DELETE_CONFIRM_TITLE to "¿Eliminar este programado?",
    StringKey.RECURRING_DELETE_CONFIRM_BODY to "Ya no se repetirá. Los movimientos que ya registró se conservan.",

    StringKey.LOANS_EMPTY_LENT to "No has prestado dinero. Registra el primero con el + de arriba.",
    StringKey.LOANS_EMPTY_BORROWED to "No tienes deudas registradas. Registra una con el + de arriba.",
    StringKey.LOANS_DIRECTION to "Dirección",
    StringKey.LOANS_DUE_OPTIONAL to "Vencimiento (opcional)",
    StringKey.LOANS_NO_DATE to "Sin fecha",
    StringKey.LOANS_PAY_TITLE_LENT to "Cobro de %s",
    StringKey.LOANS_PAY_TITLE_BORROWED to "Pagar a %s",
    StringKey.LOANS_PAY_NOTE to "Pendiente %1\$s de %2\$s",
    StringKey.LOANS_SETTLED_NOTE to "Saldado · %s",
    StringKey.LOANS_PAID_NOTE to " · abonado %1\$s de %2\$s",
    StringKey.LOANS_LENT_TAB to "Prestado",
    StringKey.LOANS_BORROWED_TAB to "Recibido",
    StringKey.LOANS_SETTLED to "Saldado",
    StringKey.LOANS_DUE to "Vence",
    StringKey.LOANS_NO_DUE_DATE to "Sin fecha de vencimiento",
    StringKey.LOANS_SUMMARY_LENT to "Te deben",
    StringKey.LOANS_SUMMARY_BORROWED to "Debes",
    StringKey.LOANS_RECORD_ONE to "registro",
    StringKey.LOANS_RECORD_MANY to "registros",
    StringKey.LOANS_SETTLED_WORD_ONE to "saldado",
    StringKey.LOANS_SETTLED_WORD_MANY to "saldados",
    StringKey.LOANS_NEW_LENT to "Registrar préstamo",
    StringKey.LOANS_NEW_BORROWED to "Registrar deuda",
    StringKey.LOANS_REGISTER_PAYMENT to "Registrar abono",
    StringKey.LOANS_SETTLE_ALL_SHORTCUT to "Saldar todo",
    StringKey.LOANS_PAYMENT_WALLET_LENT to "Billetera que recibe el abono",
    StringKey.LOANS_PAYMENT_WALLET_BORROWED to "Billetera de donde sale el pago",
    StringKey.LOANS_FORM_COUNTERPARTY_PLACEHOLDER to "Nombre de la contraparte",
    StringKey.LOANS_FORM_AMOUNT to "Monto",
    StringKey.LOANS_EDIT_TITLE to "Editar préstamo",
    StringKey.LOANS_DELETE to "Eliminar registro",
    StringKey.LOANS_DELETE_CONFIRM_TITLE to "¿Eliminar este registro?",
    StringKey.LOANS_DELETE_CONFIRM_BODY to "Esta acción no se puede deshacer.",
    StringKey.LOANS_FORM_PERSON_LENT to "¿A quién le prestaste?",
    StringKey.LOANS_FORM_PERSON_BORROWED to "¿A quién le debes?",
    StringKey.LOANS_FORM_WALLET_LENT to "Billetera de donde salió",
    StringKey.LOANS_FORM_WALLET_BORROWED to "Billetera que recibió el dinero",
    StringKey.LOANS_EDIT_ACTION to "Editar",
    StringKey.DATE_PICKER_TODAY to "Hoy",
    StringKey.DATE_PICKER_NO_DATE to "Sin fecha",
    StringKey.DATE_PICKER_USE_DATE to "Usar esta fecha",
    StringKey.DATE_PICKER_CHOOSE to "Elegir fecha",
    StringKey.PLANS_TAB to "Préstamos",
    StringKey.TITLE_PLANS to "Planes",

    StringKey.SETTINGS_LOCK_1_MINUTE to "1 minuto",
    StringKey.SETTINGS_LOCK_MINUTES to "%s minutos",
    StringKey.SETTINGS_LOCK_1_HOUR to "1 hora",
    StringKey.SETTINGS_AUTO_LOCK_HELP_PASSWORD_AFTER to "Tras %s sin actividad pedimos tu contraseña de nuevo.",
    StringKey.SETTINGS_AUTO_LOCK_HELP_BIOMETRIC_AFTER to "Tras %s sin actividad pedimos tu huella de nuevo.",

    StringKey.NAV_TRANSACTIONS to "Movimientos",
    StringKey.HOME_MONTH_INCOME to "Ingresos del mes",
    StringKey.HOME_MONTH_EXPENSES to "Gastos del mes",
    StringKey.HOME_WALLET_ONE to "billetera",
    StringKey.HOME_WALLET_MANY to "billeteras",
    StringKey.HOME_ADD_FIRST_WALLET to "Agrega tu primera billetera",
    StringKey.HOME_UPCOMING_7_DAYS to "Próximos 7 días",
    StringKey.HOME_UPCOMING_LINK to "Programados",
    StringKey.HOME_UPCOMING_EMPTY to "Nada programado para esta semana.",
    StringKey.HOME_UPCOMING_TODAY to "HOY",
    StringKey.HOME_UPCOMING_DUE_TODAY to "Vence hoy · confírmalo para que afecte el saldo",
    StringKey.HOME_UPCOMING_SCHEDULED to "Programado · %1\$s",
    StringKey.HOME_SYNC_ERROR to "No pudimos actualizar tus datos.",
    StringKey.HOME_ALERT_REVIEW to "Revisar",
    StringKey.HOME_NEXT_PAYMENT to "Próximo pago",
    StringKey.HOME_UPCOMING_MORE to "+%1\$d más esta semana",
    StringKey.HOME_VS to "vs %1\$s",
    StringKey.HOME_STAT_MORE to "%1\$s %% más que %2\$s",
    StringKey.HOME_STAT_LESS to "%1\$s %% menos que %2\$s",
    StringKey.HOME_FAVORABLE to "favorable",
    StringKey.HOME_UNFAVORABLE to "desfavorable",
    StringKey.HOME_THIS_MONTH to "Este mes",
    StringKey.HOME_SHOW_AMOUNTS to "Mostrar montos",
    StringKey.HOME_HIDE_AMOUNTS to "Ocultar montos",
    StringKey.HOME_BUDGETS_NONE to "Aún no tienes presupuestos",
    StringKey.COMMON_RETRY to "Reintentar",
    StringKey.COMMON_DISMISS to "Descartar",
    StringKey.AMOUNT_HIDDEN to "Monto oculto",
    StringKey.ALERT_SERIES_DUE_TITLE to "%1\$s vence hoy",
    StringKey.ALERT_SERIES_OVERDUE_TITLE to "%1\$s venció el %2\$s",
    StringKey.ALERT_SERIES_BODY to "%1\$s · confírmalo para que afecte el saldo",
    StringKey.ALERT_LOAN_LENT_TITLE to "%1\$s te debe",
    StringKey.ALERT_LOAN_BORROWED_TITLE to "Le debes a %1\$s",
    StringKey.ALERT_LOAN_BODY to "%1\$s · vence %2\$s",
    StringKey.ALERT_BUDGET_TITLE to "%1\$s al %2\$d%% del límite",
    StringKey.ALERT_BUDGET_BODY to "%1\$s de %2\$s este mes",
    StringKey.ALERT_GOAL_TITLE to "%1\$s está al %2\$d%%",
    StringKey.ALERT_GOAL_BODY to "Faltan %1\$s para cumplirla",
    StringKey.NM_FREQ_DAILY to "Diario",
    StringKey.NM_FREQ_WEEKLY to "Semanal",
    StringKey.NM_FREQ_MONTHLY to "Mensual",
    StringKey.NM_FREQ_YEARLY to "Anual",
    StringKey.NM_EVERY_DAILY to "Cada día",
    StringKey.NM_EVERY_WEEKLY to "Cada semana",
    StringKey.NM_EVERY_MONTHLY to "Cada mes",
    StringKey.NM_EVERY_YEARLY to "Cada año",
    StringKey.NM_NO_REPEAT to "No se repite",
    StringKey.NM_REPEAT to "Repetir",
    StringKey.NM_REPEAT_COUNT to "%1\$s × %2\$s · del %3\$s al %4\$s",
    StringKey.NM_REPEAT_UNTIL to "%1\$s · hasta el %2\$s",
    StringKey.NM_REPEAT_NEVER to "%1\$s · sin fecha de fin",
    StringKey.NM_SERIES_PAUSED to "Programado pausado",
    StringKey.NM_SERIES_SAVED to "Programado guardado",
    StringKey.NM_SERIES_ERR to "No se pudo guardar el programado. Intenta de nuevo.",
    StringKey.NM_TOAST_SCHEDULED to "Programado para el %1\$s. No afecta el saldo hasta entonces.",
    StringKey.NM_TOAST_SAVED to "Movimiento guardado",
    StringKey.NM_ERR_SAVE to "No se pudo guardar el movimiento. Intenta de nuevo.",
    StringKey.NM_EDIT_SERIES to "Editar programado",
    StringKey.NM_EDIT to "Editar movimiento",
    StringKey.NM_TITLE to "Nuevo movimiento",
    StringKey.NM_WALLET_IN to "Billetera que recibe",
    StringKey.NM_WALLET_FROM to "Desde",
    StringKey.NM_WALLET to "Billetera",
    StringKey.NM_WALLET_TO to "Transferir a",
    StringKey.NM_BUDGET_ADDS to "Suma a %1\$s",
    StringKey.NM_BUDGET_ADDS_TWO to "Suma a %1\$s y a %2\$s",
    StringKey.NM_BUDGET_BY_CATEGORY to "Por la categoría · %1\$s de %2\$s",
    StringKey.NM_BUDGET_CUSTOM to "Personalizado · %1\$s de %2\$s",
    StringKey.NM_BUDGET_WHEN_RECORDED to " · cuenta cuando se registre",
    StringKey.NM_BUDGET_WITH_THIS to " con este gasto",
    StringKey.NM_TITLE_PH to "Título",
    StringKey.NM_NOTE_PH to "Nota (opcional)",
    StringKey.NM_PHOTO to "Foto",
    StringKey.NM_DOCUMENT to "Documento",
    StringKey.NM_AUTOMATIC to "automático",
    StringKey.NM_WITH_CONFIRMATION to "con confirmación",
    StringKey.NM_SAVE_SERIES to "Guardar programado",
    StringKey.NM_SAVE_SCHEDULED to "Programar movimiento",
    StringKey.NM_SAVE_REPEAT to "Guardar y repetir",
    StringKey.NM_SAVE to "Guardar movimiento",
    StringKey.COMMON_DELETE_ERROR to "No se pudo eliminar. Intenta de nuevo.",
    StringKey.NM_TYPE_EXPENSE to "Gasto",
    StringKey.NM_TYPE_INCOME to "Ingreso",
    StringKey.NM_TYPE_TRANSFER to "Transferencia",
    StringKey.NM_CATEGORY to "CATEGORÍA",
    StringKey.NM_TRANSFER_BETWEEN to "Transferencia entre billeteras",
    StringKey.NM_PICK_CATEGORY to "Elige una categoría",
    StringKey.NM_FX_APPROX to "≈ %1\$s %2\$s en %3\$s · 1 %4\$s = %5\$s",
    StringKey.NM_FX_LATER to "Se convierte a %1\$s al guardar en %2\$s",
    StringKey.NM_SCHEDULED_CHIP to "PROGRAMADO",
    StringKey.NM_NOW to "Ahora",
    StringKey.NM_TODAY_AT to "Hoy %1\$s",
    StringKey.NM_ONE_ATTACHMENT to "1 adjunto",
    StringKey.NM_ATTACH to "Adjuntar",
    StringKey.NM_FROM to "De",
    StringKey.NM_BUDGET to "Presupuesto",
    StringKey.NM_MORE to "Más",
    StringKey.NM_NO_WALLET_TITLE to "Primero crea una billetera",
    StringKey.NM_NO_WALLET_BODY to "Necesitas al menos una para registrar movimientos.",
    StringKey.NM_NO_WALLET_CTA to "Crear billetera",
    StringKey.NM_SECTION_CURRENCY to "Moneda del movimiento",
    StringKey.NM_CURRENCY_HINT to "%1\$s está en %2\$s. Si el movimiento fue en otra moneda, guardamos el monto original y lo convertimos a %2\$s.",
    StringKey.NM_CURRENCY_OF to "Moneda de %1\$s",
    StringKey.NM_MANAGE_CURRENCIES to "Gestionar monedas en Ajustes →",
    StringKey.NM_DONE to "Listo",
    StringKey.NM_SECTION_BPICK to "Presupuesto personalizado",
    StringKey.NM_BPICK_AUTO to "Este gasto ya suma a %1\$s por su categoría. Elige un presupuesto personalizado si también cuenta ahí.",
    StringKey.NM_BPICK_NONE to "Ningún presupuesto por categoría cubre %1\$s. Puedes asignarlo a uno personalizado.",
    StringKey.NM_NONE_M to "Ninguno",
    StringKey.NM_NONE_F to "Ninguna",
    StringKey.NM_BPICK_NONE_DETAIL to "Solo cuenta por su categoría",
    StringKey.NM_X_OF_Y to "%1\$s de %2\$s",
    StringKey.NM_SECTION_MORE to "Préstamo o meta",
    StringKey.NM_MORE_OPTIONS to "Más opciones",
    StringKey.NM_TITLE_EXAMPLE to "Ej.: Mercado semanal",
    StringKey.NM_NOTE_LABEL to "Nota",
    StringKey.NM_LOAN to "Préstamo",
    StringKey.NM_EXPANDED to "Expandido",
    StringKey.NM_COLLAPSED to "Contraído",
    StringKey.NM_OPTIONAL to "Opcional",
    StringKey.NM_LOAN_BORROWED to "Es dinero que me prestaron",
    StringKey.NM_LOAN_LENT to "Es dinero que presté",
    StringKey.NM_LOAN_DETAIL to "Se registra en Planes › Préstamos con contraparte y vencimiento.",
    StringKey.NM_GOAL to "Aporte a una meta",
    StringKey.NM_CAT_INCOME to "¿De dónde viene el ingreso?",
    StringKey.NM_CAT_EXPENSE to "¿En qué gastaste?",
    StringKey.NM_CAT_STEP to "Paso 1 de 2 · después ingresas el monto",
    StringKey.NM_MANAGE_CATEGORIES to "Gestionar categorías en Ajustes →",
    StringKey.NM_SUBCATEGORY to "Subcategoría",
    StringKey.NM_CHANGE_CATEGORY to "← Cambiar categoría",
    StringKey.NM_AMOUNT to "Monto",
    StringKey.NM_SECTION_WHEN to "Fecha y hora",
    StringKey.NM_YESTERDAY to "Ayer",
    StringKey.NM_DAY_BEFORE to "Anteayer",
    StringKey.NM_LIKE_LAST to "Como el anterior · %1\$s, %2\$s",
    StringKey.NM_FUTURE to "Programar a futuro",
    StringKey.NM_TOMORROW to "Mañana",
    StringKey.NM_IN_A_WEEK to "En una semana",
    StringKey.NM_TIME to "Hora",
    StringKey.NM_WHEN_FUTURE to "Fecha futura: se guarda como programado y no afecta el saldo hasta que llegue la fecha y lo confirmes.",
    StringKey.NM_WHEN_PAST to "Fecha pasada: se registra con esa fecha y cuenta en el mes que corresponde.",
    StringKey.NM_WHEN_TODAY to "Se registra con la fecha y hora de hoy.",
    StringKey.NM_ENDS to "Termina",
    StringKey.NM_ENDS_COUNT to "Después de",
    StringKey.NM_ENDS_UNTIL to "En una fecha",
    StringKey.NM_ENDS_NEVER to "Sin fin",
    StringKey.NM_TIME_1 to "%1\$s vez",
    StringKey.NM_TIMES_N to "%1\$s veces",
    StringKey.NM_STARTS_TODAY to "Empieza hoy",
    StringKey.NM_STARTS_ON to "Empieza el %1\$s",
    StringKey.NM_CHANGE to "Cambiar",
    StringKey.NM_EACH_DATE to "En cada fecha",
    StringKey.NM_ASK to "Pedirme confirmación",
    StringKey.NM_ASK_DETAIL to "Te avisamos en cada fecha. No mueve saldo hasta que confirmes.",
    StringKey.NM_AUTO to "Registrar automáticamente",
    StringKey.NM_AUTO_DETAIL to "Se registra solo en cada fecha y te avisamos.",
    StringKey.NM_APPLY to "Aplicar",
    StringKey.NM_RECEIPT_FILE to "comprobante",
    StringKey.NM_RECEIPT_PHOTO_FILE to "foto-recibo.jpg",
    StringKey.NM_ERR_FILE_SIZE to "El archivo supera 10 MB.",
    StringKey.NM_SECTION_ATTACH to "Adjuntar comprobante",
    StringKey.NM_ATTACH_HINT to "Queda guardado con el movimiento y lo ves luego en su detalle.",
    StringKey.NM_ATTACH_CAMERA to "Tomar foto",
    StringKey.NM_ATTACH_CAMERA_DETAIL to "Usa la cámara para fotografiar el recibo",
    StringKey.NM_ATTACH_GALLERY to "Elegir de la galería",
    StringKey.NM_ATTACH_GALLERY_DETAIL to "Una foto o captura que ya tengas",
    StringKey.NM_ATTACH_DOC to "Subir PDF o documento",
    StringKey.NM_ATTACH_DOC_DETAIL to "PDF, JPG o PNG · hasta 10 MB",
    StringKey.NM_SECTION_FROM to "¿De quién recibiste el dinero?",
    StringKey.NM_FROM_HINT to "Opcional. Sirve para buscar y agrupar tus ingresos.",
    StringKey.NM_FROM_PH to "Empresa, cliente o persona",
    StringKey.NM_FROM_KIND to "Tipo de origen",
    StringKey.NM_FROM_EMPLOYER to "Empleador",
    StringKey.NM_FROM_CLIENT to "Cliente",
    StringKey.NM_FROM_FAMILY to "Familia",
    StringKey.NM_FROM_FRIEND to "Amigo",
    StringKey.NM_FROM_OTHER to "Otro",
    StringKey.NM_RECENTS to "Recientes",
    StringKey.NM_REMOVE_FROM to "Quitar origen",
    StringKey.NM_KEYPAD to "Teclado",
    StringKey.NM_CALCULATOR to "Calculadora",
    StringKey.COMMON_CLOSE to "Cerrar",
    StringKey.GOAL_EDIT to "Editar meta",
    StringKey.GOAL_NEW to "Nueva meta",
    StringKey.PLAN_NAME to "Nombre",
    StringKey.GOAL_NAME_PH to "Viaje a Perú, portátil nuevo…",
    StringKey.PLAN_ICON_GUESS to "Icono sugerido por el nombre. Toca otro para cambiarlo.",
    StringKey.GOAL_ICON_PICK to "Elige un icono para reconocer la meta de un vistazo.",
    StringKey.PLAN_ICON to "Icono",
    StringKey.GOAL_TARGET to "Monto objetivo",
    StringKey.GOAL_INITIAL to "Monto inicial",
    StringKey.GOAL_DATE to "Fecha objetivo (opcional)",
    StringKey.GOAL_PLAN to "Aporte periódico",
    StringKey.GOAL_PLAN_EMPTY to "Agrega un aporte automático o con recordatorio",
    StringKey.GOAL_DELETE to "Eliminar meta",
    StringKey.GOAL_SUM_GOAL to "Con %1\$s aportes de %2\$s cumples la meta hacia %3\$s de %4\$s.",
    StringKey.GOAL_SUM_COUNT to "%1\$s aportes · %2\$s en total · último el %3\$s",
    StringKey.GOAL_SUM_DATE to "Aportes de %1\$s hasta el %2\$s",
    StringKey.GOAL_PLAN_AMOUNT to "Monto de cada aporte",
    StringKey.GOAL_FREQ to "Frecuencia",
    StringKey.GOAL_FROM_WALLET to "Desde qué billetera",
    StringKey.GOAL_STARTS to "Empieza",
    StringKey.GOAL_ENDS_GOAL to "Al cumplir la meta",
    StringKey.GOAL_N_CONTRIBUTIONS to "%1\$s aportes",
    StringKey.GOAL_ASK_DETAIL to "Te llega una notificación y confirmas cada aporte.",
    StringKey.GOAL_AUTO to "Automático",
    StringKey.GOAL_AUTO_DETAIL to "Se descuenta de la billetera en cada fecha y te avisamos.",
    StringKey.GOAL_PLAN_REMOVE to "Quitar aporte periódico",
    StringKey.GOAL_SAVED_NEXT to "Meta guardada. Próximo aporte el %1\$s",
    StringKey.GOAL_DELETE_TITLE to "Eliminar la meta “%1\$s”",
    StringKey.GOAL_DELETE_SAVED to "%1\$s ahorrados de %2\$s",
    StringKey.GOAL_DELETE_PLAN to "El aporte periódico se cancela",
    StringKey.GOAL_DELETE_NEXT to "En el siguiente paso eliges a qué billetera vuelve el dinero",
    StringKey.GOAL_TARGET_ON to "fecha objetivo %1\$s",
    StringKey.GOAL_NO_TARGET to "sin fecha objetivo",
    StringKey.GOAL_OF to "de %1\$s",
    StringKey.GOAL_NO_PAYMENTS to "Sin abonos aún",
    StringKey.GOAL_MET to "Meta cumplida",
    StringKey.GOAL_LEFT to "Faltan %1\$s",
    StringKey.GOAL_NEXT to "próximo %1\$s",
    StringKey.GOAL_PAY to "Abonar",
    StringKey.GOAL_PLAN_TEXT_DAILY to "Aporte diario de %1\$s desde %2\$s",
    StringKey.GOAL_PLAN_TEXT_WEEKLY to "Aporte semanal de %1\$s desde %2\$s",
    StringKey.GOAL_PLAN_TEXT_MONTHLY to "Aporte mensual de %1\$s desde %2\$s",
    StringKey.GOAL_PAY_AMOUNT to "Monto del abono",
    StringKey.BUD_EDIT to "Editar presupuesto",
    StringKey.BUD_NEW to "Nuevo presupuesto",
    StringKey.BUD_KIND_CATEGORY to "Por categoría",
    StringKey.BUD_KIND_CUSTOM to "Personalizado",
    StringKey.BUD_KIND_CUSTOM_HINT to "Tú decides qué gastos cuentan: asígnalos desde Nuevo movimiento › Presupuesto.",
    StringKey.BUD_KIND_CATEGORY_HINT to "Los gastos de la categoría elegida suman solos, en las billeteras que indiques.",
    StringKey.BUD_PH_CUSTOM to "Cumpleaños, viaje, remodelación…",
    StringKey.BUD_PH_CATEGORY to "Mercado, salidas… (opcional)",
    StringKey.BUD_ICON_PICK to "Elige un icono para reconocerlo de un vistazo.",
    StringKey.BUD_CAT_GUESS to "Categoría detectada por el nombre. Puedes cambiarla.",
    StringKey.BUD_CAT_AUTO to "La categoría se detecta por el nombre; al elegir una manualmente se respeta.",
    StringKey.BUD_LIMIT to "Límite del presupuesto",
    StringKey.BUD_CATEGORY to "Categoría",
    StringKey.BUD_WALLETS to "Billeteras",
    StringKey.BUD_N_WALLETS to "%1\$s billeteras",
    StringKey.BUD_RANGE to "Rango",
    StringKey.BUD_PERIOD to "Periodo",
    StringKey.BUD_SCOPE_PICK to "Elige la categoría que cubre este presupuesto.",
    StringKey.BUD_SCOPE_ONLY to "Solo %1\$s",
    StringKey.BUD_SCOPE_ALL to "Todos los gastos de %1\$s",
    StringKey.BUD_SCOPE_FROM to ", pagados desde %1\$s",
    StringKey.BUD_SCOPE_ALL_WALLETS to ", de todas tus billeteras",
    StringKey.BUD_SCOPE_NO_RESET to "no se reinicia",
    StringKey.PLAN_STATE_NOT_STARTED to "Aún no empieza",
    StringKey.PLAN_STATE_OVER to "Superado por %1\$s",
    StringKey.PLAN_STATE_NEAR to "Cerca del límite",
    StringKey.PLAN_STATE_WATCH to "Vigílalo",
    StringKey.PLAN_STATE_OK to "Holgado",
    StringKey.BUD_SCOPE_RESET to "se reinicia cada mes",
    StringKey.BUD_DELETE to "Eliminar presupuesto",
    StringKey.BUD_SUB_HINT to "\"Todas\" incluye cada subcategoría.",
    StringKey.BUD_WALLETS_HINT to "Elige desde qué billeteras cuentan los gastos.",
    StringKey.BUD_PERIOD_CUSTOM_HINT to "No se reinicia. Cuenta los gastos entre las dos fechas.",
    StringKey.BUD_PERIOD_MONTHLY_HINT to "Se reinicia el 1 de cada mes.",
    StringKey.BUD_CAT_HINT to "Los gastos de esta categoría suman solos al presupuesto.",
    StringKey.BUD_ICON_HINT to "Para reconocer el presupuesto de un vistazo.",
    StringKey.BUD_ALL to "Todas",
    StringKey.BUD_CUSTOM_RANGE to "Rango personalizado",
    StringKey.BUD_UNTIL to "Hasta",
    StringKey.BUD_TAKEN to "Ya existe un presupuesto para esa categoría en ese periodo.",
    StringKey.BUD_DELETE_TITLE to "Eliminar el presupuesto “%1\$s”",
    StringKey.BUD_DELETE_SPENT to "%1\$s gastados de %2\$s",
    StringKey.BUD_THIS_MONTH to "este mes",
    StringKey.BUD_DELETE_HISTORY to "Su historial de avance y sus alertas",
    StringKey.BUD_DELETE_KEEP to "Tus movimientos no se borran; solo dejan de contar para este límite",
    StringKey.BUD_DELETE_ACK to "Entiendo que el presupuesto y su historial se eliminan.",
    StringKey.BUD_SCOPE_CUSTOM to "Personalizado · %1\$s movimientos asignados",
    StringKey.BUD_SCOPE_ONLY_WALLETS to " · solo %1\$s",
    StringKey.MV_DELETED to "Movimiento eliminado",
    StringKey.MV_DELETE_TITLE to "Eliminar “%1\$s”",
    StringKey.MV_DELETE_RECEIPT to "Su comprobante: %1\$s",
    StringKey.MV_DELETE_REPEATS to "Las repeticiones futuras de este movimiento",
    StringKey.MV_DELETE_BALANCE to "El saldo de %1\$s y tus presupuestos se recalculan",
    StringKey.MV_DELETE_ACK to "Entiendo que el movimiento se elimina para siempre.",
    StringKey.MV_DELETE_ACK_RECEIPT to "Entiendo que el movimiento y su comprobante se eliminan para siempre.",
    StringKey.MV_DELETE to "Eliminar movimiento",
    StringKey.MV_TITLE to "Movimiento",
    StringKey.MV_EDIT to "Editar",
    StringKey.MV_GONE to "Este movimiento ya no existe.",
    StringKey.MV_STATE_SCHEDULED to "Programado · no afecta el saldo todavía",
    StringKey.MV_STATE_RECORDED to "Registrado",
    StringKey.MV_NOTE to "Nota",
    StringKey.MV_MERCHANT to "Comercio",
    StringKey.MV_REPEATS to "Se repite",
    StringKey.MV_RECEIPT to "Comprobante",
    StringKey.MV_RECEIPT_META to "%1\$s · %2\$s · agregado el %3\$s",
    StringKey.MV_RECEIPT_SEE to "Ver",
    StringKey.MV_RECEIPT_REPLACE to "Reemplazar",
    StringKey.MV_RECEIPT_REMOVE to "Quitar",
    StringKey.MV_RECEIPT_REMOVED to "Comprobante quitado",
    StringKey.MV_RECEIPT_ATTACH to "Adjuntar recibo o factura",
    StringKey.MV_RECEIPT_PREVIEW to "Vista previa del comprobante",
    StringKey.MV_SHARE to "Compartir",
    StringKey.MV_RECEIPT_DOWNLOAD to "Descargar",
    StringKey.MV_RECEIPT_SAVED to "Comprobante guardado en el movimiento",
    StringKey.MV_RECEIPT_LOADING to "El comprobante aún se está cargando.",
    StringKey.CAT_TITLE to "Categorías",
    StringKey.CAT_TAB_EXPENSES to "Gastos",
    StringKey.CAT_TAB_INCOME to "Ingresos",
    StringKey.CAT_SUBTITLE to "Son las mismas en Nuevo movimiento, presupuestos, filtros y reportes. Toca una categoría o subcategoría para editarla.",
    StringKey.CAT_SUB_ONE to "%1\$s subcategoría",
    StringKey.CAT_SUB_MANY to "%1\$s subcategorías",
    StringKey.CAT_HIDDEN to "Oculta",
    StringKey.CAT_YOURS to "Tuya",
    StringKey.CAT_ADD_SUB to "+ Subcategoría",
    StringKey.CAT_EDIT_SUB to "Editar subcategoría",
    StringKey.CAT_EDIT to "Editar categoría",
    StringKey.CAT_NEW_SUB_IN to "Nueva subcategoría en %1\$s",
    StringKey.CAT_NEW to "Nueva categoría",
    StringKey.CAT_SUB_CUSTOM to "Creada por ti. Los cambios se ven en movimientos, presupuestos y reportes.",
    StringKey.CAT_SUB_BUILTIN to "Categoría de S2 Nova: puedes cambiar el nombre y el icono. No se puede eliminar; ocúltala si no la usas.",
    StringKey.CAT_SUB_NEW_INCOME to "Tipo: ingreso. Queda disponible en todo S2 Nova.",
    StringKey.CAT_SUB_NEW_EXPENSE to "Tipo: gasto. Queda disponible en todo S2 Nova.",
    StringKey.CAT_NAME_PH to "Ej. Clases de música",
    StringKey.CAT_INSIDE to "Dentro de",
    StringKey.CAT_NEW_MAIN to "Nueva principal",
    StringKey.CAT_ICON_COLOR to "Icono y color",
    StringKey.CAT_PARENT_COLOR to "Usa el color de %1\$s para agruparse igual en reportes.",
    StringKey.CAT_SHOW to "Mostrar al registrar",
    StringKey.CAT_SHOW_HINT to "Si la ocultas, sale del selector pero conserva su historial en reportes.",
    StringKey.CAT_SAVE to "Guardar cambios",
    StringKey.CAT_CREATE to "Crear categoría",
    StringKey.CAT_ERR_NAME to "Escribe un nombre.",
    StringKey.CAT_ERR_TAKEN to "Ya existe una categoría con ese nombre aquí.",
    StringKey.LOAN_ERR_SAVE to "No se pudo guardar. Intenta de nuevo.",
    StringKey.CAT_DELETE_SUB to "Eliminar subcategoría",
    StringKey.CAT_DELETE to "Eliminar categoría",
    StringKey.CAT_SUB_OF to "Subcategoría de %1\$s",
    StringKey.CAT_MAIN to "Categoría principal",
    StringKey.CAT_AND_SUBS to " y sus %1\$s subcategorías",
    StringKey.CAT_MOVE_ONE to "%1\$s movimiento pasa a %2\$s",
    StringKey.CAT_MOVE_MANY to "%1\$s movimientos pasan a %2\$s",
    StringKey.CAT_DELETE_GONE to "Deja de aparecer en presupuestos, filtros y reportes",
    StringKey.CAT_DELETE_ACK to "Entiendo que los movimientos se reasignan a %1\$s y que esto no se puede deshacer.",
    StringKey.WALLET_KIND_SAVINGS to "Cuenta de ahorros",
    StringKey.WALLET_KIND_CHECKING to "Cuenta corriente",
    StringKey.WALLET_KIND_CREDIT to "Tarjeta de crédito",
    StringKey.WALLET_KIND_CASH to "Efectivo",
    StringKey.WALLET_TITLE to "Billeteras",
    StringKey.WALLET_EMPTY to "No tienes billeteras. Agrega la primera con el + de arriba.",
    StringKey.WALLET_TOTAL to "%1\$s en total, en %2\$s. Las billeteras en otra moneda se convierten con la tasa del día.",
    StringKey.WALLET_SHARE to "%1\$d %% del total",
    StringKey.WALLET_TOTAL_LABEL to "Total en %1\$s",
    StringKey.WALLET_TOTAL_NOTE to "Las billeteras en otra moneda se convierten con la tasa del día.",
    StringKey.WALLET_EDIT to "Editar billetera",
    StringKey.WALLET_NEW to "Nueva billetera",
    StringKey.WALLET_NAME_PH to "Nequi, Bancolombia — Ahorros…",
    StringKey.WALLET_TYPE_GUESS to "Tipo detectado por el nombre. Puedes cambiarlo.",
    StringKey.WALLET_TYPE_HINT to "El tipo define el icono y el método de pago que deriva el servidor.",
    StringKey.WALLET_TYPE to "Tipo",
    StringKey.WALLET_CURRENCY to "Moneda",
    StringKey.WALLET_CURRENCY_HINT to "El saldo se lleva en %1\$s. Los movimientos en otra moneda se convierten al registrarlos.",
    StringKey.WALLET_BALANCE to "Saldo actual",
    StringKey.WALLET_INITIAL to "Saldo inicial",
    StringKey.WALLET_ERR_SAVE to "No se pudo guardar la billetera.",
    StringKey.WALLET_DELETE to "Eliminar billetera",
    StringKey.WALLET_LAST to "Necesitas al menos una billetera para usar S2 Nova.",
    StringKey.WALLET_DELETE_TITLE to "Eliminar la billetera “%1\$s”",
    StringKey.WALLET_DELETE_BALANCE to "Saldo actual: %1\$s",
    StringKey.WALLET_DELETE_ONE to "%1\$s movimiento asociado se elimina con ella",
    StringKey.WALLET_DELETE_MANY to "%1\$s movimientos asociados se eliminan con ella",
    StringKey.WALLET_DELETE_TOTAL to "El saldo total de Inicio se recalcula",
    StringKey.WALLET_DELETE_ACK to "Entiendo que se eliminan la billetera y sus %1\$s movimientos.",
    StringKey.CONFIRM_WILL_DELETE to "SE VA A ELIMINAR",
    StringKey.CONFIRM_CONTINUE to "Continuar",
    StringKey.CONFIRM_CANT_UNDO to "No se puede deshacer",
    StringKey.COMMON_BACK_TO to "Volver",
    StringKey.GUIDE_LABEL to "Guía rápida",
    StringKey.GUIDE_SKIP to "Omitir guías",
    StringKey.GUIDE_OK to "Entendido",
    StringKey.GUIDE_INICIO_LABEL to "Inicio",
    StringKey.GUIDE_INICIO_TITLE to "Tu dinero de un vistazo",
    StringKey.GUIDE_INICIO_BODY to "El saldo suma todas tus billeteras en tu moneda principal. Debajo ves el mes, las alertas y lo que viene.",
    StringKey.GUIDE_MOVIMIENTOS_LABEL to "Movimientos",
    StringKey.GUIDE_MOVIMIENTOS_TITLE to "Todo lo que entra y sale",
    StringKey.GUIDE_MOVIMIENTOS_BODY to "Los programados aparecen arriba. Toca un movimiento para ver su detalle y su comprobante.",
    StringKey.GUIDE_PLANES_LABEL to "Planes",
    StringKey.GUIDE_PLANES_TITLE to "Presupuestos, metas y préstamos",
    StringKey.GUIDE_PLANES_BODY to "Pon límites a tus gastos, ahorra para lo que quieres y lleva la cuenta de lo que prestas.",
    StringKey.GUIDE_REPORTES_LABEL to "Reportes",
    StringKey.GUIDE_REPORTES_TITLE to "Hacia dónde va tu dinero",
    StringKey.GUIDE_REPORTES_BODY to "Compara meses y revisa tus gastos por categoría o subcategoría.",
    StringKey.GUIDE_BILLETERAS_LABEL to "Billeteras",
    StringKey.GUIDE_BILLETERAS_TITLE to "Dónde está tu dinero",
    StringKey.GUIDE_BILLETERAS_BODY to "Cada billetera tiene su moneda. El saldo total las convierte a tu moneda principal.",
    StringKey.CUR_TITLE to "Monedas",
    StringKey.CUR_PRINCIPAL to "Moneda principal",
    StringKey.CUR_PRINCIPAL_BADGE to "Principal",
    StringKey.CUR_DETECTED to "Detectada por la región de tu dispositivo (%1\$s). El saldo total, los presupuestos y los reportes se muestran en %2\$s.",
    StringKey.CUR_OTHERS to "Otras monedas",
    StringKey.CUR_ONLY_PRINCIPAL to "Solo usas tu moneda principal.",
    StringKey.CUR_WALLET_ONE to "%1\$s billetera",
    StringKey.CUR_WALLET_MANY to "%1\$s billeteras",
    StringKey.CUR_NO_WALLETS to "sin billeteras",
    StringKey.CUR_REMOVE_TITLE to "Quitar %1\$s",
    StringKey.CUR_REMOVE_GONE to "Deja de aparecer al crear billeteras y movimientos",
    StringKey.CUR_REMOVE_KEEP to "Los movimientos ya registrados en %1\$s conservan su monto y su tasa",
    StringKey.CUR_REMOVE_ACK to "Entiendo que %1\$s se quita de mis monedas.",
    StringKey.CUR_REMOVE to "Quitar moneda",
    StringKey.CUR_ADD to "Agregar moneda",
    StringKey.CUR_RATES_NOTE to "Las tasas se actualizan cada día. Cada movimiento guarda su monto en la moneda original y la tasa usada al registrarlo.",
    StringKey.CUR_ADD_HINT to "Podrás crear billeteras y registrar movimientos en ella.",
    StringKey.CUR_ADDED to "%1\$s agregado",
    StringKey.FIRST_STEP to "PASO %1\$s DE 2",
    StringKey.FIRST_WALLET_TITLE to "Crea tu primera billetera",
    StringKey.FIRST_CURRENCY_TITLE to "Tu moneda principal",
    StringKey.FIRST_WALLET_BODY to "Necesitas al menos una para registrar movimientos. Puede ser tu cuenta de ahorros, Nequi o el efectivo que llevas.",
    StringKey.FIRST_CURRENCY_BODY to "La usamos para el saldo total y los reportes. La detectamos por la región de tu dispositivo; puedes cambiarla y agregar otras monedas después.",
    StringKey.FIRST_DETECTED to "Detectada en tu dispositivo · %1\$s",
    StringKey.FIRST_NAME_PH to "Nequi, Bancolombia, Efectivo…",
    StringKey.FIRST_OTHER_CURRENCIES to "Puedes crear billeteras en otras monedas después, desde Billeteras.",
    StringKey.FIRST_CREATE to "Crear billetera y entrar",
    StringKey.FIRST_ERR to "No se pudo crear la billetera. Intenta de nuevo.",
    StringKey.AUTH_LOGIN_TITLE to "Iniciar sesión",
    StringKey.AUTH_LOGIN_SUB to "Tus finanzas, siempre al día.",
    StringKey.AUTH_EMAIL to "CORREO",
    StringKey.AUTH_PASSWORD to "CONTRASEÑA",
    StringKey.AUTH_NAME to "NOMBRE",
    StringKey.AUTH_FORGOT to "¿Olvidaste tu contraseña?",
    StringKey.AUTH_ENTER to "Entrar",
    StringKey.AUTH_BAD_CREDENTIALS to "Correo o contraseña incorrectos.",
    StringKey.AUTH_GOOGLE_ERR to "No pudimos iniciar sesión con Google.",
    StringKey.AUTH_GUEST to "Continuar como invitado",
    StringKey.AUTH_GUEST_HINT to "Explora una cuenta de ejemplo. No se guarda nada.",
    StringKey.AUTH_NEW_HERE to "¿Nuevo aquí?",
    StringKey.AUTH_CREATE to "Crear cuenta",
    StringKey.AUTH_REGISTER_SUB to "Gratis, sin tarjeta de crédito.",
    StringKey.AUTH_REGISTER_ERR to "Revisa tu nombre, correo y que la contraseña tenga al menos 8 caracteres.",
    StringKey.AUTH_GOOGLE_REGISTER to "Registrarse con Google",
    StringKey.AUTH_HAVE_ACCOUNT to "¿Ya tienes cuenta?",
    StringKey.AUTH_CHECK_EMAIL to "Revisa tu correo",
    StringKey.AUTH_FORGOT_SENT to "Si existe una cuenta con ese correo, enviamos instrucciones para restablecer tu contraseña.",
    StringKey.AUTH_FORGOT_HINT to "Ingresa tu correo y te enviaremos instrucciones para recuperarla.",
    StringKey.AUTH_BACK_TO_LOGIN to "Volver a inicio de sesión",
    StringKey.AUTH_EMAIL_FULL to "Correo electrónico",
    StringKey.AUTH_SEND to "Enviar instrucciones",
    StringKey.SET_CAT_SUMMARY to "%1\$s de gasto · %2\$s de ingreso",
    StringKey.SET_CAT_CUSTOM to " · %1\$s tuyas",
    StringKey.SET_CUR_DETAIL to "%1\$s principal",
    StringKey.SET_GUIDES_TOAST to "Verás una guía corta en cada pantalla principal.",
    StringKey.SET_GUIDES_AGAIN to "Ver las guías otra vez",
    StringKey.SET_GUIDES_DETAIL to "Una guía corta en cada pantalla principal",
    StringKey.ALERT_PLAN_DUE_TITLE to "Aporte programado a %1\$s",
    StringKey.ALERT_PLAN_DUE_BODY to "Tienes un aporte de %1\$s %2\$s para %3\$s desde %4\$s.",
    StringKey.ALERT_PLAN_DUE_TODAY to "hoy",
    StringKey.ALERT_PLAN_DUE_ON to "el %1\$s",
    StringKey.ALERT_PLANNED_TITLE to "%1\$s se registra el %2\$s",
    StringKey.ALERT_PLANNED_BODY to "%1\$s · %2\$s · te pediremos confirmarlo",
    StringKey.ALERT_PLAN_AUTO_TITLE to "Aporte automático registrado",
    StringKey.ALERT_PLAN_AUTO_BODY to "%1\$s %2\$s a %3\$s desde %4\$s · %5\$s",
    StringKey.GUEST_TITLE to "Modo invitado",
    StringKey.GUEST_BODY to "Estás usando datos de ejemplo. No se guarda nada.",
    StringKey.LOAN_DESC_LENT to "Préstamo a %1\$s",
    StringKey.LOAN_DESC_BORROWED to "Deuda con %1\$s",
    StringKey.PLAN_CONFIRM to "Confirmar aporte",
    StringKey.PLAN_SKIP to "Omitir esta vez",
    StringKey.PLAN_DONE to "Aporte registrado",
    StringKey.PLAN_SKIPPED to "Aporte omitido. Te avisamos en la próxima fecha.",
    StringKey.TERMS_ACCEPT to "Acepto los",
    StringKey.TERMS_TERMS to "Términos",
    StringKey.TERMS_AND to "y la",
    StringKey.TERMS_PRIVACY to "Política de privacidad",
    StringKey.PW_STRONG to "Segura",
    StringKey.PW_RULES to "Mínimo 8 caracteres, una mayúscula y un número.",
    StringKey.PW_HIDE to "Ocultar contraseña",
    StringKey.PW_SHOW to "Ver contraseña",
    StringKey.AUTH_GOOGLE to "Continuar con Google",
    StringKey.MV_EMPTY to "Aún no tienes movimientos. Registra el primero con el botón +.",
    StringKey.MV_SCHEDULED_ONE to "Programado",
    StringKey.REP_WEEK to "Sem %1\$s",
    StringKey.API_OFFLINE to "No se pudo conectar con el servidor. Verifica tu conexión e inténtalo de nuevo.",
    StringKey.API_EMAIL_TAKEN to "Ya existe una cuenta con ese correo.",
    StringKey.API_EMAIL_TAKEN_GOOGLE to "Ya existe una cuenta con ese correo. Entra con tu contraseña o verifica el correo con Google primero.",
    StringKey.API_WRONG_PASSWORD to "La contraseña no es correcta.",
    StringKey.API_SAME_PASSWORD to "La nueva contraseña debe ser distinta de la actual.",
    StringKey.API_PASSWORD_FIRST_EMAIL to "Crea una contraseña antes de cambiar tu correo.",
    StringKey.API_PASSWORD_FIRST_DELETE to "Crea una contraseña antes de eliminar tu cuenta.",
    StringKey.API_GUEST to "No disponible en modo invitado.",
    StringKey.AUTH_OR to "O",
    StringKey.MV_SCHEDULED to "Programados",
)

private val EN: Map<StringKey, String> = mapOf(
    StringKey.NAV_HOME to "Home",
    StringKey.NAV_REPORTS to "Reports",
    StringKey.NAV_PLANS to "Plans",
    StringKey.NAV_ADD to "Add",
    StringKey.TITLE_TRANSACTIONS to "Transactions",
    StringKey.TITLE_REPORTS to "Reports",
    StringKey.TITLE_BUDGETS to "Budgets",
    StringKey.TITLE_SETTINGS to "Settings",
    StringKey.TITLE_PROFILE to "Profile",
    StringKey.SETTINGS_PERSONAL_INFO to "Personal information",
    StringKey.SETTINGS_FULL_NAME to "Full name",
    StringKey.SETTINGS_EMAIL to "Email",
    StringKey.SETTINGS_SAVE_CHANGES to "Save changes",
    StringKey.SETTINGS_PREFERENCES to "Preferences",
    StringKey.SETTINGS_DARK_MODE to "Dark mode",
    StringKey.SETTINGS_NOTIFICATIONS to "Notifications",
    StringKey.SETTINGS_BIOMETRIC to "Biometric sign-in",
    StringKey.SETTINGS_LANGUAGE to "Language",
    StringKey.SETTINGS_ABOUT to "About",
    StringKey.SETTINGS_PHONE to "Phone",
    StringKey.SETTINGS_CITY to "City",
    StringKey.SETTINGS_PRIVACY_SESSION to "Privacy and session",
    StringKey.SETTINGS_BLUR_BALANCE to "Blur total balance",
    StringKey.SETTINGS_BLUR_BALANCE_HELP_ON to "Home hides the balance by default; tap it to reveal.",
    StringKey.SETTINGS_BLUR_BALANCE_HELP_OFF to "The balance always shows when you open Home.",
    StringKey.SETTINGS_AUTO_LOCK to "Automatic session lock",
    StringKey.SETTINGS_AUTO_LOCK_NEVER to "Never",
    StringKey.SETTINGS_AUTO_LOCK_HELP_NEVER to "The session stays open until you sign out manually.",
    StringKey.HOME_BALANCE_TAP_TO_REVEAL to "Tap to reveal",

    StringKey.ADD_TXN_PAYMENT_METHOD to "Payment method",

    StringKey.ADD_ACTION_MANUAL_TITLE to "Record manually",
    StringKey.ADD_ACTION_MANUAL_SUBTITLE to "Expense, income or transfer",
    StringKey.ADD_ACTION_SCAN_TITLE to "Scan code",
    StringKey.ADD_ACTION_SCAN_SUBTITLE to "Read a product's barcode",

    StringKey.PROFILE_LOGOUT to "Log out",
    StringKey.PROFILE_MEMBER_SINCE to "since",
    StringKey.PROFILE_WALLETS_DETAIL to "active",
    StringKey.PROFILE_RECURRING_DETAIL to "active series",
    StringKey.PROFILE_RECURRING_DETAIL_EMPTY to "No recurring series",
    StringKey.PROFILE_SETTINGS_DETAIL to "Language, currency, security",


    StringKey.PAYMENT_CASH to "Cash",
    StringKey.PAYMENT_DEBIT_CARD to "Debit card",
    StringKey.PAYMENT_CREDIT_CARD to "Credit card",
    StringKey.PAYMENT_BANK_TRANSFER to "Bank transfer",
    StringKey.PAYMENT_NEQUI to "Nequi",
    StringKey.PAYMENT_DAVIPLATA to "Daviplata",

    StringKey.COMMON_CANCEL to "Cancel",
    StringKey.COMMON_SAVE to "Save",
    StringKey.COMMON_BACK to "Back",
    StringKey.COMMON_DELETE to "Delete",

    StringKey.SCANNER_TITLE to "Scan barcode",
    StringKey.SCANNER_CLOSE_CD to "Close",
    StringKey.SCANNER_PERMISSION_MESSAGE to "S2 Nova needs camera access to scan barcodes.",
    StringKey.SCANNER_PERMISSION_BUTTON to "Allow camera access",
    StringKey.SCANNER_NOT_FOUND to "We couldn't find that product.",
    StringKey.SCANNER_TRY_AGAIN to "Try again",
    StringKey.SCANNER_HINT to "Position the barcode inside the frame",
    StringKey.SCANNER_MANUAL_PLACEHOLDER to "Or enter the code manually",
    StringKey.SCANNER_DISCARD to "Discard",
    StringKey.SCANNER_CONFIRM_PURCHASE to "Record purchase",
    StringKey.SCANNER_NOTIF_TITLE to "Purchase recorded",
    StringKey.SCANNER_NOTIF_MESSAGE_PREFIX to "Registered \"",
    StringKey.SCANNER_NOTIF_MESSAGE_MIDDLE to "\" — ",

    StringKey.HOME_GREETING_MORNING to "Good morning,",
    StringKey.HOME_GREETING_AFTERNOON to "Good afternoon,",
    StringKey.HOME_GREETING_EVENING to "Good evening,",
    StringKey.HOME_BALANCE to "TOTAL BALANCE",
    StringKey.HOME_INCOME to "Income",
    StringKey.HOME_EXPENSES to "Expenses",
    StringKey.HOME_SAVINGS to "Savings",
    StringKey.HOME_RECENT_TXNS to "Recent transactions",
    StringKey.HOME_SEE_ALL to "See all",

    StringKey.NOTIF_MARK_ALL_READ to "Mark all as read",
    StringKey.NOTIF_EMPTY to "Nothing pending. We'll let you know when a charge is due or a budget nears its limit.",
    StringKey.NOTIF_UNREAD_SUFFIX to "unread",
    StringKey.NOTIF_ALL_CAUGHT_UP to "All caught up",

    StringKey.REPORTS_RANGE_3M to "3M",
    StringKey.REPORTS_RANGE_6M to "6M",
    StringKey.REPORTS_RANGE_12M to "12M",
    StringKey.REPORTS_SUBTITLE_3M to "Last 3 months",
    StringKey.REPORTS_SUBTITLE_6M to "Last 6 months",
    StringKey.REPORTS_SUBTITLE_12M to "Last 12 months",
    StringKey.REPORTS_SAVINGS_RATE to "Savings rate",
    StringKey.REPORTS_PERIOD_TOTALS to "Period totals",
    StringKey.REPORTS_INCOME_VS_EXPENSES to "Income vs expenses",
    StringKey.REPORTS_SPEND_BY_CATEGORY to "Spend by category",
    StringKey.REPORTS_RANGE to "Period",
    StringKey.REPORTS_SUMMARY_FLOW to "%1\$s: %2\$s of income and %3\$s of expenses. The month with the most spending was %4\$s.",
    StringKey.REPORTS_TAP_MONTH to "Tap a month to see its figures",
    StringKey.REPORTS_VS_PREVIOUS to "vs previous period",

    StringKey.TXN_LIST_FILTER_ALL to "All",
    StringKey.TXN_LIST_FILTER_PENDING to "Scheduled",
    StringKey.TXN_LIST_TODAY to "Today",
    StringKey.TXN_LIST_YESTERDAY to "Yesterday",


    StringKey.BUDGETS_NEW to "New budget",
    StringKey.BUDGETS_SPENT_LABEL to "Spent on budgets",
    StringKey.BUDGETS_LIMIT_TOTAL to "Total limit",
    StringKey.BUDGETS_DAYS_LEFT_NOTE to "%1\$d days left and %2\$s available",
    StringKey.BUDGETS_LAST_DAY_NOTE to "The month closes today · %1\$s available",
    StringKey.PLAN_STATE_A11Y to "%1\$s, %2\$d percent, %3\$s, %4\$s of %5\$s, %6\$s",
    StringKey.BUDGET_STATUS_OVER to "Over budget",
    StringKey.BUDGET_STATUS_NEAR to "Near limit",
    StringKey.BUDGET_STATUS_ON_TRACK to "On track",
    StringKey.BUDGETS_EMPTY to "You have no budgets yet. Create the first one and a category is assigned from its name.",
    StringKey.COMMON_SAVE_ERROR to "Couldn't save. Please try again.",

    StringKey.ADD_TXN_NO_WALLET_SUBTITLE to "Create a wallet (cash, bank, savings...) before recording transactions.",
    StringKey.RECURRENCE_WEEKLY to "Weekly",
    StringKey.RECURRENCE_MONTHLY to "Monthly",
    StringKey.RECURRENCE_YEARLY to "Yearly",

    StringKey.WALLETS_TITLE to "Wallets",

    StringKey.GOALS_TITLE to "Goals",
    StringKey.GOALS_NEW to "New goal",
    StringKey.GOALS_EMPTY to "No goals yet. Create one like \"Car Payment\".",
    StringKey.GOALS_NOTE_NONE to "No contributions yet",
    StringKey.GOALS_NOTE_DONE to "Goal reached",
    StringKey.GOALS_NOTE_LEFT to "%s to go",
    StringKey.GOAL_PAY_NOTE to "%1\$s of %2\$s · the contribution is recorded in the source wallet",
    StringKey.GOALS_DELETE_NAMED to "Delete “%s”",
    StringKey.GOALS_DELETE_HAS_BALANCE to "This goal holds %s. Choose where that money goes back to.",
    StringKey.GOALS_DELETE_ORIGIN to "Return to where it came from",
    StringKey.GOALS_DELETE_NO_ORIGIN to "No contributions recorded",
    StringKey.GOALS_DELETE_ALL_TO to "All to %s",
    StringKey.GOALS_DELETE_ONE_MOVE to "A single transaction of %s",
    StringKey.GOALS_DELETE_AND_RETURN to "Delete and return %s",
    StringKey.GOALS_EDIT_TITLE to "Edit goal",
    StringKey.GOALS_DELETE to "Delete goal",
    StringKey.GOALS_DELETE_CONFIRM_BODY to "This action can't be undone.",
    StringKey.GOALS_DELETE_ERROR to "Couldn't delete the goal. Please try again.",

    StringKey.GOAL_CONTRIBUTION_TITLE to "Contribute to",
    StringKey.GOAL_CONTRIBUTION_AMOUNT to "Amount to add",
    StringKey.GOAL_CONTRIBUTION_WALLET to "From which wallet",
    StringKey.GOAL_CONTRIBUTION_SAVE to "Contribute",
    StringKey.GOAL_CONTRIBUTION_SAVED to "Contribution added",
    StringKey.GOAL_CONTRIBUTION_DESCRIPTION_PREFIX to "Contribution to ",

    StringKey.COMMON_UNDO to "Undo",
    StringKey.COMMON_SESSION_EXPIRED to "Your session expired, please sign in again.",
    StringKey.COMMON_SESSION_IDLE to "We signed you out after a period of inactivity. Sign in again.",

    StringKey.RECURRING_TITLE to "Scheduled",
    StringKey.RECURRING_NEW to "New recurring series",
    StringKey.RECURRING_EMPTY to "No recurring series yet. Create the first one with the + above.",
    StringKey.RECURRING_DUE_TODAY to "Due today",
    StringKey.RECURRING_NEXT_DUE to "Next",
    StringKey.RECURRING_CONFIRM to "Confirm",
    StringKey.RECURRING_SKIP to "Skip",
    StringKey.RECURRING_OVERDUE to "Overdue",
    StringKey.RECURRING_OVERDUE_SINCE to "Due",
    StringKey.RECURRING_PAUSE to "Pause",
    StringKey.RECURRING_RESUME to "Resume",
    StringKey.RECURRING_EDIT to "Edit",
    StringKey.RECURRING_PAUSED to "Paused",
    StringKey.RECURRING_DELETE to "Delete scheduled item",
    StringKey.RECURRING_DELETE_CONFIRM_TITLE to "Delete this scheduled item?",
    StringKey.RECURRING_DELETE_CONFIRM_BODY to "It won't repeat anymore. Transactions it already recorded are kept.",

    StringKey.LOANS_EMPTY_LENT to "You haven't lent any money. Record the first one with the + above.",
    StringKey.LOANS_EMPTY_BORROWED to "You have no debts on record. Add one with the + above.",
    StringKey.LOANS_DIRECTION to "Direction",
    StringKey.LOANS_DUE_OPTIONAL to "Due date (optional)",
    StringKey.LOANS_NO_DATE to "No date",
    StringKey.LOANS_PAY_TITLE_LENT to "Payment from %s",
    StringKey.LOANS_PAY_TITLE_BORROWED to "Pay %s",
    StringKey.LOANS_PAY_NOTE to "%1\$s outstanding of %2\$s",
    StringKey.LOANS_SETTLED_NOTE to "Settled · %s",
    StringKey.LOANS_PAID_NOTE to " · %1\$s paid of %2\$s",
    StringKey.LOANS_LENT_TAB to "Lent",
    StringKey.LOANS_BORROWED_TAB to "Borrowed",
    StringKey.LOANS_SETTLED to "Settled",
    StringKey.LOANS_DUE to "Due",
    StringKey.LOANS_NO_DUE_DATE to "No due date",
    StringKey.LOANS_SUMMARY_LENT to "They owe you",
    StringKey.LOANS_SUMMARY_BORROWED to "You owe",
    StringKey.LOANS_RECORD_ONE to "record",
    StringKey.LOANS_RECORD_MANY to "records",
    StringKey.LOANS_SETTLED_WORD_ONE to "settled",
    StringKey.LOANS_SETTLED_WORD_MANY to "settled",
    StringKey.LOANS_NEW_LENT to "Record a loan",
    StringKey.LOANS_NEW_BORROWED to "Record a debt",
    StringKey.LOANS_REGISTER_PAYMENT to "Record payment",
    StringKey.LOANS_SETTLE_ALL_SHORTCUT to "Settle all",
    StringKey.LOANS_PAYMENT_WALLET_LENT to "Wallet receiving the payment",
    StringKey.LOANS_PAYMENT_WALLET_BORROWED to "Wallet the payment comes from",
    StringKey.LOANS_FORM_COUNTERPARTY_PLACEHOLDER to "Person's name",
    StringKey.LOANS_FORM_AMOUNT to "Amount",
    StringKey.LOANS_EDIT_TITLE to "Edit loan",
    StringKey.LOANS_DELETE to "Delete loan",
    StringKey.LOANS_DELETE_CONFIRM_TITLE to "Delete this record?",
    StringKey.LOANS_DELETE_CONFIRM_BODY to "This action can't be undone.",
    StringKey.LOANS_FORM_PERSON_LENT to "Who did you lend to?",
    StringKey.LOANS_FORM_PERSON_BORROWED to "Who do you owe?",
    StringKey.LOANS_FORM_WALLET_LENT to "Wallet the money came from",
    StringKey.LOANS_FORM_WALLET_BORROWED to "Wallet that received the money",
    StringKey.LOANS_EDIT_ACTION to "Edit",
    StringKey.DATE_PICKER_TODAY to "Today",
    StringKey.DATE_PICKER_NO_DATE to "No date",
    StringKey.DATE_PICKER_USE_DATE to "Use this date",
    StringKey.DATE_PICKER_CHOOSE to "Choose date",
    StringKey.PLANS_TAB to "Loans",
    StringKey.TITLE_PLANS to "Plans",

    StringKey.SETTINGS_LOCK_1_MINUTE to "1 minute",
    StringKey.SETTINGS_LOCK_MINUTES to "%s minutes",
    StringKey.SETTINGS_LOCK_1_HOUR to "1 hour",
    StringKey.SETTINGS_AUTO_LOCK_HELP_PASSWORD_AFTER to "After %s without activity we ask for your password again.",
    StringKey.SETTINGS_AUTO_LOCK_HELP_BIOMETRIC_AFTER to "After %s without activity we ask for your fingerprint again.",

    StringKey.NAV_TRANSACTIONS to "Transactions",
    StringKey.HOME_MONTH_INCOME to "Income this month",
    StringKey.HOME_MONTH_EXPENSES to "Expenses this month",
    StringKey.HOME_WALLET_ONE to "wallet",
    StringKey.HOME_WALLET_MANY to "wallets",
    StringKey.HOME_ADD_FIRST_WALLET to "Add your first wallet",
    StringKey.HOME_UPCOMING_7_DAYS to "Next 7 days",
    StringKey.HOME_UPCOMING_LINK to "Scheduled",
    StringKey.HOME_UPCOMING_EMPTY to "Nothing scheduled this week.",
    StringKey.HOME_UPCOMING_TODAY to "TODAY",
    StringKey.HOME_UPCOMING_DUE_TODAY to "Due today · confirm it so it affects your balance",
    StringKey.HOME_UPCOMING_SCHEDULED to "Scheduled · %1\$s",
    StringKey.HOME_SYNC_ERROR to "We couldn't update your data.",
    StringKey.HOME_ALERT_REVIEW to "Review",
    StringKey.HOME_NEXT_PAYMENT to "Next payment",
    StringKey.HOME_UPCOMING_MORE to "+%1\$d more this week",
    StringKey.HOME_VS to "vs %1\$s",
    StringKey.HOME_STAT_MORE to "%1\$s%% more than %2\$s",
    StringKey.HOME_STAT_LESS to "%1\$s%% less than %2\$s",
    StringKey.HOME_FAVORABLE to "favorable",
    StringKey.HOME_UNFAVORABLE to "unfavorable",
    StringKey.HOME_THIS_MONTH to "This month",
    StringKey.HOME_SHOW_AMOUNTS to "Show amounts",
    StringKey.HOME_HIDE_AMOUNTS to "Hide amounts",
    StringKey.HOME_BUDGETS_NONE to "No budgets yet",
    StringKey.COMMON_RETRY to "Retry",
    StringKey.COMMON_DISMISS to "Dismiss",
    StringKey.AMOUNT_HIDDEN to "Hidden amount",
    StringKey.ALERT_SERIES_DUE_TITLE to "%1\$s is due today",
    StringKey.ALERT_SERIES_OVERDUE_TITLE to "%1\$s was due %2\$s",
    StringKey.ALERT_SERIES_BODY to "%1\$s · confirm it so it affects your balance",
    StringKey.ALERT_LOAN_LENT_TITLE to "%1\$s owes you",
    StringKey.ALERT_LOAN_BORROWED_TITLE to "You owe %1\$s",
    StringKey.ALERT_LOAN_BODY to "%1\$s · due %2\$s",
    StringKey.ALERT_BUDGET_TITLE to "%1\$s at %2\$d%% of its limit",
    StringKey.ALERT_BUDGET_BODY to "%1\$s of %2\$s this month",
    StringKey.ALERT_GOAL_TITLE to "%1\$s is at %2\$d%%",
    StringKey.ALERT_GOAL_BODY to "%1\$s left to reach it",
    StringKey.NM_FREQ_DAILY to "Daily",
    StringKey.NM_FREQ_WEEKLY to "Weekly",
    StringKey.NM_FREQ_MONTHLY to "Monthly",
    StringKey.NM_FREQ_YEARLY to "Yearly",
    StringKey.NM_EVERY_DAILY to "Every day",
    StringKey.NM_EVERY_WEEKLY to "Every week",
    StringKey.NM_EVERY_MONTHLY to "Every month",
    StringKey.NM_EVERY_YEARLY to "Every year",
    StringKey.NM_NO_REPEAT to "Doesn't repeat",
    StringKey.NM_REPEAT to "Repeat",
    StringKey.NM_REPEAT_COUNT to "%1\$s × %2\$s · %3\$s to %4\$s",
    StringKey.NM_REPEAT_UNTIL to "%1\$s · until %2\$s",
    StringKey.NM_REPEAT_NEVER to "%1\$s · no end date",
    StringKey.NM_SERIES_PAUSED to "Scheduled item paused",
    StringKey.NM_SERIES_SAVED to "Scheduled item saved",
    StringKey.NM_SERIES_ERR to "Couldn't save the scheduled item. Try again.",
    StringKey.NM_TOAST_SCHEDULED to "Scheduled for %1\$s. It won't affect your balance until then.",
    StringKey.NM_TOAST_SAVED to "Transaction saved",
    StringKey.NM_ERR_SAVE to "Couldn't save the transaction. Try again.",
    StringKey.NM_EDIT_SERIES to "Edit scheduled item",
    StringKey.NM_EDIT to "Edit transaction",
    StringKey.NM_TITLE to "New transaction",
    StringKey.NM_WALLET_IN to "Receiving wallet",
    StringKey.NM_WALLET_FROM to "From",
    StringKey.NM_WALLET to "Wallet",
    StringKey.NM_WALLET_TO to "Transfer to",
    StringKey.NM_BUDGET_ADDS to "Adds to %1\$s",
    StringKey.NM_BUDGET_ADDS_TWO to "Adds to %1\$s and %2\$s",
    StringKey.NM_BUDGET_BY_CATEGORY to "By category · %1\$s of %2\$s",
    StringKey.NM_BUDGET_CUSTOM to "Custom · %1\$s of %2\$s",
    StringKey.NM_BUDGET_WHEN_RECORDED to " · counts once recorded",
    StringKey.NM_BUDGET_WITH_THIS to " with this expense",
    StringKey.NM_TITLE_PH to "Title",
    StringKey.NM_NOTE_PH to "Note (optional)",
    StringKey.NM_PHOTO to "Photo",
    StringKey.NM_DOCUMENT to "Document",
    StringKey.NM_AUTOMATIC to "automatic",
    StringKey.NM_WITH_CONFIRMATION to "with confirmation",
    StringKey.NM_SAVE_SERIES to "Save scheduled item",
    StringKey.NM_SAVE_SCHEDULED to "Schedule transaction",
    StringKey.NM_SAVE_REPEAT to "Save and repeat",
    StringKey.NM_SAVE to "Save transaction",
    StringKey.COMMON_DELETE_ERROR to "Couldn't delete. Try again.",
    StringKey.NM_TYPE_EXPENSE to "Expense",
    StringKey.NM_TYPE_INCOME to "Income",
    StringKey.NM_TYPE_TRANSFER to "Transfer",
    StringKey.NM_CATEGORY to "CATEGORY",
    StringKey.NM_TRANSFER_BETWEEN to "Transfer between wallets",
    StringKey.NM_PICK_CATEGORY to "Pick a category",
    StringKey.NM_FX_APPROX to "≈ %1\$s %2\$s in %3\$s · 1 %4\$s = %5\$s",
    StringKey.NM_FX_LATER to "Converted to %1\$s when saved to %2\$s",
    StringKey.NM_SCHEDULED_CHIP to "SCHEDULED",
    StringKey.NM_NOW to "Now",
    StringKey.NM_TODAY_AT to "Today %1\$s",
    StringKey.NM_ONE_ATTACHMENT to "1 attachment",
    StringKey.NM_ATTACH to "Attach",
    StringKey.NM_FROM to "From",
    StringKey.NM_BUDGET to "Budget",
    StringKey.NM_MORE to "More",
    StringKey.NM_NO_WALLET_TITLE to "Create a wallet first",
    StringKey.NM_NO_WALLET_BODY to "You need at least one to record transactions.",
    StringKey.NM_NO_WALLET_CTA to "Create wallet",
    StringKey.NM_SECTION_CURRENCY to "Transaction currency",
    StringKey.NM_CURRENCY_HINT to "%1\$s is in %2\$s. If the transaction was in another currency, we keep the original amount and convert it to %2\$s.",
    StringKey.NM_CURRENCY_OF to "Currency of %1\$s",
    StringKey.NM_MANAGE_CURRENCIES to "Manage currencies in Settings →",
    StringKey.NM_DONE to "Done",
    StringKey.NM_SECTION_BPICK to "Custom budget",
    StringKey.NM_BPICK_AUTO to "This expense already counts toward %1\$s through its category. Pick a custom budget if it counts there too.",
    StringKey.NM_BPICK_NONE to "No category budget covers %1\$s. You can assign it to a custom one.",
    StringKey.NM_NONE_M to "None",
    StringKey.NM_NONE_F to "None",
    StringKey.NM_BPICK_NONE_DETAIL to "Counts only through its category",
    StringKey.NM_X_OF_Y to "%1\$s of %2\$s",
    StringKey.NM_SECTION_MORE to "Loan or goal",
    StringKey.NM_MORE_OPTIONS to "More options",
    StringKey.NM_TITLE_EXAMPLE to "E.g. Weekly groceries",
    StringKey.NM_NOTE_LABEL to "Note",
    StringKey.NM_LOAN to "Loan",
    StringKey.NM_EXPANDED to "Expanded",
    StringKey.NM_COLLAPSED to "Collapsed",
    StringKey.NM_OPTIONAL to "Optional",
    StringKey.NM_LOAN_BORROWED to "It's money I borrowed",
    StringKey.NM_LOAN_LENT to "It's money I lent",
    StringKey.NM_LOAN_DETAIL to "It's recorded in Plans › Loans with a counterparty and due date.",
    StringKey.NM_GOAL to "Goal contribution",
    StringKey.NM_CAT_INCOME to "Where does the income come from?",
    StringKey.NM_CAT_EXPENSE to "What did you spend on?",
    StringKey.NM_CAT_STEP to "Step 1 of 2 · then you enter the amount",
    StringKey.NM_MANAGE_CATEGORIES to "Manage categories in Settings →",
    StringKey.NM_SUBCATEGORY to "Subcategory",
    StringKey.NM_CHANGE_CATEGORY to "← Change category",
    StringKey.NM_AMOUNT to "Amount",
    StringKey.NM_SECTION_WHEN to "Date and time",
    StringKey.NM_YESTERDAY to "Yesterday",
    StringKey.NM_DAY_BEFORE to "Day before yesterday",
    StringKey.NM_LIKE_LAST to "Same as last · %1\$s, %2\$s",
    StringKey.NM_FUTURE to "Schedule ahead",
    StringKey.NM_TOMORROW to "Tomorrow",
    StringKey.NM_IN_A_WEEK to "In a week",
    StringKey.NM_TIME to "Time",
    StringKey.NM_WHEN_FUTURE to "Future date: it's saved as scheduled and won't affect your balance until the date comes and you confirm it.",
    StringKey.NM_WHEN_PAST to "Past date: it's recorded on that date and counts in that month.",
    StringKey.NM_WHEN_TODAY to "It's recorded with today's date and time.",
    StringKey.NM_ENDS to "Ends",
    StringKey.NM_ENDS_COUNT to "After",
    StringKey.NM_ENDS_UNTIL to "On a date",
    StringKey.NM_ENDS_NEVER to "Never",
    StringKey.NM_TIME_1 to "%1\$s time",
    StringKey.NM_TIMES_N to "%1\$s times",
    StringKey.NM_STARTS_TODAY to "Starts today",
    StringKey.NM_STARTS_ON to "Starts %1\$s",
    StringKey.NM_CHANGE to "Change",
    StringKey.NM_EACH_DATE to "On each date",
    StringKey.NM_ASK to "Ask me to confirm",
    StringKey.NM_ASK_DETAIL to "We'll remind you on each date. Your balance won't change until you confirm.",
    StringKey.NM_AUTO to "Record automatically",
    StringKey.NM_AUTO_DETAIL to "It's recorded on each date and we'll let you know.",
    StringKey.NM_APPLY to "Apply",
    StringKey.NM_RECEIPT_FILE to "receipt",
    StringKey.NM_RECEIPT_PHOTO_FILE to "receipt-photo.jpg",
    StringKey.NM_ERR_FILE_SIZE to "The file is over 10 MB.",
    StringKey.NM_SECTION_ATTACH to "Attach receipt",
    StringKey.NM_ATTACH_HINT to "It's saved with the transaction and you can see it later in its details.",
    StringKey.NM_ATTACH_CAMERA to "Take photo",
    StringKey.NM_ATTACH_CAMERA_DETAIL to "Use the camera to photograph the receipt",
    StringKey.NM_ATTACH_GALLERY to "Choose from gallery",
    StringKey.NM_ATTACH_GALLERY_DETAIL to "A photo or screenshot you already have",
    StringKey.NM_ATTACH_DOC to "Upload PDF or document",
    StringKey.NM_ATTACH_DOC_DETAIL to "PDF, JPG or PNG · up to 10 MB",
    StringKey.NM_SECTION_FROM to "Who did you get the money from?",
    StringKey.NM_FROM_HINT to "Optional. Helps you search and group your income.",
    StringKey.NM_FROM_PH to "Company, client or person",
    StringKey.NM_FROM_KIND to "Source type",
    StringKey.NM_FROM_EMPLOYER to "Employer",
    StringKey.NM_FROM_CLIENT to "Client",
    StringKey.NM_FROM_FAMILY to "Family",
    StringKey.NM_FROM_FRIEND to "Friend",
    StringKey.NM_FROM_OTHER to "Other",
    StringKey.NM_RECENTS to "Recent",
    StringKey.NM_REMOVE_FROM to "Remove source",
    StringKey.NM_KEYPAD to "Keypad",
    StringKey.NM_CALCULATOR to "Calculator",
    StringKey.COMMON_CLOSE to "Close",
    StringKey.GOAL_EDIT to "Edit goal",
    StringKey.GOAL_NEW to "New goal",
    StringKey.PLAN_NAME to "Name",
    StringKey.GOAL_NAME_PH to "Trip to Peru, new laptop…",
    StringKey.PLAN_ICON_GUESS to "Icon suggested from the name. Tap another to change it.",
    StringKey.GOAL_ICON_PICK to "Pick an icon to spot the goal at a glance.",
    StringKey.PLAN_ICON to "Icon",
    StringKey.GOAL_TARGET to "Target amount",
    StringKey.GOAL_INITIAL to "Starting amount",
    StringKey.GOAL_DATE to "Target date (optional)",
    StringKey.GOAL_PLAN to "Recurring contribution",
    StringKey.GOAL_PLAN_EMPTY to "Add an automatic or reminded contribution",
    StringKey.GOAL_DELETE to "Delete goal",
    StringKey.GOAL_SUM_GOAL to "With %1\$s contributions of %2\$s you reach the goal around %3\$s %4\$s.",
    StringKey.GOAL_SUM_COUNT to "%1\$s contributions · %2\$s in total · last on %3\$s",
    StringKey.GOAL_SUM_DATE to "Contributions of %1\$s until %2\$s",
    StringKey.GOAL_PLAN_AMOUNT to "Amount per contribution",
    StringKey.GOAL_FREQ to "Frequency",
    StringKey.GOAL_FROM_WALLET to "From which wallet",
    StringKey.GOAL_STARTS to "Starts",
    StringKey.GOAL_ENDS_GOAL to "When the goal is met",
    StringKey.GOAL_N_CONTRIBUTIONS to "%1\$s contributions",
    StringKey.GOAL_ASK_DETAIL to "You get a notification and confirm each contribution.",
    StringKey.GOAL_AUTO to "Automatic",
    StringKey.GOAL_AUTO_DETAIL to "It's taken from the wallet on each date and we'll let you know.",
    StringKey.GOAL_PLAN_REMOVE to "Remove recurring contribution",
    StringKey.GOAL_SAVED_NEXT to "Goal saved. Next contribution on %1\$s",
    StringKey.GOAL_DELETE_TITLE to "Delete the “%1\$s” goal",
    StringKey.GOAL_DELETE_SAVED to "%1\$s saved of %2\$s",
    StringKey.GOAL_DELETE_PLAN to "The recurring contribution is canceled",
    StringKey.GOAL_DELETE_NEXT to "In the next step you choose which wallet the money goes back to",
    StringKey.GOAL_TARGET_ON to "target date %1\$s",
    StringKey.GOAL_NO_TARGET to "no target date",
    StringKey.GOAL_OF to "of %1\$s",
    StringKey.GOAL_NO_PAYMENTS to "No contributions yet",
    StringKey.GOAL_MET to "Goal reached",
    StringKey.GOAL_LEFT to "%1\$s to go",
    StringKey.GOAL_NEXT to "next %1\$s",
    StringKey.GOAL_PAY to "Add money",
    StringKey.GOAL_PLAN_TEXT_DAILY to "Daily contribution of %1\$s from %2\$s",
    StringKey.GOAL_PLAN_TEXT_WEEKLY to "Weekly contribution of %1\$s from %2\$s",
    StringKey.GOAL_PLAN_TEXT_MONTHLY to "Monthly contribution of %1\$s from %2\$s",
    StringKey.GOAL_PAY_AMOUNT to "Contribution amount",
    StringKey.BUD_EDIT to "Edit budget",
    StringKey.BUD_NEW to "New budget",
    StringKey.BUD_KIND_CATEGORY to "By category",
    StringKey.BUD_KIND_CUSTOM to "Custom",
    StringKey.BUD_KIND_CUSTOM_HINT to "You decide which expenses count: assign them from New transaction › Budget.",
    StringKey.BUD_KIND_CATEGORY_HINT to "The chosen category's expenses add up on their own, from the wallets you pick.",
    StringKey.BUD_PH_CUSTOM to "Birthday, trip, remodeling…",
    StringKey.BUD_PH_CATEGORY to "Groceries, going out… (optional)",
    StringKey.BUD_ICON_PICK to "Pick an icon to spot it at a glance.",
    StringKey.BUD_CAT_GUESS to "Category detected from the name. You can change it.",
    StringKey.BUD_CAT_AUTO to "The category is detected from the name; one you pick yourself is kept.",
    StringKey.BUD_LIMIT to "Budget limit",
    StringKey.BUD_CATEGORY to "Category",
    StringKey.BUD_WALLETS to "Wallets",
    StringKey.BUD_N_WALLETS to "%1\$s wallets",
    StringKey.BUD_RANGE to "Range",
    StringKey.BUD_PERIOD to "Period",
    StringKey.BUD_SCOPE_PICK to "Pick the category this budget covers.",
    StringKey.BUD_SCOPE_ONLY to "Only %1\$s",
    StringKey.BUD_SCOPE_ALL to "All %1\$s expenses",
    StringKey.BUD_SCOPE_FROM to ", paid from %1\$s",
    StringKey.BUD_SCOPE_ALL_WALLETS to ", from all your wallets",
    StringKey.BUD_SCOPE_NO_RESET to "doesn't reset",
    StringKey.PLAN_STATE_NOT_STARTED to "Hasn't started",
    StringKey.PLAN_STATE_OVER to "Over by %1\$s",
    StringKey.PLAN_STATE_NEAR to "Near the limit",
    StringKey.PLAN_STATE_WATCH to "Keep an eye on it",
    StringKey.PLAN_STATE_OK to "Comfortable",
    StringKey.BUD_SCOPE_RESET to "resets every month",
    StringKey.BUD_DELETE to "Delete budget",
    StringKey.BUD_SUB_HINT to "\"All\" includes every subcategory.",
    StringKey.BUD_WALLETS_HINT to "Pick which wallets the expenses count from.",
    StringKey.BUD_PERIOD_CUSTOM_HINT to "It doesn't reset. It counts expenses between the two dates.",
    StringKey.BUD_PERIOD_MONTHLY_HINT to "It resets on the 1st of each month.",
    StringKey.BUD_CAT_HINT to "This category's expenses add to the budget on their own.",
    StringKey.BUD_ICON_HINT to "To spot the budget at a glance.",
    StringKey.BUD_ALL to "All",
    StringKey.BUD_CUSTOM_RANGE to "Custom range",
    StringKey.BUD_UNTIL to "Until",
    StringKey.BUD_TAKEN to "You already have a budget for that category in that period.",
    StringKey.BUD_DELETE_TITLE to "Delete the “%1\$s” budget",
    StringKey.BUD_DELETE_SPENT to "%1\$s spent of %2\$s",
    StringKey.BUD_THIS_MONTH to "this month",
    StringKey.BUD_DELETE_HISTORY to "Its progress history and alerts",
    StringKey.BUD_DELETE_KEEP to "Your transactions aren't deleted; they just stop counting toward this limit",
    StringKey.BUD_DELETE_ACK to "I understand the budget and its history will be deleted.",
    StringKey.BUD_SCOPE_CUSTOM to "Custom · %1\$s transactions assigned",
    StringKey.BUD_SCOPE_ONLY_WALLETS to " · only %1\$s",
    StringKey.MV_DELETED to "Transaction deleted",
    StringKey.MV_DELETE_TITLE to "Delete “%1\$s”",
    StringKey.MV_DELETE_RECEIPT to "Its receipt: %1\$s",
    StringKey.MV_DELETE_REPEATS to "This transaction's future repeats",
    StringKey.MV_DELETE_BALANCE to "%1\$s's balance and your budgets are recalculated",
    StringKey.MV_DELETE_ACK to "I understand the transaction is deleted for good.",
    StringKey.MV_DELETE_ACK_RECEIPT to "I understand the transaction and its receipt are deleted for good.",
    StringKey.MV_DELETE to "Delete transaction",
    StringKey.MV_TITLE to "Transaction",
    StringKey.MV_EDIT to "Edit",
    StringKey.MV_GONE to "This transaction no longer exists.",
    StringKey.MV_STATE_SCHEDULED to "Scheduled · doesn't affect your balance yet",
    StringKey.MV_STATE_RECORDED to "Recorded",
    StringKey.MV_NOTE to "Note",
    StringKey.MV_MERCHANT to "Merchant",
    StringKey.MV_REPEATS to "Repeats",
    StringKey.MV_RECEIPT to "Receipt",
    StringKey.MV_RECEIPT_META to "%1\$s · %2\$s · added %3\$s",
    StringKey.MV_RECEIPT_SEE to "View",
    StringKey.MV_RECEIPT_REPLACE to "Replace",
    StringKey.MV_RECEIPT_REMOVE to "Remove",
    StringKey.MV_RECEIPT_REMOVED to "Receipt removed",
    StringKey.MV_RECEIPT_ATTACH to "Attach a receipt or invoice",
    StringKey.MV_RECEIPT_PREVIEW to "Receipt preview",
    StringKey.MV_SHARE to "Share",
    StringKey.MV_RECEIPT_DOWNLOAD to "Download",
    StringKey.MV_RECEIPT_SAVED to "Receipt saved to the transaction",
    StringKey.MV_RECEIPT_LOADING to "The receipt is still loading.",
    StringKey.CAT_TITLE to "Categories",
    StringKey.CAT_TAB_EXPENSES to "Expenses",
    StringKey.CAT_TAB_INCOME to "Income",
    StringKey.CAT_SUBTITLE to "The same in New transaction, budgets, filters and reports. Tap a category or subcategory to edit it.",
    StringKey.CAT_SUB_ONE to "%1\$s subcategory",
    StringKey.CAT_SUB_MANY to "%1\$s subcategories",
    StringKey.CAT_HIDDEN to "Hidden",
    StringKey.CAT_YOURS to "Yours",
    StringKey.CAT_ADD_SUB to "+ Subcategory",
    StringKey.CAT_EDIT_SUB to "Edit subcategory",
    StringKey.CAT_EDIT to "Edit category",
    StringKey.CAT_NEW_SUB_IN to "New subcategory in %1\$s",
    StringKey.CAT_NEW to "New category",
    StringKey.CAT_SUB_CUSTOM to "Created by you. Changes show in transactions, budgets and reports.",
    StringKey.CAT_SUB_BUILTIN to "S2 Nova category: you can change its name and icon. It can't be deleted; hide it if you don't use it.",
    StringKey.CAT_SUB_NEW_INCOME to "Type: income. Available across S2 Nova.",
    StringKey.CAT_SUB_NEW_EXPENSE to "Type: expense. Available across S2 Nova.",
    StringKey.CAT_NAME_PH to "E.g. Music lessons",
    StringKey.CAT_INSIDE to "Inside",
    StringKey.CAT_NEW_MAIN to "New main one",
    StringKey.CAT_ICON_COLOR to "Icon and color",
    StringKey.CAT_PARENT_COLOR to "It uses %1\$s's color so it groups the same way in reports.",
    StringKey.CAT_SHOW to "Show when recording",
    StringKey.CAT_SHOW_HINT to "If you hide it, it leaves the picker but keeps its history in reports.",
    StringKey.CAT_SAVE to "Save changes",
    StringKey.CAT_CREATE to "Create category",
    StringKey.CAT_ERR_NAME to "Enter a name.",
    StringKey.CAT_ERR_TAKEN to "A category with that name already exists here.",
    StringKey.LOAN_ERR_SAVE to "Couldn't save. Try again.",
    StringKey.CAT_DELETE_SUB to "Delete subcategory",
    StringKey.CAT_DELETE to "Delete category",
    StringKey.CAT_SUB_OF to "%1\$s subcategory",
    StringKey.CAT_MAIN to "Main category",
    StringKey.CAT_AND_SUBS to " and its %1\$s subcategories",
    StringKey.CAT_MOVE_ONE to "%1\$s transaction moves to %2\$s",
    StringKey.CAT_MOVE_MANY to "%1\$s transactions move to %2\$s",
    StringKey.CAT_DELETE_GONE to "It stops showing in budgets, filters and reports",
    StringKey.CAT_DELETE_ACK to "I understand the transactions are reassigned to %1\$s and that this can't be undone.",
    StringKey.WALLET_KIND_SAVINGS to "Savings account",
    StringKey.WALLET_KIND_CHECKING to "Checking account",
    StringKey.WALLET_KIND_CREDIT to "Credit card",
    StringKey.WALLET_KIND_CASH to "Cash",
    StringKey.WALLET_TITLE to "Wallets",
    StringKey.WALLET_EMPTY to "You don't have wallets. Add the first one with the + above.",
    StringKey.WALLET_TOTAL to "%1\$s in total, in %2\$s. Wallets in another currency are converted at today's rate.",
    StringKey.WALLET_SHARE to "%1\$d%% of total",
    StringKey.WALLET_TOTAL_LABEL to "Total in %1\$s",
    StringKey.WALLET_TOTAL_NOTE to "Wallets in another currency are converted at today's rate.",
    StringKey.WALLET_EDIT to "Edit wallet",
    StringKey.WALLET_NEW to "New wallet",
    StringKey.WALLET_NAME_PH to "Nequi, Bancolombia — Savings…",
    StringKey.WALLET_TYPE_GUESS to "Type detected from the name. You can change it.",
    StringKey.WALLET_TYPE_HINT to "The type sets the icon and the payment method the server derives.",
    StringKey.WALLET_TYPE to "Type",
    StringKey.WALLET_CURRENCY to "Currency",
    StringKey.WALLET_CURRENCY_HINT to "The balance is kept in %1\$s. Transactions in another currency are converted when recorded.",
    StringKey.WALLET_BALANCE to "Current balance",
    StringKey.WALLET_INITIAL to "Starting balance",
    StringKey.WALLET_ERR_SAVE to "Couldn't save the wallet.",
    StringKey.WALLET_DELETE to "Delete wallet",
    StringKey.WALLET_LAST to "You need at least one wallet to use S2 Nova.",
    StringKey.WALLET_DELETE_TITLE to "Delete the “%1\$s” wallet",
    StringKey.WALLET_DELETE_BALANCE to "Current balance: %1\$s",
    StringKey.WALLET_DELETE_ONE to "%1\$s linked transaction is deleted with it",
    StringKey.WALLET_DELETE_MANY to "%1\$s linked transactions are deleted with it",
    StringKey.WALLET_DELETE_TOTAL to "Home's total balance is recalculated",
    StringKey.WALLET_DELETE_ACK to "I understand the wallet and its %1\$s transactions will be deleted.",
    StringKey.CONFIRM_WILL_DELETE to "WILL BE DELETED",
    StringKey.CONFIRM_CONTINUE to "Continue",
    StringKey.CONFIRM_CANT_UNDO to "This can't be undone",
    StringKey.COMMON_BACK_TO to "Back",
    StringKey.GUIDE_LABEL to "Quick guide",
    StringKey.GUIDE_SKIP to "Skip guides",
    StringKey.GUIDE_OK to "Got it",
    StringKey.GUIDE_INICIO_LABEL to "Home",
    StringKey.GUIDE_INICIO_TITLE to "Your money at a glance",
    StringKey.GUIDE_INICIO_BODY to "Your balance adds up all your wallets in your main currency. Below you see the month, alerts and what's coming.",
    StringKey.GUIDE_MOVIMIENTOS_LABEL to "Transactions",
    StringKey.GUIDE_MOVIMIENTOS_TITLE to "Everything in and out",
    StringKey.GUIDE_MOVIMIENTOS_BODY to "Scheduled items show at the top. Tap a transaction to see its details and receipt.",
    StringKey.GUIDE_PLANES_LABEL to "Plans",
    StringKey.GUIDE_PLANES_TITLE to "Budgets, goals and loans",
    StringKey.GUIDE_PLANES_BODY to "Set limits on your spending, save for what you want and keep track of what you lend.",
    StringKey.GUIDE_REPORTES_LABEL to "Reports",
    StringKey.GUIDE_REPORTES_TITLE to "Where your money goes",
    StringKey.GUIDE_REPORTES_BODY to "Compare months and review your spending by category or subcategory.",
    StringKey.GUIDE_BILLETERAS_LABEL to "Wallets",
    StringKey.GUIDE_BILLETERAS_TITLE to "Where your money is",
    StringKey.GUIDE_BILLETERAS_BODY to "Each wallet has its own currency. The total balance converts them to your main currency.",
    StringKey.CUR_TITLE to "Currencies",
    StringKey.CUR_PRINCIPAL to "Main currency",
    StringKey.CUR_PRINCIPAL_BADGE to "Main",
    StringKey.CUR_DETECTED to "Detected from your device's region (%1\$s). Your total balance, budgets and reports are shown in %2\$s.",
    StringKey.CUR_OTHERS to "Other currencies",
    StringKey.CUR_ONLY_PRINCIPAL to "You only use your main currency.",
    StringKey.CUR_WALLET_ONE to "%1\$s wallet",
    StringKey.CUR_WALLET_MANY to "%1\$s wallets",
    StringKey.CUR_NO_WALLETS to "no wallets",
    StringKey.CUR_REMOVE_TITLE to "Remove %1\$s",
    StringKey.CUR_REMOVE_GONE to "It stops showing when creating wallets and transactions",
    StringKey.CUR_REMOVE_KEEP to "Transactions already recorded in %1\$s keep their amount and rate",
    StringKey.CUR_REMOVE_ACK to "I understand %1\$s is removed from my currencies.",
    StringKey.CUR_REMOVE to "Remove currency",
    StringKey.CUR_ADD to "Add currency",
    StringKey.CUR_RATES_NOTE to "Rates update every day. Each transaction keeps its amount in the original currency and the rate used when recorded.",
    StringKey.CUR_ADD_HINT to "You'll be able to create wallets and record transactions in it.",
    StringKey.CUR_ADDED to "%1\$s added",
    StringKey.FIRST_STEP to "STEP %1\$s OF 2",
    StringKey.FIRST_WALLET_TITLE to "Create your first wallet",
    StringKey.FIRST_CURRENCY_TITLE to "Your main currency",
    StringKey.FIRST_WALLET_BODY to "You need at least one to record transactions. It can be your savings account, Nequi or the cash you carry.",
    StringKey.FIRST_CURRENCY_BODY to "We use it for your total balance and reports. We detected it from your device's region; you can change it and add other currencies later.",
    StringKey.FIRST_DETECTED to "Detected on your device · %1\$s",
    StringKey.FIRST_NAME_PH to "Nequi, Bancolombia, Cash…",
    StringKey.FIRST_OTHER_CURRENCIES to "You can create wallets in other currencies later, from Wallets.",
    StringKey.FIRST_CREATE to "Create wallet and enter",
    StringKey.FIRST_ERR to "Couldn't create the wallet. Try again.",
    StringKey.AUTH_LOGIN_TITLE to "Sign in",
    StringKey.AUTH_LOGIN_SUB to "Your finances, always up to date.",
    StringKey.AUTH_EMAIL to "EMAIL",
    StringKey.AUTH_PASSWORD to "PASSWORD",
    StringKey.AUTH_NAME to "NAME",
    StringKey.AUTH_FORGOT to "Forgot your password?",
    StringKey.AUTH_ENTER to "Sign in",
    StringKey.AUTH_BAD_CREDENTIALS to "Wrong email or password.",
    StringKey.AUTH_GOOGLE_ERR to "We couldn't sign you in with Google.",
    StringKey.AUTH_GUEST to "Continue as guest",
    StringKey.AUTH_GUEST_HINT to "Explore a sample account. Nothing is saved.",
    StringKey.AUTH_NEW_HERE to "New here?",
    StringKey.AUTH_CREATE to "Create account",
    StringKey.AUTH_REGISTER_SUB to "Free, no credit card.",
    StringKey.AUTH_REGISTER_ERR to "Check your name and email, and that the password has at least 8 characters.",
    StringKey.AUTH_GOOGLE_REGISTER to "Sign up with Google",
    StringKey.AUTH_HAVE_ACCOUNT to "Already have an account?",
    StringKey.AUTH_CHECK_EMAIL to "Check your email",
    StringKey.AUTH_FORGOT_SENT to "If an account with that email exists, we sent instructions to reset your password.",
    StringKey.AUTH_FORGOT_HINT to "Enter your email and we'll send you instructions to recover it.",
    StringKey.AUTH_BACK_TO_LOGIN to "Back to sign in",
    StringKey.AUTH_EMAIL_FULL to "Email",
    StringKey.AUTH_SEND to "Send instructions",
    StringKey.SET_CAT_SUMMARY to "%1\$s expense · %2\$s income",
    StringKey.SET_CAT_CUSTOM to " · %1\$s yours",
    StringKey.SET_CUR_DETAIL to "%1\$s main",
    StringKey.SET_GUIDES_TOAST to "You'll see a short guide on each main screen.",
    StringKey.SET_GUIDES_AGAIN to "Show the guides again",
    StringKey.SET_GUIDES_DETAIL to "A short guide on each main screen",
    StringKey.ALERT_PLAN_DUE_TITLE to "Scheduled contribution to %1\$s",
    StringKey.ALERT_PLAN_DUE_BODY to "You have a %1\$s %2\$s contribution %3\$s from %4\$s.",
    StringKey.ALERT_PLAN_DUE_TODAY to "today",
    StringKey.ALERT_PLAN_DUE_ON to "on %1\$s",
    StringKey.ALERT_PLANNED_TITLE to "%1\$s is recorded on %2\$s",
    StringKey.ALERT_PLANNED_BODY to "%1\$s · %2\$s · we'll ask you to confirm it",
    StringKey.ALERT_PLAN_AUTO_TITLE to "Automatic contribution recorded",
    StringKey.ALERT_PLAN_AUTO_BODY to "%1\$s %2\$s to %3\$s from %4\$s · %5\$s",
    StringKey.GUEST_TITLE to "Guest mode",
    StringKey.GUEST_BODY to "You're using sample data. Nothing is saved.",
    StringKey.LOAN_DESC_LENT to "Loan to %1\$s",
    StringKey.LOAN_DESC_BORROWED to "Debt with %1\$s",
    StringKey.PLAN_CONFIRM to "Confirm contribution",
    StringKey.PLAN_SKIP to "Skip this time",
    StringKey.PLAN_DONE to "Contribution recorded",
    StringKey.PLAN_SKIPPED to "Contribution skipped. We'll remind you on the next date.",
    StringKey.TERMS_ACCEPT to "I accept the",
    StringKey.TERMS_TERMS to "Terms",
    StringKey.TERMS_AND to "and the",
    StringKey.TERMS_PRIVACY to "Privacy policy",
    StringKey.PW_STRONG to "Strong",
    StringKey.PW_RULES to "At least 8 characters, one uppercase letter and one number.",
    StringKey.PW_HIDE to "Hide password",
    StringKey.PW_SHOW to "Show password",
    StringKey.AUTH_GOOGLE to "Continue with Google",
    StringKey.MV_EMPTY to "You don't have transactions yet. Record the first one with the + button.",
    StringKey.MV_SCHEDULED_ONE to "Scheduled",
    StringKey.REP_WEEK to "Wk %1\$s",
    StringKey.API_OFFLINE to "Couldn't reach the server. Check your connection and try again.",
    StringKey.API_EMAIL_TAKEN to "An account with that email already exists.",
    StringKey.API_EMAIL_TAKEN_GOOGLE to "An account with that email already exists. Sign in with your password, or verify this email with Google first.",
    StringKey.API_WRONG_PASSWORD to "That password isn't right.",
    StringKey.API_SAME_PASSWORD to "The new password must differ from the current one.",
    StringKey.API_PASSWORD_FIRST_EMAIL to "Set a password before changing your email.",
    StringKey.API_PASSWORD_FIRST_DELETE to "Set a password before deleting your account.",
    StringKey.API_GUEST to "Not available in guest mode.",
    StringKey.AUTH_OR to "OR",
    StringKey.MV_SCHEDULED to "Scheduled",
)

fun stringFor(key: StringKey, language: AppLanguage): String =
    (if (language == AppLanguage.EN) EN else ES).getValue(key)

// Maps mock-data ids to their StringKey so every screen that shows a
// category/payment-method name goes through the same translated lookup
// instead of reading the (Spanish-only) `label` field on the mock data
// directly.
fun paymentMethodStringKey(id: PaymentMethod): StringKey = when (id) {
    PaymentMethod.CASH -> StringKey.PAYMENT_CASH
    PaymentMethod.DEBIT_CARD -> StringKey.PAYMENT_DEBIT_CARD
    PaymentMethod.CREDIT_CARD -> StringKey.PAYMENT_CREDIT_CARD
    PaymentMethod.BANK_TRANSFER -> StringKey.PAYMENT_BANK_TRANSFER
    PaymentMethod.NEQUI -> StringKey.PAYMENT_NEQUI
    PaymentMethod.DAVIPLATA -> StringKey.PAYMENT_DAVIPLATA
}

fun budgetStatusStringKey(status: com.s2nova.app.data.model.BudgetStatus): StringKey = when (status) {
    com.s2nova.app.data.model.BudgetStatus.OVER_BUDGET -> StringKey.BUDGET_STATUS_OVER
    com.s2nova.app.data.model.BudgetStatus.NEAR_LIMIT, com.s2nova.app.data.model.BudgetStatus.AT_RISK -> StringKey.BUDGET_STATUS_NEAR
    com.s2nova.app.data.model.BudgetStatus.ON_TRACK -> StringKey.BUDGET_STATUS_ON_TRACK
}

// The app language: the signed-in user's preference, or the last one used
// while signed out. Compose state, so anything that reads it during
// composition (tr(), rememberStrings()) updates when it changes.
object AppLang {
    private const val PREFS = "s2nova_language"
    private var prefs: android.content.SharedPreferences? = null

    var current by mutableStateOf(AppLanguage.ES)
        private set

    fun init(context: Context) {
        prefs = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
        current = if (prefs?.getString("language", null) == "EN") AppLanguage.EN else AppLanguage.ES
    }

    fun set(language: AppLanguage) {
        if (language == current) return
        current = language
        prefs?.edit()?.putString("language", language.name)?.apply()
    }
}

fun tr(key: StringKey): String = stringFor(key, AppLang.current)

// tr(key) with its "%1$s" arguments filled in.
fun tr(key: StringKey, vararg args: Any?): String = stringFor(key, AppLang.current).format(*args)

@Composable
fun rememberStrings(): (StringKey) -> String {
    val language = AppLang.current
    return { key -> stringFor(key, language) }
}

@Composable
fun rememberAppLanguage(): AppLanguage = AppLang.current
